// templates/styling/styled-components/overlays/portfolio/react/src/components/PortfolioFooter.tsx
import styled from 'styled-components';

const StyledFooter = styled.footer`
  background: #111827;
  color: #9ca3af;
  padding: 2rem;
  text-align: center;
  margin-top: auto;
`;

const FooterContent = styled.div`
  max-width: 1100px;
  margin: 0 auto;

  p {
    font-size: 0.85rem;
  }
`;

const FooterLinks = styled.div`
  display: flex;
  gap: 2rem;
  justify-content: center;
  margin-bottom: 1rem;

  a {
    color: #9ca3af;
    text-decoration: none;

    &:hover {
      color: white;
    }
  }
`;

function PortfolioFooter() {
  return (
    <StyledFooter>
      <FooterContent>
        <FooterLinks>
          <a href="#" target="_blank" rel="noopener noreferrer">GitHub</a>
          <a href="#">LinkedIn</a>
          <a href="#">Twitter</a>
        </FooterLinks>
        <p>&copy; 2025 {'{{projectName}}'}. All rights reserved.</p>
      </FooterContent>
    </StyledFooter>
  );
}

export default PortfolioFooter;

// templates/styling/css-modules/overlays/portfolio/vue/src/components/PortfolioFooter.vue
<script setup lang="ts">
</script>

<template>
  <footer :class="$style.portfolioFooter">
    <div :class="$style.socialLinks">
      <a href="#" title="GitHub">🐙</a>
      <a href="#" title="LinkedIn">💼</a>
      <a href="#" title="Twitter">🐦</a>
      <a href="#" title="Email">📧</a>
    </div>
    <p :class="$style.copyright">&copy; 2025 {{projectName}}. Built with passion.</p>
  </footer>
</template>

<style module>
.portfolioFooter {
  background: #111827;
  color: #9ca3af;
  text-align: center;
  padding: 2rem 1.5rem;
  margin-top: auto;
}

.socialLinks {
  display: flex;
  justify-content: center;
  gap: 1rem;
  margin-bottom: 1rem;
}

.socialLinks a {
  color: #9ca3af;
  font-size: 1.25rem;
  text-decoration: none;
  transition: color 0.2s;
}

.socialLinks a:hover {
  color: #fff;
}

.copyright {
  font-size: 0.85rem;
}
</style>
