// templates/overlays/portfolio/angular/src/app/components/project-card.component.ts
import { Component, Input } from '@angular/core';

export interface Project {
  id: number;
  title: string;
  description: string;
  image: string;
  tags: string[];
  category: string;
}

@Component({
  selector: 'app-project-card',
  standalone: true,
  template: `
    <div class="project-card">
      <div class="project-card-image">{{ project.image }}</div>
      <div class="project-card-body">
        <h3 class="project-card-title">{{ project.title }}</h3>
        <p class="project-card-description">{{ project.description }}</p>
        <div class="project-card-tags">
          @for (tag of project.tags; track tag) {
            <span class="project-card-tag">{{ tag }}</span>
          }
        </div>
      </div>
    </div>
  `,
  styles: [`
    .project-card {
      background: #fff;
      border-radius: 12px;
      overflow: hidden;
      box-shadow: 0 1px 3px rgba(0, 0, 0, 0.08);
      transition: transform 0.2s, box-shadow 0.2s;
    }

    .project-card:hover {
      transform: translateY(-4px);
      box-shadow: 0 8px 24px rgba(0, 0, 0, 0.12);
    }

    .project-card-image {
      font-size: 48px;
      text-align: center;
      padding: 32px;
      background: #f3f4f6;
    }

    .project-card-body {
      padding: 20px;
    }

    .project-card-title {
      font-size: 18px;
      font-weight: 700;
      color: #111827;
      margin-bottom: 8px;
    }

    .project-card-description {
      font-size: 14px;
      color: #6b7280;
      line-height: 1.5;
      margin-bottom: 14px;
    }

    .project-card-tags {
      display: flex;
      flex-wrap: wrap;
      gap: 6px;
    }

    .project-card-tag {
      padding: 4px 10px;
      background: #eef2ff;
      color: #4f46e5;
      border-radius: 6px;
      font-size: 12px;
      font-weight: 500;
    }
  `]
})
export class ProjectCardComponent {
  @Input() project!: Project;
}

// templates/styling/css-modules/overlays/portfolio/vue/src/components/ProjectCard.vue
<script setup lang="ts">
import type { Project } from '../data'

defineProps<{ project: Project }>()
</script>

<template>
  <div :class="$style.projectCard">
    <div :class="$style.cardImage">{{ project.image }}</div>
    <div :class="$style.cardBody">
      <div :class="$style.cardTitle">{{ project.title }}</div>
      <div :class="$style.cardDesc">{{ project.description }}</div>
      <div :class="$style.cardTags">
        <span v-for="tag in project.tags" :key="tag">{{ tag }}</span>
      </div>
    </div>
  </div>
</template>

<style module>
.projectCard {
  background: #fff;
  border-radius: 8px;
  overflow: hidden;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.08);
  transition: box-shadow 0.2s, transform 0.2s;
}

.projectCard:hover {
  box-shadow: 0 4px 16px rgba(0, 0, 0, 0.12);
  transform: translateY(-2px);
}

.cardImage {
  background: #eef2ff;
  height: 140px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 3.5rem;
}

.cardBody {
  padding: 1.25rem;
}

.cardTitle {
  font-size: 1.1rem;
  font-weight: 700;
  color: #111827;
  margin-bottom: 0.4rem;
}

.cardDesc {
  font-size: 0.9rem;
  color: #6b7280;
  margin-bottom: 0.75rem;
  line-height: 1.5;
}

.cardTags {
  display: flex;
  flex-wrap: wrap;
  gap: 0.4rem;
}

.cardTags span {
  background: #eef2ff;
  color: #4f46e5;
  font-size: 0.75rem;
  font-weight: 600;
  padding: 0.2rem 0.6rem;
  border-radius: 9999px;
}
</style>
