// templates/styling/chakra-ui/overlays/portfolio/react/src/components/SkillsGrid.tsx
import { SimpleGrid, Box, Heading, Flex, Badge } from '@chakra-ui/react';
import { skills } from '../data/projects';

function SkillsGrid() {
  return (
    <SimpleGrid columns={{ base: 1, sm: 2, lg: 4 }} gap={6} maxW="1100px" mx="auto">
      {skills.map((group, i) => (
        <Box key={i} bg="white" p={6} borderRadius="xl" border="1px solid" borderColor="gray.200">
          <Heading as="h3" size="sm" fontWeight={600} mb={4} color="#4f46e5">
            {group.category}
          </Heading>
          <Flex flexWrap="wrap" gap={2}>
            {group.items.map((skill, j) => (
              <Badge key={j} bg="gray.100" color="gray.700" px={3} py={1} borderRadius="md" fontSize="0.85rem" fontWeight={400}>
                {skill}
              </Badge>
            ))}
          </Flex>
        </Box>
      ))}
    </SimpleGrid>
  );
}

export default SkillsGrid;

// templates/styling/css-modules/overlays/portfolio/vue/src/components/SkillsGrid.vue
<script setup lang="ts">
import { skills } from '../data'
</script>

<template>
  <div :class="$style.skillsSection">
    <div v-for="group in skills" :key="group.category" :class="$style.skillGroup">
      <h3>{{ group.category }}</h3>
      <div :class="$style.skillItems">
        <span v-for="item in group.items" :key="item">{{ item }}</span>
      </div>
    </div>
  </div>
</template>

<style module>
.skillsSection {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
  gap: 1.5rem;
}

.skillGroup {
  background: #fff;
  border-radius: 8px;
  padding: 1.25rem;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.08);
}

.skillGroup h3 {
  font-size: 0.85rem;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: #4f46e5;
  margin-bottom: 0.75rem;
}

.skillItems {
  display: flex;
  flex-wrap: wrap;
  gap: 0.4rem;
}

.skillItems span {
  background: #f3f4f6;
  color: #374151;
  font-size: 0.85rem;
  padding: 0.3rem 0.7rem;
  border-radius: 6px;
}
</style>
