// templates/overlays/ecommerce/nuxt/pages/product/[id].vue
<script setup lang="ts">
interface Product {
  id: number;
  name: string;
  price: number;
  image: string;
  category: string;
  description: string;
}

interface CartItem extends Product {
  quantity: number;
}

const route = useRoute();
const productId = Number(route.params.id);

const products: Product[] = [
  { id: 1, name: 'Wireless Headphones', price: 79.99, image: '🎧', category: 'Electronics', description: 'Premium wireless headphones with noise cancellation.' },
  { id: 2, name: 'Running Shoes', price: 129.99, image: '👟', category: 'Sports', description: 'Lightweight running shoes for daily training.' },
  { id: 3, name: 'Coffee Maker', price: 49.99, image: '☕', category: 'Home', description: 'Programmable coffee maker with thermal carafe.' },
  { id: 4, name: 'Backpack', price: 59.99, image: '🎒', category: 'Accessories', description: 'Water-resistant laptop backpack.' },
  { id: 5, name: 'Smartwatch', price: 199.99, image: '⌚', category: 'Electronics', description: 'Fitness tracking smartwatch.' },
  { id: 6, name: 'Desk Lamp', price: 34.99, image: '💡', category: 'Home', description: 'LED desk lamp with adjustable brightness.' },
  { id: 7, name: 'Yoga Mat', price: 29.99, image: '🧘', category: 'Sports', description: 'Non-slip yoga mat with carrying strap.' },
  { id: 8, name: 'Sunglasses', price: 89.99, image: '🕶️', category: 'Accessories', description: 'Polarized sunglasses with UV protection.' },
];

const product = products.find(p => p.id === productId);
const quantity = ref(1);
const added = ref(false);

const cart = useState<CartItem[]>('cart');

function addToCart() {
  if (!product) return;
  const existing = cart.value.find(item => item.id === product.id);
  if (existing) {
    existing.quantity += quantity.value;
  } else {
    cart.value.push({ ...product, quantity: quantity.value });
  }
  added.value = true;
  setTimeout(() => { added.value = false; }, 2000);
}
</script>

<template>
  <div v-if="product" class="product-detail">
    <NuxtLink to="/" class="back-link">← Back to Shop</NuxtLink>

    <div class="product-layout">
      <div class="product-image">
        <span class="image-emoji">{{ product.image }}</span>
      </div>

      <div class="product-info">
        <span class="product-category">{{ product.category }}</span>
        <h1 class="product-name">{{ product.name }}</h1>
        <p class="product-price">${{ product.price.toFixed(2) }}</p>
        <p class="product-desc">{{ product.description }}</p>

        <div class="add-to-cart-section">
          <div class="quantity-control">
            <button @click="quantity = Math.max(1, quantity - 1)">-</button>
            <span>{{ quantity }}</span>
            <button @click="quantity++">+</button>
          </div>
          <button class="add-btn" @click="addToCart">
            {{ added ? '✓ Added!' : 'Add to Cart' }}
          </button>
        </div>
      </div>
    </div>
  </div>

  <div v-else class="not-found">
    <h2>Product not found</h2>
    <NuxtLink to="/" class="back-link">← Back to Shop</NuxtLink>
  </div>
</template>

<style scoped>
.back-link {
  display: inline-block;
  color: #4f46e5;
  margin-bottom: 1.5rem;
  font-weight: 500;
}

.back-link:hover {
  text-decoration: underline;
}

.product-layout {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 3rem;
  align-items: start;
}

.product-image {
  background: white;
  border-radius: 12px;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 3rem;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
}

.image-emoji {
  font-size: 8rem;
}

.product-category {
  display: inline-block;
  background: #eef2ff;
  color: #4f46e5;
  padding: 0.25rem 0.75rem;
  border-radius: 20px;
  font-size: 0.8rem;
  font-weight: 500;
  margin-bottom: 0.75rem;
}

.product-name {
  font-size: 2rem;
  color: #111827;
  margin-bottom: 0.75rem;
}

.product-price {
  font-size: 1.75rem;
  color: #4f46e5;
  font-weight: 700;
  margin-bottom: 1rem;
}

.product-desc {
  color: #6b7280;
  line-height: 1.7;
  margin-bottom: 2rem;
}

.add-to-cart-section {
  display: flex;
  gap: 1rem;
  align-items: center;
}

.quantity-control {
  display: flex;
  align-items: center;
  border: 1px solid #d1d5db;
  border-radius: 8px;
  overflow: hidden;
}

.quantity-control button {
  background: #f3f4f6;
  border: none;
  padding: 0.5rem 1rem;
  font-size: 1.1rem;
  cursor: pointer;
}

.quantity-control button:hover {
  background: #e5e7eb;
}

.quantity-control span {
  padding: 0.5rem 1rem;
  font-weight: 600;
  min-width: 3rem;
  text-align: center;
}

.add-btn {
  background: #4f46e5;
  color: white;
  border: none;
  padding: 0.75rem 2rem;
  border-radius: 8px;
  font-size: 1rem;
  font-weight: 600;
  cursor: pointer;
  transition: background 0.2s;
}

.add-btn:hover {
  background: #4338ca;
}

.not-found {
  text-align: center;
  padding: 4rem 0;
}

.not-found h2 {
  color: #111827;
  margin-bottom: 1rem;
}

@media (max-width: 768px) {
  .product-layout {
    grid-template-columns: 1fr;
    gap: 1.5rem;
  }
}
</style>

// templates/styling/chakra-ui/overlays/ecommerce/nextjs/src/app/product/[id]/page.tsx
'use client';

import { useParams } from 'next/navigation';
import Link from 'next/link';
import { Box, Heading, Text, Button, Badge, SimpleGrid, Center, VStack } from '@chakra-ui/react';
import { useCart, Product } from '../../components/CartProvider';

const products: Product[] = [
  { id: 1, name: 'Wireless Headphones', price: 79.99, image: '🎧', category: 'Electronics', rating: 4.5, description: 'Premium wireless headphones with noise cancellation and 30-hour battery life. Crystal-clear sound quality for music lovers.' },
  { id: 2, name: 'Smart Watch', price: 199.99, image: '⌚', category: 'Electronics', rating: 4.7, description: 'Feature-packed smartwatch with health monitoring, GPS tracking, and a vibrant AMOLED display.' },
  { id: 3, name: 'Running Shoes', price: 129.99, image: '👟', category: 'Sports', rating: 4.3, description: 'Lightweight running shoes with responsive cushioning and breathable mesh upper for maximum comfort.' },
  { id: 4, name: 'Backpack', price: 59.99, image: '🎒', category: 'Accessories', rating: 4.6, description: 'Durable travel backpack with laptop compartment, water-resistant fabric, and ergonomic design.' },
  { id: 5, name: 'Coffee Maker', price: 89.99, image: '☕', category: 'Home', rating: 4.4, description: 'Programmable coffee maker with thermal carafe, brew-strength control, and auto-shutoff feature.' },
  { id: 6, name: 'Desk Lamp', price: 45.99, image: '💡', category: 'Home', rating: 4.2, description: 'Adjustable LED desk lamp with multiple brightness levels, color temperatures, and USB charging port.' },
  { id: 7, name: 'Yoga Mat', price: 34.99, image: '🧘', category: 'Sports', rating: 4.8, description: 'Non-slip yoga mat with alignment marks, eco-friendly material, and carrying strap included.' },
  { id: 8, name: 'Sunglasses', price: 149.99, image: '🕶️', category: 'Accessories', rating: 4.1, description: 'Polarized sunglasses with UV400 protection, lightweight titanium frame, and scratch-resistant lenses.' },
];

export default function ProductDetailPage() {
  const params = useParams();
  const { addToCart } = useCart();
  const product = products.find((p) => p.id === Number(params.id));

  if (!product) {
    return (
      <Center py={16} flexDirection="column" gap={4}>
        <Heading as="h2" size="lg">Product Not Found</Heading>
        <Text color="gray.500">The product you are looking for does not exist.</Text>
        <Button as={Link} href="/" bg="#4f46e5" color="white" _hover={{ bg: '#4338ca' }}>Back to Shop</Button>
      </Center>
    );
  }

  return (
    <Box maxW="1000px" mx="auto" py={8} px={6}>
      <Box as={Link} href="/" color="#4f46e5" fontWeight={500} textDecoration="none" display="inline-block" mb={6} _hover={{ textDecoration: 'underline' }}>← Back to Shop</Box>
      <SimpleGrid columns={{ base: 1, md: 2 }} gap={12}>
        <Center h="400px" fontSize="8xl" bg="white" borderRadius="xl" boxShadow="sm">{product.image}</Center>
        <VStack align="flex-start" gap={4}>
          <Badge color="#4f46e5" fontSize="0.75rem" fontWeight={600} textTransform="uppercase" bg="transparent" p={0}>{product.category}</Badge>
          <Heading as="h1" size="xl" color="gray.900">{product.name}</Heading>
          <Text fontSize="0.85rem" color="gray.500">{'⭐'.repeat(Math.floor(product.rating))} {product.rating} / 5.0</Text>
          <Text fontSize="2xl" fontWeight={700} color="#4f46e5">${product.price.toFixed(2)}</Text>
          <Text color="gray.700" lineHeight={1.7}>{product.description}</Text>
          <Button bg="#4f46e5" color="white" size="lg" px={8} borderRadius="lg" fontWeight={600} _hover={{ bg: '#4338ca' }} onClick={() => addToCart(product)}>Add to Cart</Button>
          <Box mt={4}>
            <Heading as="h3" size="sm" color="gray.900" mb={3}>Features</Heading>
            <VStack align="flex-start" gap={1} color="gray.700">
              <Text>Free shipping on orders over $50</Text>
              <Text>30-day return policy</Text>
              <Text>1-year warranty</Text>
              <Text>Secure checkout</Text>
            </VStack>
          </Box>
        </VStack>
      </SimpleGrid>
    </Box>
  );
}
