// templates/styling/chakra-ui/overlays/landing/nextjs/src/app/components/Hero.tsx
'use client';

import { Box, Flex, Heading, Text, Button, HStack, Link } from '@chakra-ui/react';

export function Hero() {
  return (
    <Box as="header" bgGradient="linear-gradient(135deg, #667eea 0%, #764ba2 100%)" color="white" pb={16}>
      <Flex as="nav" justify="space-between" align="center" maxW="1200px" mx="auto" px={8} py={4}>
        <Heading size="lg" color="white">{'{{projectName}}'}</Heading>
        <HStack gap={8} display={{ base: 'none', md: 'flex' }}>
          <Link href="#features" color="whiteAlpha.900" textDecoration="none" fontWeight={500} _hover={{ color: 'white' }}>Features</Link>
          <Link href="#cta" color="whiteAlpha.900" textDecoration="none" fontWeight={500} _hover={{ color: 'white' }}>Pricing</Link>
          <Link href="#contact" color="whiteAlpha.900" textDecoration="none" fontWeight={500} _hover={{ color: 'white' }}>Contact</Link>
        </HStack>
      </Flex>
      <Box textAlign="center" px={8} py={16} maxW="800px" mx="auto">
        <Heading as="h1" fontSize={{ base: '2.5rem', md: '3.5rem' }} fontWeight={800} mb={6} lineHeight={1.1}>
          Build Something Amazing
        </Heading>
        <Text fontSize="xl" opacity={0.9} mb={8}>
          A modern landing page template to kickstart your next project.
        </Text>
        <HStack gap={4} justify="center" flexWrap="wrap">
          <Button bg="#4f46e5" color="white" px={6} py={5} borderRadius="lg" fontWeight={600} border="2px solid" borderColor="#4f46e5" _hover={{ bg: '#4338ca', borderColor: '#4338ca' }}>
            Get Started
          </Button>
          <Button bg="transparent" color="white" px={6} py={5} borderRadius="lg" fontWeight={600} border="2px solid" borderColor="whiteAlpha.500" _hover={{ bg: 'whiteAlpha.100', borderColor: 'white' }}>
            Learn More
          </Button>
        </HStack>
      </Box>
    </Box>
  );
}

// templates/overlays/landing/vue/src/components/Hero.vue
<template>
  <header class="hero">
    <nav class="nav">
      <div class="logo">{{projectName}}</div>
      <div class="nav-links">
        <a href="#features">Features</a>
        <a href="#cta">Pricing</a>
        <a href="#contact">Contact</a>
      </div>
    </nav>
    <div class="hero-content">
      <h1>Build Something Amazing</h1>
      <p>A modern landing page template to kickstart your next project.</p>
      <div class="hero-actions">
        <button class="btn btn-primary">Get Started</button>
        <button class="btn btn-secondary">Learn More</button>
      </div>
    </div>
  </header>
</template>

<style scoped>
.hero { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding-bottom: 4rem; }
.nav { display: flex; justify-content: space-between; align-items: center; padding: 1rem 2rem; max-width: 1200px; margin: 0 auto; }
.logo { font-size: 1.5rem; font-weight: 700; color: white; }
.nav-links { display: flex; gap: 2rem; }
.nav-links a { color: rgba(255,255,255,0.9); text-decoration: none; font-weight: 500; }
.hero-content { text-align: center; padding: 4rem 2rem; max-width: 800px; margin: 0 auto; }
.hero-content h1 { font-size: 3.5rem; font-weight: 800; margin-bottom: 1.5rem; line-height: 1.1; }
.hero-content p { font-size: 1.25rem; opacity: 0.9; margin-bottom: 2rem; }
.hero-actions { display: flex; gap: 1rem; justify-content: center; }
.btn { padding: 0.75rem 1.5rem; border-radius: 8px; font-size: 1rem; font-weight: 600; cursor: pointer; border: 2px solid transparent; }
.btn-primary { background: #4f46e5; color: white; border-color: #4f46e5; }
.btn-secondary { background: transparent; color: white; border-color: rgba(255,255,255,0.5); }
</style>
