// templates/styling/styled-components/overlays/crm/react/src/pages/Settings.tsx
import styled from 'styled-components';

const CRMHeader = styled.header`
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 2rem;

  h1 {
    font-size: 1.75rem;
    font-weight: 700;
    color: #111827;
    margin: 0;
  }
`;

const SettingsCard = styled.div`
  background: white;
  border-radius: 12px;
  padding: 2rem;
  border: 1px solid #e5e7eb;
  max-width: 500px;
`;

const SettingsForm = styled.form`
  display: flex;
  flex-direction: column;
  gap: 1.25rem;
`;

const FormGroup = styled.div`
  display: flex;
  flex-direction: column;
  gap: 0.4rem;

  label {
    font-size: 0.85rem;
    font-weight: 600;
    color: #374151;
  }

  input, select {
    padding: 0.6rem 0.75rem;
    border: 1px solid #d1d5db;
    border-radius: 8px;
    font-size: 0.9rem;
    font-family: inherit;

    &:focus {
      outline: none;
      border-color: #4f46e5;
    }
  }
`;

const PrimaryButton = styled.button`
  background: #4f46e5;
  color: white;
  border: none;
  padding: 0.6rem 1.25rem;
  border-radius: 8px;
  cursor: pointer;
  font-weight: 600;
  font-size: 0.9rem;

  &:hover {
    background: #4338ca;
  }
`;

function Settings() {
  return (
    <div>
      <CRMHeader>
        <h1>Settings</h1>
      </CRMHeader>
      <SettingsCard>
        <SettingsForm onSubmit={(e) => e.preventDefault()}>
          <FormGroup>
            <label htmlFor="companyName">Company Name</label>
            <input type="text" id="companyName" defaultValue="My Company" />
          </FormGroup>
          <FormGroup>
            <label htmlFor="email">Email Address</label>
            <input type="email" id="email" defaultValue="admin@company.com" />
          </FormGroup>
          <FormGroup>
            <label htmlFor="timezone">Timezone</label>
            <select id="timezone" defaultValue="UTC-5">
              <option value="UTC-8">Pacific Time (UTC-8)</option>
              <option value="UTC-7">Mountain Time (UTC-7)</option>
              <option value="UTC-6">Central Time (UTC-6)</option>
              <option value="UTC-5">Eastern Time (UTC-5)</option>
              <option value="UTC+0">UTC</option>
              <option value="UTC+1">Central European (UTC+1)</option>
            </select>
          </FormGroup>
          <PrimaryButton type="submit">Save Changes</PrimaryButton>
        </SettingsForm>
      </SettingsCard>
    </div>
  );
}

export default Settings;

// templates/styling/css-modules/overlays/crm/vue/src/pages/Settings.vue
<script setup lang="ts">
import { ref } from 'vue'

const companyName = ref('My Company')
const email = ref('admin@company.com')
const saved = ref(false)

const save = () => {
  saved.value = true
  setTimeout(() => (saved.value = false), 2000)
}
</script>

<template>
  <div>
    <div :class="$style.pageHeader">
      <h1>Settings</h1>
      <p>Manage your CRM preferences</p>
    </div>
    <div :class="$style.settingsForm">
      <div :class="$style.formGroup">
        <label>Company Name</label>
        <input v-model="companyName" type="text" />
      </div>
      <div :class="$style.formGroup">
        <label>Email Address</label>
        <input v-model="email" type="email" />
      </div>
      <button :class="$style.btnPrimary" @click="save">Save Changes</button>
      <p v-if="saved" style="color: #059669; margin-top: 0.75rem; font-size: 0.85rem;">Settings saved successfully!</p>
    </div>
  </div>
</template>

<style module>
.pageHeader {
  margin-bottom: 1.5rem;
}

.pageHeader h1 {
  font-size: 1.5rem;
  color: #111827;
  font-weight: 700;
}

.pageHeader p {
  color: #6b7280;
  font-size: 0.9rem;
}

.settingsForm {
  background: #fff;
  border-radius: 8px;
  padding: 1.5rem;
  max-width: 500px;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.08);
}

.formGroup {
  margin-bottom: 1.25rem;
}

.formGroup label {
  display: block;
  font-size: 0.85rem;
  font-weight: 600;
  color: #374151;
  margin-bottom: 0.4rem;
}

.formGroup input {
  width: 100%;
  padding: 0.6rem 0.75rem;
  border: 1px solid #d1d5db;
  border-radius: 6px;
  font-size: 0.9rem;
  outline: none;
}

.formGroup input:focus {
  border-color: #4f46e5;
}

.btnPrimary {
  background: #4f46e5;
  color: #fff;
  border: none;
  padding: 0.6rem 1.5rem;
  border-radius: 6px;
  font-size: 0.9rem;
  font-weight: 600;
  cursor: pointer;
  transition: background 0.2s;
}

.btnPrimary:hover {
  background: #4338ca;
}
</style>
