// templates/styling/tailwind/overlays/dashboard/vue/src/pages/Overview.vue
<script setup lang="ts">
import KPICards from '../components/KPICards.vue';
import ChartPlaceholder from '../components/ChartPlaceholder.vue';
import DataTable from '../components/DataTable.vue';
</script>

<template>
  <div>
    <div class="mb-8">
      <h1 class="text-2xl font-bold text-gray-900">Overview</h1>
      <p class="text-gray-500 mt-1">Welcome back. Here is what is happening today.</p>
    </div>
    <KPICards />
    <ChartPlaceholder title="Monthly Revenue" />
    <DataTable />
  </div>
</template>

// templates/styling/css-modules/overlays/dashboard/react/src/pages/Overview.tsx
import { KPICards } from '../components/KPICards';
import { ChartPlaceholder } from '../components/ChartPlaceholder';
import { DataTable } from '../components/DataTable';
import styles from './Overview.module.css';

export function Overview() {
  return (
    <div>
      <div className={styles.pageHeader}>
        <h1>Dashboard</h1>
        <div className={styles.headerActions}>
          <input type="text" placeholder="Search..." className={styles.searchInput} />
          <div className={styles.userAvatar}>B</div>
        </div>
      </div>
      <KPICards />
      <div className={styles.dashboardGrid}>
        <ChartPlaceholder title="Revenue Overview" />
        <ChartPlaceholder title="User Growth" />
      </div>
      <DataTable />
    </div>
  );
}
