// templates/styling/css-modules/overlays/crm/nuxt/pages/deals.vue
<script setup lang="ts">
interface Deal { id: number; title: string; company: string; value: string; contact: string; }
interface Column { id: string; title: string; color: string; deals: Deal[]; }

const columns: Column[] = [
  { id: 'lead', title: 'Lead', color: '#6b7280', deals: [
    { id: 1, title: 'Website Redesign', company: 'Acme Inc', value: '$12,000', contact: 'John Doe' },
    { id: 2, title: 'Mobile App', company: 'StartupXYZ', value: '$25,000', contact: 'Mike Johnson' },
  ]},
  { id: 'qualified', title: 'Qualified', color: '#3b82f6', deals: [
    { id: 3, title: 'Cloud Migration', company: 'BigCo', value: '$45,000', contact: 'Emily Davis' },
    { id: 4, title: 'SEO Campaign', company: 'Tech Labs', value: '$8,500', contact: 'Jane Smith' },
  ]},
  { id: 'proposal', title: 'Proposal', color: '#f59e0b', deals: [
    { id: 5, title: 'ERP Integration', company: 'Skynet Corp', value: '$68,000', contact: 'Sarah Connor' },
  ]},
  { id: 'closed', title: 'Closed Won', color: '#10b981', deals: [
    { id: 6, title: 'Brand Identity', company: 'DevStudio', value: '$15,000', contact: 'Chris Wilson' },
    { id: 7, title: 'Data Analytics', company: 'Acme Inc', value: '$32,000', contact: 'John Doe' },
  ]},
];
</script>

<template>
  <div>
    <div :class="$style.pageHeader">
      <div>
        <h1>Deals Pipeline</h1>
        <p :class="$style.subtitle">Track and manage your sales pipeline.</p>
      </div>
      <button :class="$style.addBtn">+ New Deal</button>
    </div>

    <div :class="$style.kanbanBoard">
      <div v-for="col in columns" :key="col.id" :class="$style.kanbanColumn">
        <div :class="$style.columnHeader">
          <span :class="$style.columnDot" :style="{ backgroundColor: col.color }"></span>
          <h3 :class="$style.columnTitle">{{ col.title }}</h3>
          <span :class="$style.columnCount">{{ col.deals.length }}</span>
        </div>
        <div :class="$style.columnCards">
          <div v-for="deal in col.deals" :key="deal.id" :class="$style.dealCard">
            <h4 :class="$style.dealTitle">{{ deal.title }}</h4>
            <p :class="$style.dealCompany">{{ deal.company }}</p>
            <div :class="$style.dealFooter">
              <span :class="$style.dealValue">{{ deal.value }}</span>
              <span :class="$style.dealContact">{{ deal.contact }}</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style module>
.pageHeader { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 2rem; }
.pageHeader h1 { font-size: 1.75rem; color: #111827; margin-bottom: 0.25rem; }
.subtitle { color: #6b7280; }
.addBtn { background: #4f46e5; color: white; border: none; padding: 0.65rem 1.25rem; border-radius: 8px; font-weight: 600; cursor: pointer; transition: background 0.2s; }
.addBtn:hover { background: #4338ca; }
.kanbanBoard { display: grid; grid-template-columns: repeat(4, 1fr); gap: 1rem; overflow-x: auto; }
.kanbanColumn { background: #f9fafb; border-radius: 10px; padding: 1rem; min-width: 240px; }
.columnHeader { display: flex; align-items: center; gap: 0.5rem; margin-bottom: 1rem; padding-bottom: 0.75rem; border-bottom: 2px solid #e5e7eb; }
.columnDot { width: 10px; height: 10px; border-radius: 50%; }
.columnTitle { font-size: 0.95rem; color: #111827; flex: 1; }
.columnCount { background: #e5e7eb; color: #374151; font-size: 0.75rem; font-weight: 700; width: 22px; height: 22px; border-radius: 50%; display: flex; align-items: center; justify-content: center; }
.columnCards { display: flex; flex-direction: column; gap: 0.75rem; }
.dealCard { background: white; border-radius: 8px; padding: 1rem; box-shadow: 0 1px 3px rgba(0, 0, 0, 0.08); cursor: pointer; transition: box-shadow 0.2s; }
.dealCard:hover { box-shadow: 0 4px 12px rgba(0, 0, 0, 0.12); }
.dealTitle { font-size: 0.95rem; color: #111827; margin-bottom: 0.25rem; }
.dealCompany { font-size: 0.8rem; color: #6b7280; margin-bottom: 0.75rem; }
.dealFooter { display: flex; justify-content: space-between; align-items: center; }
.dealValue { font-size: 0.85rem; font-weight: 700; color: #4f46e5; }
.dealContact { font-size: 0.75rem; color: #9ca3af; }

@media (max-width: 1024px) { .kanbanBoard { grid-template-columns: repeat(2, 1fr); } }
@media (max-width: 640px) { .kanbanBoard { grid-template-columns: 1fr; } }
</style>

// templates/styling/styled-components/overlays/crm/nextjs/src/app/deals/page.tsx
'use client';

import styled from 'styled-components';

const PageHeader = styled.div`margin-bottom: 2rem; h1 { font-size: 1.75rem; color: #111827; font-weight: 700; } p { color: #6b7280; margin-top: 0.25rem; }`;

const DealsBoard = styled.div`display: grid; grid-template-columns: repeat(4, 1fr); gap: 1rem; @media (max-width: 768px) { grid-template-columns: 1fr; }`;
const DealsColumn = styled.div`background: white; border-radius: 12px; padding: 1rem; box-shadow: 0 1px 3px rgba(0,0,0,0.08);`;
const ColumnHeader = styled.div`display: flex; justify-content: space-between; align-items: center; margin-bottom: 0.5rem;`;
const ColumnTitle = styled.h3`font-size: 0.95rem; font-weight: 600; color: #111827;`;
const ColumnCount = styled.span`background: #f3f4f6; padding: 0.15rem 0.5rem; border-radius: 10px; font-size: 0.75rem; color: #6b7280; font-weight: 600;`;
const ColumnTotal = styled.p`font-size: 0.85rem; color: #6b7280; margin-bottom: 1rem; padding-bottom: 0.75rem; border-bottom: 2px solid #4f46e5;`;
const ColumnCards = styled.div`display: flex; flex-direction: column; gap: 0.75rem;`;
const DealCard = styled.div`background: #f9fafb; border-radius: 8px; padding: 1rem; border: 1px solid #e5e7eb;`;
const DealCompany = styled.h4`font-size: 0.95rem; font-weight: 600; color: #111827; margin: 0 0 0.25rem;`;
const DealValue = styled.p`font-size: 1.1rem; font-weight: 700; color: #4f46e5; margin: 0.25rem 0;`;
const DealContact = styled.span`font-size: 0.8rem; color: #6b7280;`;

interface Deal { id: number; company: string; value: number; contact: string; stage: string; }

const deals: Deal[] = [
  { id: 1, company: 'TechCorp Inc.', value: 45000, contact: 'Sarah Chen', stage: 'Prospect' },
  { id: 2, company: 'Innovate.io', value: 28000, contact: 'James Wilson', stage: 'Proposal' },
  { id: 3, company: 'DesignLab Co.', value: 15000, contact: 'Maria Garcia', stage: 'Qualified' },
  { id: 4, company: 'GlobalNet Ltd.', value: 62000, contact: 'Robert Kim', stage: 'Won' },
  { id: 5, company: 'StartupXYZ', value: 18500, contact: 'Emily Brown', stage: 'Proposal' },
  { id: 6, company: 'Oscorp Labs', value: 34000, contact: 'Michael Davis', stage: 'Prospect' },
  { id: 7, company: 'LexCorp', value: 55000, contact: 'Rachel Green', stage: 'Qualified' },
  { id: 8, company: 'Umbrella Co.', value: 21000, contact: 'Lisa Wang', stage: 'Won' },
];

const stages = ['Prospect', 'Qualified', 'Proposal', 'Won'];

export default function DealsPage() {
  const pipelineTotal = deals.filter((d) => d.stage !== 'Won').reduce((sum, d) => sum + d.value, 0);

  return (
    <div>
      <PageHeader><h1>Deals Pipeline</h1><p>Pipeline value: ${pipelineTotal.toLocaleString()}</p></PageHeader>
      <DealsBoard>
        {stages.map((stage) => {
          const stageDeals = deals.filter((d) => d.stage === stage);
          const stageTotal = stageDeals.reduce((sum, d) => sum + d.value, 0);
          return (
            <DealsColumn key={stage}>
              <ColumnHeader><ColumnTitle>{stage}</ColumnTitle><ColumnCount>{stageDeals.length}</ColumnCount></ColumnHeader>
              <ColumnTotal>${stageTotal.toLocaleString()}</ColumnTotal>
              <ColumnCards>
                {stageDeals.map((deal) => (
                  <DealCard key={deal.id}>
                    <DealCompany>{deal.company}</DealCompany>
                    <DealValue>${deal.value.toLocaleString()}</DealValue>
                    <DealContact>👤 {deal.contact}</DealContact>
                  </DealCard>
                ))}
              </ColumnCards>
            </DealsColumn>
          );
        })}
      </DealsBoard>
    </div>
  );
}
