// templates/styling/material-ui/overlays/dashboard/react/src/components/DataTable.tsx
import {
  Card, Box, Typography, Button, Table, TableHead, TableBody, TableRow, TableCell, Chip,
} from '@mui/material';

interface Order {
  id: string;
  customer: string;
  email: string;
  amount: string;
  status: 'Completed' | 'Processing' | 'Cancelled';
}

const rows: Order[] = [
  { id: '#3210', customer: 'Olivia Martin', email: 'olivia@email.com', amount: '$42.00', status: 'Completed' },
  { id: '#3209', customer: 'Ava Johnson', email: 'ava@email.com', amount: '$74.99', status: 'Processing' },
  { id: '#3208', customer: 'Michael Brown', email: 'michael@email.com', amount: '$64.00', status: 'Completed' },
  { id: '#3207', customer: 'Lisa Anderson', email: 'lisa@email.com', amount: '$49.99', status: 'Cancelled' },
  { id: '#3206', customer: 'Thomas Wilson', email: 'thomas@email.com', amount: '$120.00', status: 'Completed' },
];

const statusColors: Record<string, { bg: string; color: string }> = {
  Completed: { bg: '#d1fae5', color: '#065f46' },
  Processing: { bg: '#dbeafe', color: '#1e40af' },
  Cancelled: { bg: '#fee2e2', color: '#991b1b' },
};

export function DataTable() {
  return (
    <Card sx={{ borderRadius: 3, overflow: 'hidden' }}>
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', px: 3, py: 2 }}>
        <Typography variant="h6" sx={{ fontWeight: 600, color: '#111827' }}>
          Recent Orders
        </Typography>
        <Button variant="outlined" size="small" sx={{ textTransform: 'none', color: '#374151', borderColor: '#d1d5db' }}>
          View All
        </Button>
      </Box>
      <Table>
        <TableHead>
          <TableRow sx={{ bgcolor: '#f9fafb' }}>
            <TableCell sx={{ color: '#6b7280', fontWeight: 600, fontSize: '0.8rem', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Order</TableCell>
            <TableCell sx={{ color: '#6b7280', fontWeight: 600, fontSize: '0.8rem', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Customer</TableCell>
            <TableCell sx={{ color: '#6b7280', fontWeight: 600, fontSize: '0.8rem', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Email</TableCell>
            <TableCell sx={{ color: '#6b7280', fontWeight: 600, fontSize: '0.8rem', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Amount</TableCell>
            <TableCell sx={{ color: '#6b7280', fontWeight: 600, fontSize: '0.8rem', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Status</TableCell>
          </TableRow>
        </TableHead>
        <TableBody>
          {rows.map((row, i) => (
            <TableRow key={i} sx={{ '&:hover': { bgcolor: '#f9fafb' } }}>
              <TableCell sx={{ color: '#374151' }}>{row.id}</TableCell>
              <TableCell sx={{ color: '#374151' }}>{row.customer}</TableCell>
              <TableCell sx={{ color: '#374151' }}>{row.email}</TableCell>
              <TableCell sx={{ color: '#374151' }}>{row.amount}</TableCell>
              <TableCell>
                <Chip
                  label={row.status}
                  size="small"
                  sx={{ bgcolor: statusColors[row.status].bg, color: statusColors[row.status].color, fontWeight: 500 }}
                />
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </Card>
  );
}

// templates/styling/css-modules/overlays/dashboard/vue/src/components/DataTable.vue
<script setup lang="ts">
import { useCssModule } from 'vue';

const style = useCssModule();

const orders = [
  { id: '#3210', customer: 'Sarah Johnson', amount: '$245.00', status: 'Completed', badge: 'badgeSuccess' },
  { id: '#3209', customer: 'Mike Peters', amount: '$129.50', status: 'Processing', badge: 'badgeWarning' },
  { id: '#3208', customer: 'Emily Chen', amount: '$89.99', status: 'Completed', badge: 'badgeSuccess' },
  { id: '#3207', customer: 'James Wilson', amount: '$312.00', status: 'Cancelled', badge: 'badgeDanger' },
  { id: '#3206', customer: 'Anna Lee', amount: '$175.25', status: 'Shipped', badge: 'badgeInfo' },
  { id: '#3205', customer: 'Tom Davis', amount: '$98.00', status: 'Completed', badge: 'badgeSuccess' },
];

function badgeClass(badge: string) {
  return style[badge] || '';
}
</script>

<template>
  <div :class="$style.dataTableWrapper">
    <div :class="$style.tableHeader">Recent Orders</div>
    <table :class="$style.dataTable">
      <thead>
        <tr>
          <th>Order ID</th>
          <th>Customer</th>
          <th>Amount</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="order in orders" :key="order.id">
          <td>{{ order.id }}</td>
          <td>{{ order.customer }}</td>
          <td>{{ order.amount }}</td>
          <td><span :class="badgeClass(order.badge)">{{ order.status }}</span></td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<style module>
.dataTableWrapper {
  background: #ffffff;
  border: 1px solid #e5e7eb;
  border-radius: 12px;
  overflow: hidden;
  margin-bottom: 2rem;
}

.tableHeader {
  padding: 1rem 1.5rem;
  border-bottom: 1px solid #e5e7eb;
  font-weight: 600;
  color: #111827;
}

.dataTable {
  width: 100%;
  border-collapse: collapse;
}

.dataTable th {
  text-align: left;
  padding: 0.75rem 1.5rem;
  font-size: 0.8rem;
  font-weight: 600;
  color: #6b7280;
  text-transform: uppercase;
  border-bottom: 1px solid #e5e7eb;
  background: #f9fafb;
}

.dataTable td {
  padding: 0.75rem 1.5rem;
  border-bottom: 1px solid #f3f4f6;
  font-size: 0.9rem;
}

.dataTable tr:last-child td {
  border-bottom: none;
}

.dataTable tr:hover {
  background: #f9fafb;
}

.badgeSuccess {
  display: inline-block;
  padding: 0.2rem 0.75rem;
  border-radius: 9999px;
  font-size: 0.8rem;
  font-weight: 600;
  background: #d1fae5;
  color: #065f46;
}

.badgeWarning {
  display: inline-block;
  padding: 0.2rem 0.75rem;
  border-radius: 9999px;
  font-size: 0.8rem;
  font-weight: 600;
  background: #fef3c7;
  color: #92400e;
}

.badgeDanger {
  display: inline-block;
  padding: 0.2rem 0.75rem;
  border-radius: 9999px;
  font-size: 0.8rem;
  font-weight: 600;
  background: #fee2e2;
  color: #991b1b;
}

.badgeInfo {
  display: inline-block;
  padding: 0.2rem 0.75rem;
  border-radius: 9999px;
  font-size: 0.8rem;
  font-weight: 600;
  background: #dbeafe;
  color: #1e40af;
}
</style>
