// templates/styling/tailwind/overlays/dashboard/angular/src/app/components/data-table.component.ts
import { Component } from '@angular/core';

interface OrderItem {
  id: number;
  customer: string;
  amount: string;
  status: 'Completed' | 'Shipped' | 'Pending' | 'Cancelled';
}

@Component({
  selector: 'app-data-table',
  standalone: true,
  template: `
    <div class="bg-white rounded-xl p-5 border border-gray-200">
      <h3 class="text-base font-semibold text-gray-900 mb-4">Recent Orders</h3>
      <table class="w-full border-collapse">
        <thead>
          <tr>
            <th class="text-left px-3 py-2 text-xs text-gray-500 uppercase font-semibold border-b-2 border-gray-200">Order</th>
            <th class="text-left px-3 py-2 text-xs text-gray-500 uppercase font-semibold border-b-2 border-gray-200">Customer</th>
            <th class="text-left px-3 py-2 text-xs text-gray-500 uppercase font-semibold border-b-2 border-gray-200">Amount</th>
            <th class="text-left px-3 py-2 text-xs text-gray-500 uppercase font-semibold border-b-2 border-gray-200">Status</th>
          </tr>
        </thead>
        <tbody>
          @for (order of orders; track order.id) {
            <tr>
              <td class="px-3 py-3 border-b border-gray-100 text-sm">#{{ order.id }}</td>
              <td class="px-3 py-3 border-b border-gray-100 text-sm">{{ order.customer }}</td>
              <td class="px-3 py-3 border-b border-gray-100 text-sm">{{ order.amount }}</td>
              <td class="px-3 py-3 border-b border-gray-100 text-sm">
                <span
                  class="px-2 py-0.5 rounded-full text-xs font-semibold"
                  [class.bg-emerald-100]="order.status === 'Completed'"
                  [class.text-emerald-600]="order.status === 'Completed'"
                  [class.bg-amber-100]="order.status === 'Pending'"
                  [class.text-amber-600]="order.status === 'Pending'"
                  [class.bg-blue-100]="order.status === 'Shipped'"
                  [class.text-blue-600]="order.status === 'Shipped'"
                  [class.bg-red-100]="order.status === 'Cancelled'"
                  [class.text-red-600]="order.status === 'Cancelled'"
                >
                  {{ order.status }}
                </span>
              </td>
            </tr>
          }
        </tbody>
      </table>
    </div>
  `,
  styles: []
})
export class DataTableComponent {
  orders: OrderItem[] = [
    {
      id: 1041,
      customer: 'Alice Johnson',
      amount: '$125.00',
      status: 'Completed',
    },
    {
      id: 1040,
      customer: 'Bob Smith',
      amount: '$89.50',
      status: 'Shipped',
    },
    {
      id: 1039,
      customer: 'Carol Davis',
      amount: '$245.00',
      status: 'Pending',
    },
    {
      id: 1038,
      customer: 'Dan Wilson',
      amount: '$67.25',
      status: 'Completed',
    },
    {
      id: 1037,
      customer: 'Eve Martinez',
      amount: '$312.00',
      status: 'Cancelled',
    },
  ];
}

// templates/styling/tailwind/overlays/dashboard/vue/src/components/DataTable.vue
<script setup lang="ts">
const orders = [
  { id: '#3210', customer: 'Sarah Johnson', amount: '$245.00', status: 'Completed', badge: 'bg-emerald-100 text-emerald-800' },
  { id: '#3209', customer: 'Mike Peters', amount: '$129.50', status: 'Processing', badge: 'bg-amber-100 text-amber-800' },
  { id: '#3208', customer: 'Emily Chen', amount: '$89.99', status: 'Completed', badge: 'bg-emerald-100 text-emerald-800' },
  { id: '#3207', customer: 'James Wilson', amount: '$312.00', status: 'Cancelled', badge: 'bg-red-100 text-red-800' },
  { id: '#3206', customer: 'Anna Lee', amount: '$175.25', status: 'Shipped', badge: 'bg-blue-100 text-blue-800' },
  { id: '#3205', customer: 'Tom Davis', amount: '$98.00', status: 'Completed', badge: 'bg-emerald-100 text-emerald-800' },
];
</script>

<template>
  <div class="bg-white border border-gray-200 rounded-xl overflow-hidden mb-8">
    <div class="px-6 py-4 border-b border-gray-200 font-semibold text-gray-900">Recent Orders</div>
    <table class="w-full border-collapse">
      <thead>
        <tr>
          <th class="text-left px-6 py-3 text-xs font-semibold text-gray-500 uppercase border-b border-gray-200 bg-gray-50">Order ID</th>
          <th class="text-left px-6 py-3 text-xs font-semibold text-gray-500 uppercase border-b border-gray-200 bg-gray-50">Customer</th>
          <th class="text-left px-6 py-3 text-xs font-semibold text-gray-500 uppercase border-b border-gray-200 bg-gray-50">Amount</th>
          <th class="text-left px-6 py-3 text-xs font-semibold text-gray-500 uppercase border-b border-gray-200 bg-gray-50">Status</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="order in orders" :key="order.id" class="hover:bg-gray-50">
          <td class="px-6 py-3 border-b border-gray-100 text-sm">{{ order.id }}</td>
          <td class="px-6 py-3 border-b border-gray-100 text-sm">{{ order.customer }}</td>
          <td class="px-6 py-3 border-b border-gray-100 text-sm">{{ order.amount }}</td>
          <td class="px-6 py-3 border-b border-gray-100 text-sm"><span :class="['inline-block px-3 py-0.5 rounded-full text-xs font-semibold', order.badge]">{{ order.status }}</span></td>
        </tr>
      </tbody>
    </table>
  </div>
</template>
