// templates/overlays/blog/angular/src/app/components/post-card.component.ts
import { Component, Input } from '@angular/core';
import { RouterLink } from '@angular/router';

export interface BlogPost {
  id: number;
  title: string;
  excerpt: string;
  content: string;
  category: string;
  author: string;
  date: string;
  readTime: string;
  image: string;
}

@Component({
  selector: 'app-post-card',
  standalone: true,
  imports: [RouterLink],
  template: `
    <a [routerLink]="'/post/' + post.id" class="post-card">
      <div class="post-card__image">{{ post.image }}</div>
      <div class="post-card__body">
        <span class="post-card__category">{{ post.category }}</span>
        <h3 class="post-card__title">{{ post.title }}</h3>
        <p class="post-card__excerpt">{{ post.excerpt }}</p>
        <div class="post-card__meta">
          <span>{{ post.author }}</span>
          <span>{{ post.date }}</span>
          <span>{{ post.readTime }}</span>
        </div>
      </div>
    </a>
  `,
  styles: [`
    .post-card {
      display: block;
      background: #fff;
      border-radius: 12px;
      overflow: hidden;
      text-decoration: none;
      box-shadow: 0 1px 3px rgba(0, 0, 0, 0.08);
      transition: transform 0.2s, box-shadow 0.2s;
    }

    .post-card:hover {
      transform: translateY(-2px);
      box-shadow: 0 4px 12px rgba(0, 0, 0, 0.12);
    }

    .post-card__image {
      font-size: 48px;
      text-align: center;
      padding: 24px;
      background: #f3f4f6;
    }

    .post-card__body {
      padding: 20px;
    }

    .post-card__category {
      font-size: 12px;
      font-weight: 600;
      color: #4f46e5;
      text-transform: uppercase;
      letter-spacing: 0.05em;
    }

    .post-card__title {
      font-size: 18px;
      font-weight: 700;
      color: #111827;
      margin: 8px 0;
    }

    .post-card__excerpt {
      font-size: 14px;
      color: #6b7280;
      line-height: 1.5;
      margin-bottom: 12px;
    }

    .post-card__meta {
      display: flex;
      gap: 12px;
      font-size: 12px;
      color: #9ca3af;
    }
  `]
})
export class PostCardComponent {
  @Input() post!: BlogPost;
}

// templates/styling/css-modules/overlays/blog/vue/src/components/PostCard.vue
<script setup lang="ts">
import type { Post } from '../data'

defineProps<{ post: Post }>()
</script>

<template>
  <RouterLink :to="`/post/${post.id}`" :class="$style.postCard" style="text-decoration: none; color: inherit;">
    <div :class="$style.postImage">{{ post.image }}</div>
    <div :class="$style.postBody">
      <div :class="$style.postCategory">{{ post.category }}</div>
      <div :class="$style.postTitle">{{ post.title }}</div>
      <div :class="$style.postExcerpt">{{ post.excerpt }}</div>
      <div :class="$style.postMeta">{{ post.author }} &middot; {{ post.date }} &middot; {{ post.readTime }}</div>
    </div>
  </RouterLink>
</template>

<style module>
.postCard {
  background: #fff;
  border-radius: 8px;
  overflow: hidden;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.08);
  display: flex;
  transition: box-shadow 0.2s;
}

.postCard:hover {
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.12);
}

.postImage {
  width: 180px;
  min-height: 140px;
  background: #eef2ff;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 3rem;
  flex-shrink: 0;
}

.postBody {
  padding: 1.25rem;
  flex: 1;
}

.postCategory {
  font-size: 0.75rem;
  font-weight: 600;
  color: #4f46e5;
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

.postTitle {
  font-size: 1.15rem;
  font-weight: 700;
  color: #111827;
  margin: 0.3rem 0 0.4rem;
}

.postExcerpt {
  font-size: 0.9rem;
  color: #6b7280;
  line-height: 1.5;
}

.postMeta {
  margin-top: 0.75rem;
  font-size: 0.8rem;
  color: #9ca3af;
}
</style>
