// templates/styling/tailwind/overlays/ecommerce/vue/src/pages/Home.vue
<script setup lang="ts">
import { ref, computed, inject } from 'vue';
import type { Product } from '../data';
import { products } from '../data';
import ProductCard from '../components/ProductCard.vue';

const addToCart = inject<(p: Product) => void>('addToCart')!;
const search = ref('');
const filtered = computed(() =>
  products.filter(p => p.name.toLowerCase().includes(search.value.toLowerCase()))
);
</script>

<template>
  <main class="flex-1 max-w-6xl mx-auto px-8 py-8 w-full">
    <h2 class="text-2xl font-bold text-gray-900 mb-6">All Products</h2>
    <input v-model="search" type="text" class="py-3 px-4 border border-gray-300 rounded-lg w-full max-w-md mb-6 text-sm focus:outline-none focus:border-indigo-600 focus:ring-2 focus:ring-indigo-600/10" placeholder="Search products..." />
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
      <ProductCard
        v-for="p in filtered"
        :key="p.id"
        :product="p"
        @add-to-cart="addToCart"
      />
    </div>
  </main>
</template>

// templates/styling/tailwind/overlays/ecommerce/react/src/pages/Home.tsx
import { useState } from 'react';
import { ProductCard } from '../components/ProductCard';
import { products, Product } from '../data/products';

interface HomeProps {
  addToCart: (product: Product) => void;
}

export function Home({ addToCart }: HomeProps) {
  const [search, setSearch] = useState('');

  const filtered = products.filter((p) =>
    p.name.toLowerCase().includes(search.toLowerCase()) ||
    p.category.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <section>
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-6 gap-4">
        <h2 className="text-3xl font-bold text-gray-900 m-0">All Products</h2>
        <input
          type="text"
          className="px-4 py-2 border border-gray-300 rounded-lg text-sm w-full sm:w-56 outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500"
          placeholder="Search products..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />
      </div>
      <div className="grid grid-cols-[repeat(auto-fill,minmax(260px,1fr))] gap-6">
        {filtered.map((product) => (
          <ProductCard key={product.id} product={product} onAddToCart={addToCart} />
        ))}
        {filtered.length === 0 && (
          <p className="text-gray-500 text-center col-span-full py-8">No products found.</p>
        )}
      </div>
    </section>
  );
}
