// templates/overlays/dashboard/vue/src/components/DataTable.vue
<script setup lang="ts">
const orders = [
  { id: '#3210', customer: 'Sarah Johnson', amount: '$245.00', status: 'Completed', badge: 'badge-success' },
  { id: '#3209', customer: 'Mike Peters', amount: '$129.50', status: 'Processing', badge: 'badge-warning' },
  { id: '#3208', customer: 'Emily Chen', amount: '$89.99', status: 'Completed', badge: 'badge-success' },
  { id: '#3207', customer: 'James Wilson', amount: '$312.00', status: 'Cancelled', badge: 'badge-danger' },
  { id: '#3206', customer: 'Anna Lee', amount: '$175.25', status: 'Shipped', badge: 'badge-info' },
  { id: '#3205', customer: 'Tom Davis', amount: '$98.00', status: 'Completed', badge: 'badge-success' },
];
</script>

<template>
  <div class="data-table-wrapper">
    <div class="table-header">Recent Orders</div>
    <table class="data-table">
      <thead>
        <tr>
          <th>Order ID</th>
          <th>Customer</th>
          <th>Amount</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="order in orders" :key="order.id">
          <td>{{ order.id }}</td>
          <td>{{ order.customer }}</td>
          <td>{{ order.amount }}</td>
          <td><span :class="['badge', order.badge]">{{ order.status }}</span></td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

// templates/overlays/dashboard/react/src/components/DataTable.tsx
const rows = [
  { id: '#3210', customer: 'Olivia Martin', email: 'olivia@email.com', amount: '$42.00', status: 'Completed' },
  { id: '#3209', customer: 'Ava Johnson', email: 'ava@email.com', amount: '$74.99', status: 'Processing' },
  { id: '#3208', customer: 'Michael Brown', email: 'michael@email.com', amount: '$64.00', status: 'Completed' },
  { id: '#3207', customer: 'Lisa Anderson', email: 'lisa@email.com', amount: '$49.99', status: 'Cancelled' },
  { id: '#3206', customer: 'Thomas Wilson', email: 'thomas@email.com', amount: '$120.00', status: 'Completed' },
];

export function DataTable() {
  return (
    <div className="table-card">
      <div className="table-header">
        <h3>Recent Orders</h3>
        <button className="table-btn">View All</button>
      </div>
      <table className="data-table">
        <thead>
          <tr>
            <th>Order</th>
            <th>Customer</th>
            <th>Email</th>
            <th>Amount</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((row, i) => (
            <tr key={i}>
              <td>{row.id}</td>
              <td>{row.customer}</td>
              <td>{row.email}</td>
              <td>{row.amount}</td>
              <td>
                <span className={`status-badge status-${row.status.toLowerCase()}`}>
                  {row.status}
                </span>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
