// templates/styling/styled-components/overlays/portfolio/nextjs/src/app/contact/page.tsx
'use client';

import { useState } from 'react';
import styled from 'styled-components';

const ContactPageWrapper = styled.div`
  max-width: 1000px;
  margin: 0 auto;
  padding: 2rem 1.5rem;
`;

const ContactHeader = styled.div`
  text-align: center;
  margin-bottom: 2.5rem;

  h1 {
    font-size: 2rem;
    font-weight: 800;
    color: #111827;
  }

  p {
    color: #6b7280;
    margin-top: 0.5rem;
  }
`;

const ContactGrid = styled.div`
  display: grid;
  grid-template-columns: 1.2fr 1fr;
  gap: 2rem;
  align-items: start;

  @media (max-width: 768px) {
    grid-template-columns: 1fr;
  }
`;

const ContactFormCard = styled.div`
  background: white;
  padding: 2rem;
  border-radius: 12px;
  box-shadow: 0 1px 3px rgba(0,0,0,0.08);
`;

const FormGroup = styled.div`
  margin-bottom: 1.25rem;

  label {
    display: block;
    font-size: 0.85rem;
    font-weight: 600;
    color: #374151;
    margin-bottom: 0.35rem;
  }

  input, select, textarea {
    width: 100%;
    padding: 0.75rem 1rem;
    border: 1px solid #e5e7eb;
    border-radius: 8px;
    font-size: 0.95rem;
    color: #374151;
    background: white;
    font-family: inherit;

    &:focus {
      outline: none;
      border-color: #4f46e5;
      box-shadow: 0 0 0 3px rgba(79,70,229,0.1);
    }
  }

  textarea {
    resize: vertical;
  }
`;

const SubmitButton = styled.button`
  display: block;
  width: 100%;
  padding: 0.875rem 2rem;
  border-radius: 8px;
  font-weight: 600;
  font-size: 1.05rem;
  background: #4f46e5;
  color: white;
  border: none;
  cursor: pointer;
  text-align: center;
  transition: background 0.2s;

  &:hover {
    background: #4338ca;
  }
`;

const SuccessMessage = styled.div`
  text-align: center;
  padding: 2rem;

  h3 {
    font-size: 1.25rem;
    color: #111827;
    margin-bottom: 0.5rem;
  }

  p {
    color: #6b7280;
    margin-bottom: 1.5rem;
  }
`;

const SuccessIcon = styled.span`
  font-size: 3rem;
  display: block;
  margin-bottom: 1rem;
`;

const SendAnotherButton = styled.button`
  display: inline-block;
  padding: 0.75rem 1.75rem;
  border-radius: 8px;
  font-weight: 600;
  font-size: 0.95rem;
  background: #4f46e5;
  color: white;
  border: none;
  cursor: pointer;
  transition: background 0.2s;

  &:hover {
    background: #4338ca;
  }
`;

const ContactInfoSection = styled.div`
  display: flex;
  flex-direction: column;
  gap: 1.25rem;
`;

const ContactInfoCard = styled.div`
  background: white;
  padding: 1.5rem;
  border-radius: 12px;
  box-shadow: 0 1px 3px rgba(0,0,0,0.08);

  h3 {
    font-size: 1.1rem;
    font-weight: 700;
    color: #111827;
    margin-bottom: 1rem;
  }
`;

const InfoItem = styled.div`
  display: flex;
  gap: 0.75rem;
  margin-bottom: 1rem;

  &:last-child {
    margin-bottom: 0;
  }
`;

const InfoIcon = styled.span`
  font-size: 1.5rem;
  flex-shrink: 0;
`;

const InfoLabel = styled.p`
  font-size: 0.8rem;
  color: #6b7280;
`;

const InfoValue = styled.p`
  font-weight: 600;
  color: #111827;
`;

const SocialGrid = styled.div`
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 0.75rem;
`;

const SocialCard = styled.a`
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.75rem;
  background: #f9fafb;
  border-radius: 8px;
  font-weight: 500;
  color: #374151;
  transition: all 0.2s;
  text-decoration: none;

  &:hover {
    background: #eef2ff;
    color: #4f46e5;
  }
`;

export default function ContactPage() {
  const [formData, setFormData] = useState({ name: '', email: '', subject: '', message: '' });
  const [submitted, setSubmitted] = useState(false);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitted(true);
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  return (
    <ContactPageWrapper>
      <ContactHeader>
        <h1>Get in Touch</h1>
        <p>Have a project in mind or just want to say hello? I would love to hear from you.</p>
      </ContactHeader>

      <ContactGrid>
        <ContactFormCard>
          {submitted ? (
            <SuccessMessage>
              <SuccessIcon>✅</SuccessIcon>
              <h3>Message Sent!</h3>
              <p>Thank you for reaching out. I will get back to you as soon as possible.</p>
              <SendAnotherButton onClick={() => setSubmitted(false)}>Send Another</SendAnotherButton>
            </SuccessMessage>
          ) : (
            <form onSubmit={handleSubmit}>
              <FormGroup>
                <label htmlFor="name">Name</label>
                <input
                  type="text"
                  id="name"
                  name="name"
                  value={formData.name}
                  onChange={handleChange}
                  placeholder="Your name"
                  required
                />
              </FormGroup>
              <FormGroup>
                <label htmlFor="email">Email</label>
                <input
                  type="email"
                  id="email"
                  name="email"
                  value={formData.email}
                  onChange={handleChange}
                  placeholder="your@email.com"
                  required
                />
              </FormGroup>
              <FormGroup>
                <label htmlFor="subject">Subject</label>
                <select id="subject" name="subject" value={formData.subject} onChange={handleChange} required>
                  <option value="">Select a subject</option>
                  <option value="project">Project Inquiry</option>
                  <option value="collaboration">Collaboration</option>
                  <option value="freelance">Freelance Work</option>
                  <option value="other">Other</option>
                </select>
              </FormGroup>
              <FormGroup>
                <label htmlFor="message">Message</label>
                <textarea
                  id="message"
                  name="message"
                  value={formData.message}
                  onChange={handleChange}
                  placeholder="Tell me about your project..."
                  rows={5}
                  required
                />
              </FormGroup>
              <SubmitButton type="submit">Send Message</SubmitButton>
            </form>
          )}
        </ContactFormCard>

        <ContactInfoSection>
          <ContactInfoCard>
            <h3>Contact Information</h3>
            <InfoItem>
              <InfoIcon>📧</InfoIcon>
              <div>
                <InfoLabel>Email</InfoLabel>
                <InfoValue>hello@{'{{projectName}}'}.com</InfoValue>
              </div>
            </InfoItem>
            <InfoItem>
              <InfoIcon>📍</InfoIcon>
              <div>
                <InfoLabel>Location</InfoLabel>
                <InfoValue>San Francisco, CA</InfoValue>
              </div>
            </InfoItem>
            <InfoItem>
              <InfoIcon>🕐</InfoIcon>
              <div>
                <InfoLabel>Availability</InfoLabel>
                <InfoValue>Open for freelance projects</InfoValue>
              </div>
            </InfoItem>
          </ContactInfoCard>

          <ContactInfoCard>
            <h3>Social Links</h3>
            <SocialGrid>
              <SocialCard href="#">
                <span>💼</span>
                <span>LinkedIn</span>
              </SocialCard>
              <SocialCard href="#">
                <span>📂</span>
                <span>GitHub</span>
              </SocialCard>
              <SocialCard href="#">
                <span>🐦</span>
                <span>Twitter</span>
              </SocialCard>
              <SocialCard href="#">
                <span>📸</span>
                <span>Dribbble</span>
              </SocialCard>
            </SocialGrid>
          </ContactInfoCard>
        </ContactInfoSection>
      </ContactGrid>
    </ContactPageWrapper>
  );
}

// templates/styling/css-modules/overlays/portfolio/nuxt/pages/contact.vue
<script setup lang="ts">
const form = reactive({
  name: '',
  email: '',
  subject: '',
  message: '',
});

const submitted = ref(false);

function handleSubmit() {
  submitted.value = true;
  setTimeout(() => {
    form.name = '';
    form.email = '';
    form.subject = '';
    form.message = '';
    submitted.value = false;
  }, 3000);
}

const contactInfo = [
  { icon: '📧', label: 'Email', value: 'hello@example.com' },
  { icon: '📍', label: 'Location', value: 'San Francisco, CA' },
  { icon: '🔗', label: 'GitHub', value: 'github.com/developer' },
  { icon: '💼', label: 'LinkedIn', value: 'linkedin.com/in/developer' },
];
</script>

<template>
  <div :class="$style.contactPage">
    <div :class="$style.pageInner">
      <div :class="$style.pageHeader">
        <h1>Get in Touch</h1>
        <p :class="$style.subtitle">Have a project in mind? Let's talk about it.</p>
      </div>

      <div :class="$style.contactLayout">
        <form :class="$style.contactForm" @submit.prevent="handleSubmit">
          <div v-if="submitted" :class="$style.successMessage">
            <span :class="$style.successIcon">✅</span>
            <p>Thank you! Your message has been sent successfully.</p>
          </div>

          <template v-else>
            <div :class="$style.formRow">
              <div :class="$style.formGroup">
                <label for="name">Name</label>
                <input
                  id="name"
                  v-model="form.name"
                  type="text"
                  placeholder="Your name"
                  :class="$style.formInput"
                  required
                />
              </div>
              <div :class="$style.formGroup">
                <label for="email">Email</label>
                <input
                  id="email"
                  v-model="form.email"
                  type="email"
                  placeholder="your@email.com"
                  :class="$style.formInput"
                  required
                />
              </div>
            </div>

            <div :class="$style.formGroup">
              <label for="subject">Subject</label>
              <input
                id="subject"
                v-model="form.subject"
                type="text"
                placeholder="Project inquiry"
                :class="$style.formInput"
                required
              />
            </div>

            <div :class="$style.formGroup">
              <label for="message">Message</label>
              <textarea
                id="message"
                v-model="form.message"
                rows="6"
                placeholder="Tell me about your project..."
                :class="$style.formInput"
                required
              ></textarea>
            </div>

            <button type="submit" :class="$style.submitBtn">Send Message</button>
          </template>
        </form>

        <div :class="$style.contactInfo">
          <h2>Contact Info</h2>
          <div :class="$style.infoList">
            <div v-for="info in contactInfo" :key="info.label" :class="$style.infoItem">
              <span :class="$style.infoIcon">{{ info.icon }}</span>
              <div>
                <p :class="$style.infoLabel">{{ info.label }}</p>
                <p :class="$style.infoValue">{{ info.value }}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style module>
.contactPage {
  padding: 2rem 1.5rem 4rem;
}

.pageInner {
  max-width: 1000px;
  margin: 0 auto;
}

.pageHeader {
  text-align: center;
  margin-bottom: 2.5rem;
}

.pageHeader h1 {
  font-size: 2rem;
  color: #111827;
  margin-bottom: 0.5rem;
}

.subtitle {
  color: #6b7280;
  font-size: 1.1rem;
}

.contactLayout {
  display: grid;
  grid-template-columns: 1fr 320px;
  gap: 2.5rem;
  align-items: start;
}

.contactForm {
  background: white;
  border-radius: 12px;
  padding: 2rem;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
}

.successMessage {
  text-align: center;
  padding: 2rem;
}

.successIcon {
  font-size: 3rem;
  display: block;
  margin-bottom: 1rem;
}

.successMessage p {
  font-size: 1.1rem;
  color: #065f46;
  font-weight: 500;
}

.formRow {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 1rem;
}

.formGroup {
  margin-bottom: 1.25rem;
}

.formGroup label {
  display: block;
  font-size: 0.875rem;
  font-weight: 600;
  color: #374151;
  margin-bottom: 0.35rem;
}

.formInput {
  width: 100%;
  padding: 0.75rem 1rem;
  border: 1px solid #d1d5db;
  border-radius: 8px;
  font-size: 0.95rem;
  font-family: inherit;
  outline: none;
  transition: border-color 0.2s;
  resize: vertical;
}

.formInput:focus {
  border-color: #4f46e5;
  box-shadow: 0 0 0 3px rgba(79, 70, 229, 0.1);
}

.submitBtn {
  background: #4f46e5;
  color: white;
  border: none;
  padding: 0.875rem 2rem;
  border-radius: 8px;
  font-size: 1rem;
  font-weight: 600;
  cursor: pointer;
  width: 100%;
  transition: background 0.2s;
}

.submitBtn:hover {
  background: #4338ca;
}

.contactInfo {
  background: white;
  border-radius: 12px;
  padding: 2rem;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
}

.contactInfo h2 {
  font-size: 1.25rem;
  color: #111827;
  margin-bottom: 1.5rem;
  padding-bottom: 0.75rem;
  border-bottom: 2px solid #e5e7eb;
}

.infoList {
  display: flex;
  flex-direction: column;
  gap: 1.25rem;
}

.infoItem {
  display: flex;
  align-items: center;
  gap: 1rem;
}

.infoIcon {
  font-size: 1.5rem;
  flex-shrink: 0;
}

.infoLabel {
  font-size: 0.8rem;
  color: #6b7280;
  font-weight: 500;
}

.infoValue {
  font-size: 0.95rem;
  color: #111827;
  font-weight: 600;
}

@media (max-width: 768px) {
  .contactLayout {
    grid-template-columns: 1fr;
  }

  .formRow {
    grid-template-columns: 1fr;
  }
}
</style>
