// templates/styling/css-modules/overlays/portfolio/react/src/components/SkillsGrid.tsx
import { skills } from '../data/projects';
import styles from './SkillsGrid.module.css';

function SkillsGrid() {
  return (
    <div className={styles.skillsGrid}>
      {skills.map((group, i) => (
        <div key={i} className={styles.skillGroup}>
          <h3>{group.category}</h3>
          <div className={styles.skillTags}>
            {group.items.map((skill, j) => (
              <span key={j} className={styles.skillTag}>{skill}</span>
            ))}
          </div>
        </div>
      ))}
    </div>
  );
}

export default SkillsGrid;

// templates/overlays/portfolio/vue/src/components/SkillsGrid.vue
<script setup lang="ts">
import { skills } from '../data'
</script>

<template>
  <div class="skills-section">
    <div v-for="group in skills" :key="group.category" class="skill-group">
      <h3>{{ group.category }}</h3>
      <div class="skill-items">
        <span v-for="item in group.items" :key="item">{{ item }}</span>
      </div>
    </div>
  </div>
</template>
