// templates/overlays/crm/react/src/components/ContactsTable.tsx
import type { Contact } from '../data/contacts';

interface ContactsTableProps {
  contacts: Contact[];
}

function ContactsTable({ contacts }: ContactsTableProps) {
  return (
    <div className="table-card">
      <table className="data-table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Company</th>
            <th>Status</th>
            <th>Phone</th>
          </tr>
        </thead>
        <tbody>
          {contacts.map((c) => (
            <tr key={c.id}>
              <td className="contact-name">{c.name}</td>
              <td className="contact-email">{c.email}</td>
              <td>{c.company}</td>
              <td>
                <span className={`status-badge status-${c.status.toLowerCase()}`}>
                  {c.status}
                </span>
              </td>
              <td className="contact-phone">{c.phone}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export default ContactsTable;

// templates/overlays/crm/vue/src/components/ContactsTable.vue
<script setup lang="ts">
import type { Contact } from '../data'

defineProps<{ contacts: Contact[] }>()
</script>

<template>
  <div class="table-container">
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Company</th>
          <th>Phone</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="contact in contacts" :key="contact.id">
          <td>{{ contact.name }}</td>
          <td>{{ contact.email }}</td>
          <td>{{ contact.company }}</td>
          <td>{{ contact.phone }}</td>
          <td><span class="status-badge" :class="contact.status">{{ contact.status }}</span></td>
        </tr>
      </tbody>
    </table>
  </div>
</template>
