// templates/styling/ant-design/overlays/crm/react/src/components/StatsCards.tsx
import { Card, Statistic, Row, Col } from 'antd';
import { contacts } from '../data/contacts';

const stats = [
  { label: 'Total Contacts', value: contacts.length, color: '#4f46e5' },
  { label: 'Leads', value: contacts.filter((c) => c.status === 'Lead').length, color: '#f59e0b' },
  { label: 'Customers', value: contacts.filter((c) => c.status === 'Customer').length, color: '#10b981' },
  { label: 'Churned', value: contacts.filter((c) => c.status === 'Churned').length, color: '#ef4444' },
];

function StatsCards() {
  return (
    <Row gutter={[16, 16]} style={{ marginBottom: 24 }}>
      {stats.map((stat, i) => (
        <Col xs={24} sm={12} lg={6} key={i}>
          <Card>
            <Statistic
              title={stat.label}
              value={stat.value}
              valueStyle={{ color: stat.color }}
            />
          </Card>
        </Col>
      ))}
    </Row>
  );
}

export default StatsCards;

// templates/overlays/crm/vue/src/components/StatsCards.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { Contact } from '../data'

const props = defineProps<{ contacts: Contact[] }>()

const stats = computed(() => [
  { icon: '👥', label: 'Total', value: props.contacts.length },
  { icon: '🔵', label: 'Leads', value: props.contacts.filter(c => c.status === 'Lead').length },
  { icon: '🟢', label: 'Customers', value: props.contacts.filter(c => c.status === 'Customer').length },
  { icon: '🔴', label: 'Churned', value: props.contacts.filter(c => c.status === 'Churned').length },
])
</script>

<template>
  <div class="stats-grid">
    <div v-for="stat in stats" :key="stat.label" class="stat-card">
      <div class="stat-icon">{{ stat.icon }}</div>
      <div class="stat-label">{{ stat.label }}</div>
      <div class="stat-value">{{ stat.value }}</div>
    </div>
  </div>
</template>
