// templates/styling/css-modules/overlays/blog/vue/src/pages/Home.vue
<script setup lang="ts">
import PostCard from '../components/PostCard.vue'
import BlogSidebar from '../components/BlogSidebar.vue'
import { posts } from '../data'
</script>

<template>
  <div :class="$style.blogLayout">
    <div :class="$style.postsGrid">
      <PostCard v-for="post in posts" :key="post.id" :post="post" />
    </div>
    <BlogSidebar />
  </div>
</template>

<style module>
.blogLayout {
  display: grid;
  grid-template-columns: 1fr 300px;
  gap: 2rem;
}

.postsGrid {
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
}
</style>

// templates/styling/ant-design/overlays/blog/react/src/pages/Home.tsx
import PostCard from '../components/PostCard';
import BlogSidebar from '../components/BlogSidebar';
import { posts } from '../data/posts';

function Home() {
  return (
    <div style={{ display: 'flex', gap: 32, flexWrap: 'wrap' }}>
      <div style={{ flex: 1, minWidth: 0 }}>
        {posts.map((post) => (
          <PostCard key={post.id} post={post} />
        ))}
      </div>
      <BlogSidebar />
    </div>
  );
}

export default Home;
