// templates/styling/tailwind/overlays/crm/nuxt/pages/deals.vue
<script setup lang="ts">
interface Deal {
  id: number;
  title: string;
  company: string;
  value: string;
  contact: string;
}

interface Column {
  id: string;
  title: string;
  color: string;
  deals: Deal[];
}

const columns: Column[] = [
  {
    id: 'lead',
    title: 'Lead',
    color: '#6b7280',
    deals: [
      { id: 1, title: 'Website Redesign', company: 'Acme Inc', value: '$12,000', contact: 'John Doe' },
      { id: 2, title: 'Mobile App', company: 'StartupXYZ', value: '$25,000', contact: 'Mike Johnson' },
    ],
  },
  {
    id: 'qualified',
    title: 'Qualified',
    color: '#3b82f6',
    deals: [
      { id: 3, title: 'Cloud Migration', company: 'BigCo', value: '$45,000', contact: 'Emily Davis' },
      { id: 4, title: 'SEO Campaign', company: 'Tech Labs', value: '$8,500', contact: 'Jane Smith' },
    ],
  },
  {
    id: 'proposal',
    title: 'Proposal',
    color: '#f59e0b',
    deals: [
      { id: 5, title: 'ERP Integration', company: 'Skynet Corp', value: '$68,000', contact: 'Sarah Connor' },
    ],
  },
  {
    id: 'closed',
    title: 'Closed Won',
    color: '#10b981',
    deals: [
      { id: 6, title: 'Brand Identity', company: 'DevStudio', value: '$15,000', contact: 'Chris Wilson' },
      { id: 7, title: 'Data Analytics', company: 'Acme Inc', value: '$32,000', contact: 'John Doe' },
    ],
  },
];
</script>

<template>
  <div>
    <div class="flex justify-between items-start mb-8">
      <div>
        <h1 class="text-2xl font-bold text-gray-900 mb-1">Deals Pipeline</h1>
        <p class="text-gray-500">Track and manage your sales pipeline.</p>
      </div>
      <button class="bg-indigo-600 text-white border-none px-5 py-2.5 rounded-lg font-semibold cursor-pointer hover:bg-indigo-700 transition-colors">+ New Deal</button>
    </div>

    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 overflow-x-auto">
      <div v-for="col in columns" :key="col.id" class="bg-gray-50 rounded-lg p-4 min-w-[240px]">
        <div class="flex items-center gap-2 mb-4 pb-3 border-b-2 border-gray-200">
          <span class="w-2.5 h-2.5 rounded-full" :style="{ backgroundColor: col.color }"></span>
          <h3 class="text-sm font-semibold text-gray-900 flex-1">{{ col.title }}</h3>
          <span class="bg-gray-200 text-gray-600 text-xs font-bold w-5.5 h-5.5 rounded-full flex items-center justify-center">{{ col.deals.length }}</span>
        </div>

        <div class="flex flex-col gap-3">
          <div v-for="deal in col.deals" :key="deal.id" class="bg-white rounded-lg p-4 shadow-sm cursor-pointer hover:shadow-md transition-shadow">
            <h4 class="text-sm font-semibold text-gray-900 mb-1">{{ deal.title }}</h4>
            <p class="text-xs text-gray-500 mb-3">{{ deal.company }}</p>
            <div class="flex justify-between items-center">
              <span class="text-sm font-bold text-indigo-600">{{ deal.value }}</span>
              <span class="text-xs text-gray-400">{{ deal.contact }}</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

// templates/styling/tailwind/overlays/crm/angular/src/app/pages/deals.component.ts
import { Component } from '@angular/core';

interface Deal {
  name: string;
  company: string;
  value: string;
}

interface PipelineColumn {
  name: string;
  deals: Deal[];
}

@Component({
  selector: 'app-deals',
  standalone: true,
  template: `
    <h1 class="text-2xl font-bold text-gray-900 mb-6">Deals Pipeline</h1>
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
      @for (col of columns; track col.name) {
        <div class="bg-gray-100 rounded-xl p-4 min-h-[400px]">
          <div class="flex justify-between items-center mb-3">
            <span class="text-sm font-semibold text-gray-900">{{ col.name }}</span>
            <span class="bg-gray-200 px-2 py-0.5 rounded-full text-xs text-gray-500">{{ col.deals.length }}</span>
          </div>
          @for (deal of col.deals; track deal.name) {
            <div class="bg-white rounded-lg p-3.5 mb-2 shadow-sm">
              <div class="font-semibold text-gray-900 text-sm mb-1">{{ deal.name }}</div>
              <div class="text-gray-500 text-sm mb-2">{{ deal.company }}</div>
              <div class="text-indigo-600 font-bold text-sm">{{ deal.value }}</div>
            </div>
          }
        </div>
      }
    </div>
  `,
  styles: []
})
export class DealsComponent {
  columns: PipelineColumn[] = [
    {
      name: 'Prospect',
      deals: [
        { name: 'Website Redesign', company: 'Acme Corp', value: '$12,000' },
        { name: 'Mobile App', company: 'Globex Inc', value: '$28,000' },
      ],
    },
    {
      name: 'Qualified',
      deals: [
        { name: 'CRM Integration', company: 'Initech', value: '$18,500' },
      ],
    },
    {
      name: 'Proposal',
      deals: [
        { name: 'Cloud Migration', company: 'Umbrella Co', value: '$45,000' },
        { name: 'API Development', company: 'Stark Industries', value: '$22,000' },
      ],
    },
    {
      name: 'Won',
      deals: [
        { name: 'SEO Campaign', company: 'Wayne Enterprises', value: '$8,500' },
      ],
    },
  ];
}
