// templates/styling/ant-design/overlays/landing/nextjs/src/app/components/CTA.tsx
'use client';

import { Button, Typography } from 'antd';

const { Title, Text } = Typography;

export function CTA() {
  return (
    <section id="cta" style={{ background: '#f9fafb', padding: '80px 32px', textAlign: 'center' }}>
      <div style={{ maxWidth: 600, margin: '0 auto' }}>
        <Title level={2} style={{ fontSize: 40, marginBottom: 16 }}>Ready to Get Started?</Title>
        <Text type="secondary" style={{ fontSize: 18, display: 'block', marginBottom: 32 }}>
          Join thousands of developers who are building amazing products.
        </Text>
        <Button type="primary" size="large" style={{ height: 52, paddingInline: 40, fontSize: 18, fontWeight: 600 }}>
          Start Free Trial
        </Button>
        <Text type="secondary" style={{ display: 'block', marginTop: 12, fontSize: 14 }}>No credit card required</Text>
      </div>
    </section>
  );
}

// templates/styling/ant-design/overlays/landing/vue/src/components/CTA.vue
<script setup lang="ts">
</script>

<template>
  <section id="cta" :style="{ background: '#f9fafb', padding: '80px 32px', textAlign: 'center' }">
    <div :style="{ maxWidth: '600px', margin: '0 auto' }">
      <a-typography-title :level="2">Ready to Get Started?</a-typography-title>
      <a-typography-paragraph type="secondary" :style="{ fontSize: '18px', marginBottom: '32px' }">
        Join thousands of developers building amazing products.
      </a-typography-paragraph>
      <a-button type="primary" size="large" :style="{ height: '48px', paddingInline: '40px', fontSize: '16px' }">Start Free Trial</a-button>
      <a-typography-paragraph type="secondary" :style="{ fontSize: '14px', marginTop: '12px' }">No credit card required</a-typography-paragraph>
    </div>
  </section>
</template>
