// templates/styling/styled-components/overlays/portfolio/react/src/pages/Home.tsx
import { Link } from 'react-router-dom';
import styled from 'styled-components';
import ProjectCard from '../components/ProjectCard';
import SkillsGrid from '../components/SkillsGrid';
import { projects } from '../data/projects';

const HeroSection = styled.section`
  background: linear-gradient(135deg, #0f172a 0%, #1e293b 50%, #334155 100%);
  color: white;
  padding: 5rem 2rem;
`;

const HeroContent = styled.div`
  text-align: center;
  max-width: 700px;
  margin: 0 auto;

  h1 {
    font-size: 4rem;
    font-weight: 800;
    margin: 0.5rem 0;

    @media (max-width: 768px) {
      font-size: 2.5rem;
    }
  }
`;

const HeroGreeting = styled.span`
  font-size: 1.1rem;
  color: #4f46e5;
  font-weight: 600;
`;

const HeroRole = styled.p`
  font-size: 1.25rem;
  color: #94a3b8;
  margin-bottom: 1rem;
`;

const HeroDesc = styled.p`
  color: #cbd5e1;
  line-height: 1.7;
  margin-bottom: 2rem;
`;

const HeroActions = styled.div`
  display: flex;
  gap: 1rem;
  justify-content: center;

  @media (max-width: 768px) {
    flex-direction: column;
    align-items: center;
  }
`;

const Button = styled(Link)<{ $variant?: 'outline' }>`
  padding: 0.75rem 1.5rem;
  border-radius: 8px;
  font-size: 1rem;
  font-weight: 600;
  text-decoration: none;
  cursor: pointer;
  transition: all 0.2s;
  border: 2px solid transparent;
  display: inline-block;

  background: ${props => props.$variant === 'outline' ? 'transparent' : '#4f46e5'};
  color: white;
  border-color: ${props => props.$variant === 'outline' ? '#475569' : '#4f46e5'};

  &:hover {
    background: ${props => props.$variant === 'outline' ? 'transparent' : '#4338ca'};
    border-color: ${props => props.$variant === 'outline' ? 'white' : '#4338ca'};
  }
`;

const ProjectsSection = styled.section`
  max-width: 1100px;
  margin: 0 auto;
  padding: 5rem 2rem;

  h2 {
    text-align: center;
    font-size: 2rem;
    margin-bottom: 0.5rem;
    color: #111827;
  }
`;

const SectionSubtitle = styled.p`
  color: #6b7280;
  text-align: center;
  margin-bottom: 3rem;
`;

const ProjectsGrid = styled.div`
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
  gap: 1.5rem;

  @media (max-width: 768px) {
    grid-template-columns: 1fr;
  }
`;

const SkillsSection = styled.section`
  background: #f9fafb;
  padding: 5rem 2rem;

  h2 {
    text-align: center;
    font-size: 2rem;
    margin-bottom: 0.5rem;
    color: #111827;
  }
`;

function Home() {
  const featured = projects.slice(0, 3);

  return (
    <div>
      <HeroSection>
        <HeroContent>
          <HeroGreeting>Hi, I'm</HeroGreeting>
          <h1>{'{{projectName}}'}</h1>
          <HeroRole>Frontend Developer &amp; Software Engineer</HeroRole>
          <HeroDesc>
            I craft pixel-perfect, user-centric web experiences with modern technologies.
            Passionate about clean code and great design.
          </HeroDesc>
          <HeroActions>
            <Button to="/projects">View My Work</Button>
            <Button to="/contact" $variant="outline">Get In Touch</Button>
          </HeroActions>
        </HeroContent>
      </HeroSection>
      <ProjectsSection>
        <h2>Featured Projects</h2>
        <SectionSubtitle>A selection of my recent work</SectionSubtitle>
        <ProjectsGrid>
          {featured.map((project) => (
            <ProjectCard key={project.id} project={project} />
          ))}
        </ProjectsGrid>
      </ProjectsSection>
      <SkillsSection>
        <h2>Skills &amp; Technologies</h2>
        <SectionSubtitle>Technologies I work with daily</SectionSubtitle>
        <SkillsGrid />
      </SkillsSection>
    </div>
  );
}

export default Home;

// templates/styling/css-modules/overlays/portfolio/vue/src/pages/Home.vue
<script setup lang="ts">
import ProjectCard from '../components/ProjectCard.vue'
import SkillsGrid from '../components/SkillsGrid.vue'
import { projects } from '../data'

const featured = projects.slice(0, 3)
</script>

<template>
  <div>
    <section :class="$style.hero">
      <h1>Hi, I'm <span :class="$style.heroAccent">a Developer</span></h1>
      <p>I build modern web applications with clean code and great user experiences.</p>
      <RouterLink to="/projects" :class="$style.heroCta">View My Work</RouterLink>
    </section>
    <section :class="$style.section">
      <h2 :class="$style.sectionTitle">Featured Projects</h2>
      <div :class="$style.projectsGrid">
        <ProjectCard v-for="project in featured" :key="project.id" :project="project" />
      </div>
    </section>
    <section :class="$style.section">
      <h2 :class="$style.sectionTitle">Skills</h2>
      <SkillsGrid />
    </section>
  </div>
</template>

<style module>
.hero {
  background: #111827;
  color: #fff;
  text-align: center;
  padding: 4rem 1.5rem 3rem;
}

.hero h1 {
  font-size: 2.5rem;
  font-weight: 800;
  margin-bottom: 0.75rem;
}

.heroAccent {
  color: #4f46e5;
}

.hero p {
  font-size: 1.15rem;
  color: #9ca3af;
  max-width: 560px;
  margin: 0 auto 1.5rem;
}

.heroCta {
  display: inline-block;
  background: #4f46e5;
  color: #fff;
  padding: 0.7rem 1.75rem;
  border-radius: 6px;
  font-weight: 600;
  font-size: 0.95rem;
  text-decoration: none;
  transition: background 0.2s;
}

.heroCta:hover {
  background: #4338ca;
}

.section {
  max-width: 1100px;
  margin: 0 auto;
  padding: 3rem 1.5rem;
}

.sectionTitle {
  font-size: 1.5rem;
  font-weight: 700;
  color: #111827;
  margin-bottom: 1.5rem;
  text-align: center;
}

.projectsGrid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(320px, 1fr));
  gap: 1.5rem;
}
</style>
