// templates/styling/tailwind/overlays/blog/vue/src/pages/Category.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useRoute } from 'vue-router'
import PostCard from '../components/PostCard.vue'
import { posts } from '../data'

const route = useRoute()

const slug = computed(() => route.params.slug as string)

const filtered = computed(() =>
  posts.filter(p => p.category.toLowerCase().replace('.', '') === slug.value)
)

const categoryName = computed(() =>
  filtered.value.length ? filtered.value[0].category : slug.value
)
</script>

<template>
  <div>
    <div class="mb-6">
      <h1 class="text-2xl font-bold text-gray-900">{{ categoryName }}</h1>
      <p class="text-gray-500 mb-4">{{ filtered.length }} post(s) in this category</p>
    </div>
    <div class="flex flex-col gap-6">
      <PostCard v-for="post in filtered" :key="post.id" :post="post" />
    </div>
    <p v-if="!filtered.length" class="text-gray-500">No posts found in this category.</p>
    <RouterLink to="/" class="inline-block mt-4 text-indigo-600 no-underline hover:text-indigo-700 transition-colors">&larr; Back to all posts</RouterLink>
  </div>
</template>

// templates/styling/chakra-ui/overlays/blog/react/src/pages/Category.tsx
import { useParams, Link } from 'react-router-dom';
import { Box, Heading, Text, VStack } from '@chakra-ui/react';
import PostCard from '../components/PostCard';
import { posts } from '../data/posts';

function Category() {
  const { slug } = useParams();
  const filtered = posts.filter(
    (p) => p.category.toLowerCase() === slug?.toLowerCase()
  );
  const categoryName = filtered.length > 0 ? filtered[0].category : slug;

  return (
    <Box maxW="720px" mx="auto">
      <Box
        as={Link}
        to="/"
        display="inline-block"
        color="#4f46e5"
        textDecoration="none"
        fontSize="0.9rem"
        mb={6}
        _hover={{ textDecoration: 'underline' }}
      >
        ← Back to Home
      </Box>
      <Heading as="h1" size="xl" fontWeight={700} color="gray.900" mb={6}>
        Category: {categoryName}
      </Heading>
      {filtered.length === 0 ? (
        <Text color="gray.500">No posts found in this category.</Text>
      ) : (
        <VStack gap={0} align="stretch">
          {filtered.map((post) => (
            <PostCard key={post.id} post={post} />
          ))}
        </VStack>
      )}
    </Box>
  );
}

export default Category;
