// templates/styling/tailwind/overlays/landing/angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { HeroComponent } from './components/hero.component';
import { FeaturesComponent } from './components/features.component';
import { CtaComponent } from './components/cta.component';
import { FooterComponent } from './components/footer.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [HeroComponent, FeaturesComponent, CtaComponent, FooterComponent],
  template: `
    <div class="min-h-screen">
      <app-hero />
      <app-features />
      <app-cta />
      <app-footer />
    </div>
  `,
  styles: []
})
export class AppComponent {}

// templates/styling/css-modules/overlays/landing/react/src/App.tsx
import { Hero } from './components/Hero';
import { Features } from './components/Features';
import { CTA } from './components/CTA';
import { Footer } from './components/Footer';

function App() {
  return (
    <>
      <Hero />
      <Features />
      <CTA />
      <Footer />
    </>
  );
}

export default App;
