// templates/styling/tailwind/overlays/portfolio/vue/src/pages/Contact.vue
<script setup lang="ts">
import { ref } from 'vue'

const name = ref('')
const email = ref('')
const subject = ref('')
const message = ref('')
const sent = ref(false)

const submit = () => {
  if (name.value && email.value && message.value) {
    sent.value = true
    name.value = ''
    email.value = ''
    subject.value = ''
    message.value = ''
    setTimeout(() => (sent.value = false), 3000)
  }
}
</script>

<template>
  <div class="max-w-lg mx-auto py-12 px-6">
    <h1 class="text-2xl font-bold text-gray-900 text-center mb-2">Get In Touch</h1>
    <p class="text-center text-gray-500 mb-8">Have a project in mind? Let's work together.</p>
    <div class="bg-white p-6 rounded-lg shadow-sm">
      <div class="mb-5">
        <label class="block text-sm font-semibold text-gray-700 mb-1.5">Name</label>
        <input v-model="name" type="text" placeholder="Your name" class="w-full py-2.5 px-3 border border-gray-300 rounded-md text-sm focus:outline-none focus:border-indigo-600 transition-colors" />
      </div>
      <div class="mb-5">
        <label class="block text-sm font-semibold text-gray-700 mb-1.5">Email</label>
        <input v-model="email" type="email" placeholder="your@email.com" class="w-full py-2.5 px-3 border border-gray-300 rounded-md text-sm focus:outline-none focus:border-indigo-600 transition-colors" />
      </div>
      <div class="mb-5">
        <label class="block text-sm font-semibold text-gray-700 mb-1.5">Subject</label>
        <input v-model="subject" type="text" placeholder="Project inquiry" class="w-full py-2.5 px-3 border border-gray-300 rounded-md text-sm focus:outline-none focus:border-indigo-600 transition-colors" />
      </div>
      <div class="mb-5">
        <label class="block text-sm font-semibold text-gray-700 mb-1.5">Message</label>
        <textarea v-model="message" placeholder="Tell me about your project..." class="w-full py-2.5 px-3 border border-gray-300 rounded-md text-sm focus:outline-none focus:border-indigo-600 transition-colors resize-y min-h-[120px]"></textarea>
      </div>
      <button class="w-full bg-indigo-600 text-white border-none py-3 rounded-md text-sm font-semibold cursor-pointer transition-colors hover:bg-indigo-700" @click="submit">Send Message</button>
      <p v-if="sent" class="text-emerald-600 text-center mt-3 text-sm">Message sent! I'll get back to you soon.</p>
    </div>
  </div>
</template>

// templates/styling/tailwind/overlays/portfolio/angular/src/app/pages/contact.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-contact',
  standalone: true,
  imports: [FormsModule],
  template: `
    <div class="max-w-lg mx-auto px-6 py-12">
      <div class="bg-white rounded-2xl p-8 md:p-9 shadow-sm">
        <h1 class="text-2xl md:text-3xl font-extrabold text-gray-900 mb-2">Get in Touch</h1>
        <p class="text-sm text-gray-500 mb-7">Have a project in mind? Let's work together.</p>
        <div class="flex flex-col gap-1.5 mb-4">
          <label class="text-sm font-medium text-gray-700">Name</label>
          <input [(ngModel)]="name" placeholder="Your name"
            class="px-3.5 py-2.5 border border-gray-300 rounded-lg text-sm outline-none font-sans focus:border-indigo-600 focus:ring-2 focus:ring-indigo-600/10 transition-all" />
        </div>
        <div class="flex flex-col gap-1.5 mb-4">
          <label class="text-sm font-medium text-gray-700">Email</label>
          <input [(ngModel)]="email" type="email" placeholder="Your email"
            class="px-3.5 py-2.5 border border-gray-300 rounded-lg text-sm outline-none font-sans focus:border-indigo-600 focus:ring-2 focus:ring-indigo-600/10 transition-all" />
        </div>
        <div class="flex flex-col gap-1.5 mb-4">
          <label class="text-sm font-medium text-gray-700">Subject</label>
          <input [(ngModel)]="subject" placeholder="Subject"
            class="px-3.5 py-2.5 border border-gray-300 rounded-lg text-sm outline-none font-sans focus:border-indigo-600 focus:ring-2 focus:ring-indigo-600/10 transition-all" />
        </div>
        <div class="flex flex-col gap-1.5 mb-4">
          <label class="text-sm font-medium text-gray-700">Message</label>
          <textarea
            [(ngModel)]="message"
            placeholder="Your message"
            rows="5"
            class="px-3.5 py-2.5 border border-gray-300 rounded-lg text-sm outline-none font-sans resize-y focus:border-indigo-600 focus:ring-2 focus:ring-indigo-600/10 transition-all"
          ></textarea>
        </div>
        <button class="w-full py-3 bg-indigo-600 hover:bg-indigo-700 text-white font-semibold rounded-lg text-base border-none cursor-pointer mt-2 transition-colors" (click)="sent = true">
          Send Message
        </button>
        @if (sent) {
          <p class="mt-4 text-emerald-600 text-sm font-medium text-center">Thanks! Your message has been sent.</p>
        }
      </div>
    </div>
  `,
  styles: []
})
export class ContactComponent {
  name = '';
  email = '';
  subject = '';
  message = '';
  sent = false;
}
