// templates/styling/tailwind/overlays/crm/vue/src/pages/Settings.vue
<script setup lang="ts">
import { ref } from 'vue'

const companyName = ref('My Company')
const email = ref('admin@company.com')
const saved = ref(false)

const save = () => {
  saved.value = true
  setTimeout(() => (saved.value = false), 2000)
}
</script>

<template>
  <div>
    <div class="mb-6">
      <h1 class="text-2xl font-bold text-gray-900">Settings</h1>
      <p class="text-gray-500 text-sm">Manage your CRM preferences</p>
    </div>
    <div class="bg-white rounded-lg p-6 max-w-lg shadow-sm">
      <div class="mb-5">
        <label class="block text-sm font-semibold text-gray-700 mb-1.5">Company Name</label>
        <input v-model="companyName" type="text" class="w-full py-2.5 px-3 border border-gray-300 rounded-md text-sm focus:outline-none focus:border-indigo-600 transition-colors" />
      </div>
      <div class="mb-5">
        <label class="block text-sm font-semibold text-gray-700 mb-1.5">Email Address</label>
        <input v-model="email" type="email" class="w-full py-2.5 px-3 border border-gray-300 rounded-md text-sm focus:outline-none focus:border-indigo-600 transition-colors" />
      </div>
      <button class="bg-indigo-600 text-white border-none py-2.5 px-6 rounded-md text-sm font-semibold cursor-pointer transition-colors hover:bg-indigo-700" @click="save">Save Changes</button>
      <p v-if="saved" class="text-emerald-600 mt-3 text-sm">Settings saved successfully!</p>
    </div>
  </div>
</template>

// templates/styling/tailwind/overlays/crm/react/src/pages/Settings.tsx
function Settings() {
  return (
    <div>
      <header className="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-8 gap-4">
        <h1 className="text-2xl font-bold text-gray-900">Settings</h1>
      </header>
      <div className="bg-white rounded-xl p-8 border border-gray-200 max-w-lg">
        <form className="flex flex-col gap-5" onSubmit={(e) => e.preventDefault()}>
          <div className="flex flex-col gap-1.5">
            <label htmlFor="companyName" className="text-sm font-semibold text-gray-700">
              Company Name
            </label>
            <input
              type="text"
              id="companyName"
              defaultValue="My Company"
              className="px-3 py-2.5 border border-gray-300 rounded-lg text-sm font-[inherit] focus:outline-none focus:border-indigo-600"
            />
          </div>
          <div className="flex flex-col gap-1.5">
            <label htmlFor="email" className="text-sm font-semibold text-gray-700">
              Email Address
            </label>
            <input
              type="email"
              id="email"
              defaultValue="admin@company.com"
              className="px-3 py-2.5 border border-gray-300 rounded-lg text-sm font-[inherit] focus:outline-none focus:border-indigo-600"
            />
          </div>
          <div className="flex flex-col gap-1.5">
            <label htmlFor="timezone" className="text-sm font-semibold text-gray-700">
              Timezone
            </label>
            <select
              id="timezone"
              defaultValue="UTC-5"
              className="px-3 py-2.5 border border-gray-300 rounded-lg text-sm font-[inherit] focus:outline-none focus:border-indigo-600"
            >
              <option value="UTC-8">Pacific Time (UTC-8)</option>
              <option value="UTC-7">Mountain Time (UTC-7)</option>
              <option value="UTC-6">Central Time (UTC-6)</option>
              <option value="UTC-5">Eastern Time (UTC-5)</option>
              <option value="UTC+0">UTC</option>
              <option value="UTC+1">Central European (UTC+1)</option>
            </select>
          </div>
          <button
            type="submit"
            className="bg-indigo-600 text-white border-none px-5 py-2.5 rounded-lg cursor-pointer font-semibold text-sm hover:bg-indigo-700 transition-colors"
          >
            Save Changes
          </button>
        </form>
      </div>
    </div>
  );
}

export default Settings;
