// templates/styling/tailwind/overlays/crm/react/src/pages/Deals.tsx
interface Deal {
  id: number;
  company: string;
  value: number;
  contact: string;
  stage: string;
}

const deals: Deal[] = [
  { id: 1, company: 'Acme Corp', value: 25000, contact: 'John Smith', stage: 'Qualified' },
  { id: 2, company: 'Globex Inc', value: 18000, contact: 'Sarah Johnson', stage: 'Prospect' },
  { id: 3, company: 'Wayne Enterprises', value: 45000, contact: 'Emily Chen', stage: 'Proposal' },
  { id: 4, company: 'Stark Industries', value: 32000, contact: 'Alex Turner', stage: 'Won' },
  { id: 5, company: 'Initech', value: 12000, contact: 'Mike Davis', stage: 'Qualified' },
  { id: 6, company: 'Oscorp', value: 28000, contact: 'David Brown', stage: 'Prospect' },
  { id: 7, company: 'LexCorp', value: 55000, contact: 'Rachel Green', stage: 'Proposal' },
  { id: 8, company: 'Umbrella Corp', value: 15000, contact: 'Lisa Wang', stage: 'Won' },
];

const stages = ['Prospect', 'Qualified', 'Proposal', 'Won'];

function Deals() {
  return (
    <div>
      <header className="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-8 gap-4">
        <h1 className="text-2xl font-bold text-gray-900">Deals Pipeline</h1>
      </header>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {stages.map((stage) => (
          <div key={stage} className="bg-white rounded-xl p-4 border border-gray-200">
            <h3 className="text-sm font-semibold text-gray-700 mb-4 pb-3 border-b-2 border-indigo-600">
              {stage}
            </h3>
            {deals
              .filter((d) => d.stage === stage)
              .map((deal) => (
                <div key={deal.id} className="bg-gray-50 rounded-lg p-4 mb-3 border border-gray-200">
                  <h4 className="text-sm font-semibold text-gray-900 mb-1">{deal.company}</h4>
                  <p className="text-base font-bold text-indigo-600 my-1">${deal.value.toLocaleString()}</p>
                  <span className="text-xs text-gray-500">{deal.contact}</span>
                </div>
              ))}
          </div>
        ))}
      </div>
    </div>
  );
}

export default Deals;

// templates/styling/tailwind/overlays/crm/vue/src/pages/Deals.vue
<script setup lang="ts">
import { computed } from 'vue'
import { deals } from '../data'

const stages = ['Prospect', 'Qualified', 'Proposal', 'Won'] as const

const columns = computed(() =>
  stages.map(stage => ({
    stage,
    deals: deals.filter(d => d.stage === stage),
  }))
)

const formatValue = (v: number) => `$${v.toLocaleString()}`
</script>

<template>
  <div>
    <div class="mb-6">
      <h1 class="text-2xl font-bold text-gray-900">Deals</h1>
      <p class="text-gray-500 text-sm">Track your sales pipeline</p>
    </div>
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
      <div v-for="col in columns" :key="col.stage" class="bg-white rounded-lg p-4 shadow-sm">
        <h3 class="text-xs uppercase tracking-wider text-gray-500 mb-3 pb-2 border-b-2 border-indigo-600">{{ col.stage }}</h3>
        <div v-for="deal in col.deals" :key="deal.id" class="bg-gray-50 rounded-md p-3 mb-2 border border-gray-200">
          <div class="font-semibold text-sm text-gray-900">{{ deal.name }}</div>
          <div class="text-xs text-gray-500">{{ deal.company }}</div>
          <div class="text-sm font-bold text-indigo-600 mt-1">{{ formatValue(deal.value) }}</div>
        </div>
      </div>
    </div>
  </div>
</template>
