// templates/styling/tailwind/overlays/crm/vue/src/components/ContactsTable.vue
<script setup lang="ts">
import type { Contact } from '../data'

defineProps<{ contacts: Contact[] }>()

const badgeClass = (status: string) => {
  switch (status) {
    case 'Lead': return 'bg-blue-100 text-blue-800'
    case 'Prospect': return 'bg-amber-100 text-amber-800'
    case 'Customer': return 'bg-emerald-100 text-emerald-800'
    case 'Churned': return 'bg-red-100 text-red-800'
    default: return 'bg-gray-100 text-gray-800'
  }
}
</script>

<template>
  <div class="bg-white rounded-lg shadow-sm overflow-hidden">
    <table class="w-full border-collapse">
      <thead>
        <tr>
          <th class="text-left px-4 py-3 text-xs uppercase tracking-wider text-gray-500 bg-gray-50 border-b border-gray-200">Name</th>
          <th class="text-left px-4 py-3 text-xs uppercase tracking-wider text-gray-500 bg-gray-50 border-b border-gray-200">Email</th>
          <th class="text-left px-4 py-3 text-xs uppercase tracking-wider text-gray-500 bg-gray-50 border-b border-gray-200">Company</th>
          <th class="text-left px-4 py-3 text-xs uppercase tracking-wider text-gray-500 bg-gray-50 border-b border-gray-200">Phone</th>
          <th class="text-left px-4 py-3 text-xs uppercase tracking-wider text-gray-500 bg-gray-50 border-b border-gray-200">Status</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="contact in contacts" :key="contact.id" class="hover:bg-gray-50">
          <td class="px-4 py-3 border-b border-gray-100 text-sm">{{ contact.name }}</td>
          <td class="px-4 py-3 border-b border-gray-100 text-sm">{{ contact.email }}</td>
          <td class="px-4 py-3 border-b border-gray-100 text-sm">{{ contact.company }}</td>
          <td class="px-4 py-3 border-b border-gray-100 text-sm">{{ contact.phone }}</td>
          <td class="px-4 py-3 border-b border-gray-100 text-sm"><span :class="['inline-block px-2.5 py-0.5 rounded-full text-xs font-semibold', badgeClass(contact.status)]">{{ contact.status }}</span></td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

// templates/styling/tailwind/overlays/crm/react/src/components/ContactsTable.tsx
import type { Contact } from '../data/contacts';

interface ContactsTableProps {
  contacts: Contact[];
}

const statusStyles: Record<string, string> = {
  lead: 'bg-amber-100 text-amber-800',
  prospect: 'bg-blue-100 text-blue-800',
  customer: 'bg-emerald-100 text-emerald-800',
  churned: 'bg-red-100 text-red-800',
};

function ContactsTable({ contacts }: ContactsTableProps) {
  return (
    <div className="bg-white rounded-xl border border-gray-200 overflow-hidden">
      <table className="w-full border-collapse">
        <thead>
          <tr>
            <th className="text-left px-5 py-3 text-xs text-gray-500 uppercase tracking-wider bg-gray-50 border-b border-gray-200">Name</th>
            <th className="text-left px-5 py-3 text-xs text-gray-500 uppercase tracking-wider bg-gray-50 border-b border-gray-200">Email</th>
            <th className="text-left px-5 py-3 text-xs text-gray-500 uppercase tracking-wider bg-gray-50 border-b border-gray-200">Company</th>
            <th className="text-left px-5 py-3 text-xs text-gray-500 uppercase tracking-wider bg-gray-50 border-b border-gray-200">Status</th>
            <th className="text-left px-5 py-3 text-xs text-gray-500 uppercase tracking-wider bg-gray-50 border-b border-gray-200">Phone</th>
          </tr>
        </thead>
        <tbody>
          {contacts.map((c) => (
            <tr key={c.id}>
              <td className="px-5 py-3 border-b border-gray-100 text-sm font-semibold text-gray-900">{c.name}</td>
              <td className="px-5 py-3 border-b border-gray-100 text-sm text-gray-500">{c.email}</td>
              <td className="px-5 py-3 border-b border-gray-100 text-sm">{c.company}</td>
              <td className="px-5 py-3 border-b border-gray-100 text-sm">
                <span className={`inline-block px-2.5 py-0.5 rounded-full text-xs font-medium ${statusStyles[c.status.toLowerCase()] || ''}`}>
                  {c.status}
                </span>
              </td>
              <td className="px-5 py-3 border-b border-gray-100 text-sm text-gray-700">{c.phone}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export default ContactsTable;
