// templates/styling/material-ui/overlays/blog/react/src/pages/Home.tsx
import { Box, Stack } from '@mui/material';
import PostCard from '../components/PostCard';
import BlogSidebar from '../components/BlogSidebar';
import { posts } from '../data/posts';

function Home() {
  return (
    <Box sx={{ display: 'flex', gap: 4 }}>
      <Stack spacing={2} sx={{ flex: 1 }}>
        {posts.map((post) => (
          <PostCard key={post.id} post={post} />
        ))}
      </Stack>
      <BlogSidebar />
    </Box>
  );
}

export default Home;

// templates/styling/tailwind/overlays/blog/vue/src/pages/Home.vue
<script setup lang="ts">
import PostCard from '../components/PostCard.vue'
import BlogSidebar from '../components/BlogSidebar.vue'
import { posts } from '../data'
</script>

<template>
  <div class="grid grid-cols-1 lg:grid-cols-[1fr_300px] gap-8">
    <div class="flex flex-col gap-6">
      <PostCard v-for="post in posts" :key="post.id" :post="post" />
    </div>
    <BlogSidebar />
  </div>
</template>
