// templates/styling/css-modules/overlays/crm/nuxt/pages/contacts.vue
<script setup lang="ts">
const search = ref('');
</script>

<template>
  <div>
    <div :class="$style.pageHeader">
      <div>
        <h1>Contacts</h1>
        <p :class="$style.subtitle">Manage your customer relationships.</p>
      </div>
      <button :class="$style.addBtn">+ Add Contact</button>
    </div>

    <div :class="$style.searchBar">
      <input v-model="search" type="text" placeholder="Search contacts..." :class="$style.searchInput" />
    </div>

    <ContactsTable :search-query="search" />
  </div>
</template>

<style module>
.pageHeader { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 1.5rem; }
.pageHeader h1 { font-size: 1.75rem; color: #111827; margin-bottom: 0.25rem; }
.subtitle { color: #6b7280; }
.addBtn { background: #4f46e5; color: white; border: none; padding: 0.65rem 1.25rem; border-radius: 8px; font-weight: 600; cursor: pointer; transition: background 0.2s; }
.addBtn:hover { background: #4338ca; }
.searchBar { margin-bottom: 1.25rem; }
.searchInput { width: 100%; max-width: 400px; padding: 0.65rem 1rem; border: 1px solid #d1d5db; border-radius: 8px; font-size: 0.95rem; outline: none; }
.searchInput:focus { border-color: #4f46e5; box-shadow: 0 0 0 3px rgba(79, 70, 229, 0.1); }
</style>

// templates/styling/styled-components/overlays/crm/react/src/pages/Contacts.tsx
import { useState } from 'react';
import styled from 'styled-components';
import ContactsTable from '../components/ContactsTable';
import { contacts } from '../data/contacts';

const CRMHeader = styled.header`
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 2rem;

  h1 {
    font-size: 1.75rem;
    font-weight: 700;
    color: #111827;
    margin: 0;
  }

  @media (max-width: 768px) {
    flex-direction: column;
    gap: 1rem;
    align-items: flex-start;
  }
`;

const SearchInput = styled.input`
  padding: 0.5rem 1rem;
  border: 1px solid #d1d5db;
  border-radius: 8px;
  font-size: 0.9rem;
  width: 260px;

  &:focus {
    outline: none;
    border-color: #4f46e5;
    box-shadow: 0 0 0 2px rgba(79, 70, 229, 0.15);
  }

  @media (max-width: 768px) {
    width: 100%;
  }
`;

function Contacts() {
  const [search, setSearch] = useState('');

  const filtered = contacts.filter(
    (c) =>
      c.name.toLowerCase().includes(search.toLowerCase()) ||
      c.email.toLowerCase().includes(search.toLowerCase()) ||
      c.company.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div>
      <CRMHeader>
        <h1>Contacts</h1>
        <SearchInput
          type="text"
          placeholder="Search contacts..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />
      </CRMHeader>
      <ContactsTable contacts={filtered} />
    </div>
  );
}

export default Contacts;
