// templates/styling/css-modules/overlays/crm/vue/src/pages/Contacts.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import ContactsTable from '../components/ContactsTable.vue'
import { contacts } from '../data'

const search = ref('')

const filtered = computed(() =>
  contacts.filter(c =>
    c.name.toLowerCase().includes(search.value.toLowerCase()) ||
    c.company.toLowerCase().includes(search.value.toLowerCase())
  )
)
</script>

<template>
  <div>
    <div :class="$style.pageHeader">
      <h1>Contacts</h1>
      <p>Manage your contacts and leads</p>
    </div>
    <input v-model="search" :class="$style.searchInput" placeholder="Search contacts..." />
    <ContactsTable :contacts="filtered" />
  </div>
</template>

<style module>
.pageHeader {
  margin-bottom: 1.5rem;
}

.pageHeader h1 {
  font-size: 1.5rem;
  color: #111827;
  font-weight: 700;
}

.pageHeader p {
  color: #6b7280;
  font-size: 0.9rem;
}

.searchInput {
  width: 100%;
  max-width: 320px;
  padding: 0.6rem 1rem;
  border: 1px solid #d1d5db;
  border-radius: 6px;
  font-size: 0.9rem;
  margin-bottom: 1rem;
  outline: none;
  transition: border-color 0.2s;
}

.searchInput:focus {
  border-color: #4f46e5;
}
</style>

// templates/styling/styled-components/overlays/crm/react/src/pages/Contacts.tsx
import { useState } from 'react';
import styled from 'styled-components';
import ContactsTable from '../components/ContactsTable';
import { contacts } from '../data/contacts';

const CRMHeader = styled.header`
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 2rem;

  h1 {
    font-size: 1.75rem;
    font-weight: 700;
    color: #111827;
    margin: 0;
  }

  @media (max-width: 768px) {
    flex-direction: column;
    gap: 1rem;
    align-items: flex-start;
  }
`;

const SearchInput = styled.input`
  padding: 0.5rem 1rem;
  border: 1px solid #d1d5db;
  border-radius: 8px;
  font-size: 0.9rem;
  width: 260px;

  &:focus {
    outline: none;
    border-color: #4f46e5;
    box-shadow: 0 0 0 2px rgba(79, 70, 229, 0.15);
  }

  @media (max-width: 768px) {
    width: 100%;
  }
`;

function Contacts() {
  const [search, setSearch] = useState('');

  const filtered = contacts.filter(
    (c) =>
      c.name.toLowerCase().includes(search.toLowerCase()) ||
      c.email.toLowerCase().includes(search.toLowerCase()) ||
      c.company.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div>
      <CRMHeader>
        <h1>Contacts</h1>
        <SearchInput
          type="text"
          placeholder="Search contacts..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />
      </CRMHeader>
      <ContactsTable contacts={filtered} />
    </div>
  );
}

export default Contacts;
