// templates/styling/chakra-ui/overlays/blog/nextjs/src/app/components/BlogHeader.tsx
'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { Box, Flex, Text } from '@chakra-ui/react';

const navItems = [
  { href: '/', label: 'Home' },
  { href: '/category/technology', label: 'Technology' },
  { href: '/category/design', label: 'Design' },
  { href: '/about', label: 'About' },
];

export function BlogHeader() {
  const pathname = usePathname();

  return (
    <Box as="header" bg="white" borderBottom="1px solid" borderColor="gray.200" position="sticky" top={0} zIndex={100}>
      <Flex maxW="1100px" mx="auto" px={6} align="center" justify="space-between" h="64px">
        <Link href="/" style={{ textDecoration: 'none' }}>
          <Flex align="center" gap={2}>
            <Text fontSize="1.4rem">📝</Text>
            <Text fontSize="1.25rem" fontWeight={700} color="gray.900">{'{{projectName}}'}</Text>
          </Flex>
        </Link>
        <Flex as="nav" gap={6}>
          {navItems.map((item) => (
            <Link key={item.href} href={item.href} style={{ textDecoration: 'none' }}>
              <Text
                fontWeight={500}
                color={pathname === item.href ? '#4f46e5' : 'gray.600'}
                borderBottom="2px solid"
                borderColor={pathname === item.href ? '#4f46e5' : 'transparent'}
                py={1}
                _hover={{ color: '#4f46e5' }}
                transition="color 0.2s"
              >
                {item.label}
              </Text>
            </Link>
          ))}
        </Flex>
      </Flex>
    </Box>
  );
}

// templates/overlays/blog/nuxt/components/BlogHeader.vue
<template>
  <header class="blog-header">
    <div class="header-inner">
      <NuxtLink to="/" class="logo">📝 {{projectName}}</NuxtLink>
      <nav class="header-nav">
        <NuxtLink to="/" class="nav-link">Home</NuxtLink>
        <NuxtLink to="/about" class="nav-link">About</NuxtLink>
      </nav>
    </div>
  </header>
</template>

<style scoped>
.blog-header {
  background: #111827;
  color: white;
  padding: 0 1rem;
  position: sticky;
  top: 0;
  z-index: 100;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.15);
}

.header-inner {
  max-width: 1100px;
  margin: 0 auto;
  display: flex;
  align-items: center;
  justify-content: space-between;
  height: 64px;
}

.logo {
  font-size: 1.35rem;
  font-weight: 700;
  color: white;
  font-family: 'Segoe UI', system-ui, sans-serif;
}

.header-nav {
  display: flex;
  gap: 1.5rem;
}

.nav-link {
  color: #d1d5db;
  font-weight: 500;
  font-family: 'Segoe UI', system-ui, sans-serif;
  transition: color 0.2s;
}

.nav-link:hover {
  color: white;
}
</style>
