// templates/styling/ant-design/overlays/blog/react/src/pages/PostDetail.tsx
import { useParams, Link } from 'react-router-dom';
import { Typography, Tag, Card, Divider, Button, Space } from 'antd';
import { ArrowLeftOutlined } from '@ant-design/icons';
import { posts } from '../data/posts';

const { Title, Text, Paragraph } = Typography;

function PostDetail() {
  const { id } = useParams();
  const post = posts.find((p) => p.id === Number(id));

  if (!post) {
    return (
      <div style={{ textAlign: 'center', padding: 64 }}>
        <Paragraph>Post not found.</Paragraph>
        <Link to="/"><Button type="primary">Back to Home</Button></Link>
      </div>
    );
  }

  return (
    <div style={{ maxWidth: 800, margin: '0 auto' }}>
      <Link to="/" style={{ display: 'inline-flex', alignItems: 'center', gap: 8, marginBottom: 24, color: '#4f46e5' }}>
        <ArrowLeftOutlined /> Back to Posts
      </Link>
      <div style={{ textAlign: 'center', marginBottom: 32 }}>
        <span style={{ fontSize: 64 }}>{post.image}</span>
        <div style={{ marginTop: 16 }}>
          <Link to={`/category/${post.category.toLowerCase()}`}>
            <Tag color="blue">{post.category}</Tag>
          </Link>
        </div>
        <Title level={1} style={{ marginTop: 16 }}>{post.title}</Title>
        <Space split={<Text type="secondary">|</Text>}>
          <Text type="secondary">By {post.author}</Text>
          <Text type="secondary">{post.date}</Text>
          <Text type="secondary">{post.readTime} read</Text>
        </Space>
      </div>
      <Paragraph style={{ fontSize: 16, lineHeight: 1.8 }}>{post.content}</Paragraph>
      <Divider />
      <Card>
        <Title level={4}>About {post.author}</Title>
        <Paragraph type="secondary">
          A passionate developer writing about web technologies, best practices, and software engineering.
        </Paragraph>
      </Card>
    </div>
  );
}

export default PostDetail;

// templates/styling/css-modules/overlays/blog/vue/src/pages/PostDetail.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useRoute } from 'vue-router'
import { posts } from '../data'

const route = useRoute()
const post = computed(() => posts.find(p => p.id === Number(route.params.id)))
</script>

<template>
  <div :class="$style.postDetail" v-if="post">
    <RouterLink to="/" :class="$style.backLink">&larr; Back to posts</RouterLink>
    <div :class="$style.postHeroImage">{{ post.image }}</div>
    <h1>{{ post.title }}</h1>
    <div :class="$style.detailMeta">{{ post.author }} &middot; {{ post.date }} &middot; {{ post.readTime }}</div>
    <div :class="$style.postContent">{{ post.content }}</div>
  </div>
  <div v-else :class="$style.postDetail">
    <RouterLink to="/" :class="$style.backLink">&larr; Back to posts</RouterLink>
    <p>Post not found.</p>
  </div>
</template>

<style module>
.postDetail {
  max-width: 720px;
  margin: 0 auto;
}

.backLink {
  display: inline-block;
  margin-bottom: 1.5rem;
  font-size: 0.9rem;
  color: #4f46e5;
}

.postHeroImage {
  font-size: 4rem;
  text-align: center;
  background: #eef2ff;
  padding: 2rem;
  border-radius: 8px;
  margin-bottom: 1.5rem;
}

.postDetail h1 {
  font-size: 2rem;
  color: #111827;
  margin-bottom: 0.5rem;
}

.detailMeta {
  color: #6b7280;
  font-size: 0.9rem;
  margin-bottom: 1.5rem;
}

.postContent {
  font-size: 1.05rem;
  line-height: 1.8;
  color: #374151;
}
</style>
