// templates/overlays/blog/vue/src/components/BlogSidebar.vue
<script setup lang="ts">
import { ref } from 'vue'
import { categories } from '../data'

const email = ref('')
const subscribed = ref(false)

const subscribe = () => {
  if (email.value) {
    subscribed.value = true
    email.value = ''
  }
}
</script>

<template>
  <aside class="blog-sidebar">
    <h3>Categories</h3>
    <ul class="category-list">
      <li v-for="cat in categories" :key="cat">
        <RouterLink :to="`/category/${cat.toLowerCase().replace('.', '')}`">{{ cat }}</RouterLink>
      </li>
    </ul>
    <h3>Newsletter</h3>
    <div class="newsletter-form">
      <input v-model="email" type="email" placeholder="your@email.com" />
      <button @click="subscribe">Subscribe</button>
      <p v-if="subscribed" style="color: #059669; font-size: 0.8rem; margin-top: 0.4rem;">Subscribed!</p>
    </div>
  </aside>
</template>

// templates/styling/ant-design/overlays/blog/react/src/components/BlogSidebar.tsx
import { Link } from 'react-router-dom';
import { Card, Tag, Input, Button, Typography, Space } from 'antd';
import { categories } from '../data/posts';

const { Title, Paragraph } = Typography;

function BlogSidebar() {
  return (
    <aside style={{ minWidth: 280 }}>
      <Card title="Categories" style={{ marginBottom: 16 }}>
        <Space wrap>
          {categories.map((cat) => (
            <Link key={cat} to={`/category/${cat.toLowerCase()}`}>
              <Tag color="blue" style={{ cursor: 'pointer', marginBottom: 4 }}>{cat}</Tag>
            </Link>
          ))}
        </Space>
      </Card>
      <Card title="Newsletter">
        <Paragraph type="secondary">Subscribe to get the latest posts delivered to your inbox.</Paragraph>
        <Input placeholder="your@email.com" style={{ marginBottom: 12 }} />
        <Button type="primary" block>Subscribe</Button>
      </Card>
    </aside>
  );
}

export default BlogSidebar;
