// templates/overlays/crm/react/src/pages/DashboardHome.tsx
import StatsCards from '../components/StatsCards';
import { contacts } from '../data/contacts';

function DashboardHome() {
  const recentContacts = contacts.slice(0, 5);

  return (
    <div>
      <header className="crm-header">
        <h1>Dashboard</h1>
      </header>
      <StatsCards />
      <h2 className="section-title">Recent Contacts</h2>
      <div className="table-card">
        <table className="data-table">
          <thead>
            <tr>
              <th>Name</th>
              <th>Email</th>
              <th>Company</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            {recentContacts.map((c) => (
              <tr key={c.id}>
                <td className="contact-name">{c.name}</td>
                <td className="contact-email">{c.email}</td>
                <td>{c.company}</td>
                <td>
                  <span className={`status-badge status-${c.status.toLowerCase()}`}>
                    {c.status}
                  </span>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

export default DashboardHome;

// templates/overlays/crm/vue/src/pages/DashboardHome.vue
<script setup lang="ts">
import StatsCards from '../components/StatsCards.vue'
import ContactsTable from '../components/ContactsTable.vue'
import { contacts } from '../data'

const recentContacts = contacts.slice(0, 5)
</script>

<template>
  <div>
    <div class="page-header">
      <h1>Dashboard</h1>
      <p>Overview of your CRM activity</p>
    </div>
    <StatsCards :contacts="contacts" />
    <h2 style="font-size: 1.1rem; color: #111827; margin-bottom: 0.75rem;">Recent Contacts</h2>
    <ContactsTable :contacts="recentContacts" />
  </div>
</template>
