// templates/overlays/crm/vue/src/components/ContactsTable.vue
<script setup lang="ts">
import type { Contact } from '../data'

defineProps<{ contacts: Contact[] }>()
</script>

<template>
  <div class="table-container">
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Company</th>
          <th>Phone</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="contact in contacts" :key="contact.id">
          <td>{{ contact.name }}</td>
          <td>{{ contact.email }}</td>
          <td>{{ contact.company }}</td>
          <td>{{ contact.phone }}</td>
          <td><span class="status-badge" :class="contact.status">{{ contact.status }}</span></td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

// templates/styling/css-modules/overlays/crm/react/src/components/ContactsTable.tsx
import type { Contact } from '../data/contacts';
import styles from './ContactsTable.module.css';

interface ContactsTableProps {
  contacts: Contact[];
}

const statusStyles: Record<string, string> = {
  Lead: styles.statusLead,
  Prospect: styles.statusProspect,
  Customer: styles.statusCustomer,
  Churned: styles.statusChurned,
};

function ContactsTable({ contacts }: ContactsTableProps) {
  return (
    <div className={styles.tableCard}>
      <table className={styles.dataTable}>
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Company</th>
            <th>Status</th>
            <th>Phone</th>
          </tr>
        </thead>
        <tbody>
          {contacts.map((c) => (
            <tr key={c.id}>
              <td className={styles.contactName}>{c.name}</td>
              <td className={styles.contactEmail}>{c.email}</td>
              <td>{c.company}</td>
              <td>
                <span className={statusStyles[c.status]}>
                  {c.status}
                </span>
              </td>
              <td className={styles.contactPhone}>{c.phone}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export default ContactsTable;
