// templates/overlays/crm/vue/src/pages/Settings.vue
<script setup lang="ts">
import { ref } from 'vue'

const companyName = ref('My Company')
const email = ref('admin@company.com')
const saved = ref(false)

const save = () => {
  saved.value = true
  setTimeout(() => (saved.value = false), 2000)
}
</script>

<template>
  <div>
    <div class="page-header">
      <h1>Settings</h1>
      <p>Manage your CRM preferences</p>
    </div>
    <div class="settings-form">
      <div class="form-group">
        <label>Company Name</label>
        <input v-model="companyName" type="text" />
      </div>
      <div class="form-group">
        <label>Email Address</label>
        <input v-model="email" type="email" />
      </div>
      <button class="btn-primary" @click="save">Save Changes</button>
      <p v-if="saved" style="color: #059669; margin-top: 0.75rem; font-size: 0.85rem;">Settings saved successfully!</p>
    </div>
  </div>
</template>

// templates/overlays/dashboard/react/src/pages/Settings.tsx
import { useState } from 'react';

export function Settings() {
  const [name, setName] = useState('Brian Admin');
  const [email, setEmail] = useState('brian@example.com');
  const [darkMode, setDarkMode] = useState(false);
  const [notifications, setNotifications] = useState(true);

  return (
    <div className="page-settings">
      <h1>Settings</h1>
      <div className="settings-card">
        <h3>Profile</h3>
        <div className="form-group">
          <label htmlFor="name">Full Name</label>
          <input id="name" type="text" value={name} onChange={(e) => setName(e.target.value)} className="form-input" />
        </div>
        <div className="form-group">
          <label htmlFor="email">Email Address</label>
          <input id="email" type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="form-input" />
        </div>
      </div>
      <div className="settings-card">
        <h3>Preferences</h3>
        <div className="form-toggle">
          <label>
            <input type="checkbox" checked={darkMode} onChange={(e) => setDarkMode(e.target.checked)} />
            <span>Dark Mode</span>
          </label>
        </div>
        <div className="form-toggle">
          <label>
            <input type="checkbox" checked={notifications} onChange={(e) => setNotifications(e.target.checked)} />
            <span>Email Notifications</span>
          </label>
        </div>
      </div>
      <button className="primary-btn">Save Changes</button>
    </div>
  );
}
