// templates/styling/tailwind/overlays/landing/angular/src/app/components/footer.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-footer',
  standalone: true,
  template: `
    <footer class="bg-gray-900 text-gray-300 pt-16 pb-8 px-6">
      <div class="flex flex-wrap justify-between max-w-7xl mx-auto gap-16">
        <div>
          <h3 class="text-white text-2xl font-bold mb-2">{{projectName}}</h3>
          <p class="max-w-xs">Building the future of the web.</p>
        </div>
        <div class="flex gap-16">
          <div class="flex flex-col gap-2">
            <h4 class="text-white text-sm uppercase font-semibold mb-2">Product</h4>
            <a href="#features" class="text-gray-400 hover:text-white transition-colors">Features</a>
            <a href="#cta" class="text-gray-400 hover:text-white transition-colors">Pricing</a>
          </div>
          <div class="flex flex-col gap-2">
            <h4 class="text-white text-sm uppercase font-semibold mb-2">Company</h4>
            <a href="#" class="text-gray-400 hover:text-white transition-colors">About</a>
            <a href="#" class="text-gray-400 hover:text-white transition-colors">Blog</a>
          </div>
        </div>
      </div>
      <div class="border-t border-gray-700 mt-12 pt-6 text-center">
        <p class="text-sm text-gray-500">&copy; 2025 {{projectName}}. All rights reserved.</p>
      </div>
    </footer>
  `,
  styles: []
})
export class FooterComponent {}

// templates/styling/styled-components/overlays/landing/nextjs/src/app/components/Footer.tsx
'use client';

import styled from 'styled-components';

const StyledFooter = styled.footer`
  background: #111827;
  color: #d1d5db;
  padding: 4rem 2rem 2rem;
`;

const FooterContent = styled.div`
  display: flex;
  justify-content: space-between;
  max-width: 1200px;
  margin: 0 auto;
  gap: 4rem;
  flex-wrap: wrap;
`;

const FooterBrand = styled.div`
  h3 {
    color: white;
    font-size: 1.5rem;
    margin-bottom: 0.5rem;
  }
`;

const FooterLinks = styled.div`
  display: flex;
  gap: 4rem;
`;

const FooterCol = styled.div`
  display: flex;
  flex-direction: column;
  gap: 0.5rem;

  h4 {
    color: white;
    font-size: 0.875rem;
    text-transform: uppercase;
    margin-bottom: 0.5rem;
  }

  a {
    color: #9ca3af;
    text-decoration: none;

    &:hover {
      color: white;
    }
  }
`;

const FooterBottom = styled.div`
  border-top: 1px solid #374151;
  margin-top: 3rem;
  padding-top: 1.5rem;
  text-align: center;

  p {
    font-size: 0.875rem;
    color: #6b7280;
  }
`;

export function Footer() {
  return (
    <StyledFooter>
      <FooterContent>
        <FooterBrand>
          <h3>{'{{projectName}}'}</h3>
          <p>Building the future of the web.</p>
        </FooterBrand>
        <FooterLinks>
          <FooterCol>
            <h4>Product</h4>
            <a href="#features">Features</a>
            <a href="#cta">Pricing</a>
          </FooterCol>
          <FooterCol>
            <h4>Company</h4>
            <a href="#">About</a>
            <a href="#">Blog</a>
          </FooterCol>
        </FooterLinks>
      </FooterContent>
      <FooterBottom>
        <p>&copy; 2025 {'{{projectName}}'}. All rights reserved.</p>
      </FooterBottom>
    </StyledFooter>
  );
}
