// templates/overlays/portfolio/react/src/pages/Contact.tsx
function Contact() {
  return (
    <div className="contact-section">
      <h2>Get In Touch</h2>
      <p className="section-subtitle">Have a project in mind? Let's work together.</p>
      <div className="contact-grid">
        <form className="contact-form" onSubmit={(e) => e.preventDefault()}>
          <div className="form-row">
            <div className="form-group">
              <label htmlFor="name">Name</label>
              <input type="text" id="name" placeholder="Your name" />
            </div>
            <div className="form-group">
              <label htmlFor="email">Email</label>
              <input type="email" id="email" placeholder="your@email.com" />
            </div>
          </div>
          <div className="form-group">
            <label htmlFor="subject">Subject</label>
            <input type="text" id="subject" placeholder="Project inquiry" />
          </div>
          <div className="form-group">
            <label htmlFor="message">Message</label>
            <textarea id="message" rows={5} placeholder="Tell me about your project..." />
          </div>
          <button type="submit" className="btn btn-primary">Send Message</button>
        </form>
        <div className="contact-details">
          <h3>Contact Info</h3>
          <div className="contact-item">
            <span>📧</span>
            <p>hello@developer.com</p>
          </div>
          <div className="contact-item">
            <span>📍</span>
            <p>San Francisco, CA</p>
          </div>
          <div className="contact-item">
            <span>🔗</span>
            <p>github.com/developer</p>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Contact;

// templates/overlays/portfolio/vue/src/pages/Contact.vue
<script setup lang="ts">
import { ref } from 'vue'

const name = ref('')
const email = ref('')
const subject = ref('')
const message = ref('')
const sent = ref(false)

const submit = () => {
  if (name.value && email.value && message.value) {
    sent.value = true
    name.value = ''
    email.value = ''
    subject.value = ''
    message.value = ''
    setTimeout(() => (sent.value = false), 3000)
  }
}
</script>

<template>
  <div class="contact-section">
    <h1>Get In Touch</h1>
    <p class="contact-subtitle">Have a project in mind? Let's work together.</p>
    <div class="contact-form">
      <div class="form-group">
        <label>Name</label>
        <input v-model="name" type="text" placeholder="Your name" />
      </div>
      <div class="form-group">
        <label>Email</label>
        <input v-model="email" type="email" placeholder="your@email.com" />
      </div>
      <div class="form-group">
        <label>Subject</label>
        <input v-model="subject" type="text" placeholder="Project inquiry" />
      </div>
      <div class="form-group">
        <label>Message</label>
        <textarea v-model="message" placeholder="Tell me about your project..."></textarea>
      </div>
      <button class="btn-primary" @click="submit">Send Message</button>
      <p v-if="sent" style="color: #059669; text-align: center; margin-top: 0.75rem; font-size: 0.9rem;">Message sent! I'll get back to you soon.</p>
    </div>
  </div>
</template>
