// templates/i18n/angular/src/app/i18n/lang-switcher.component.ts
import { Component } from '@angular/core';
import { NgFor } from '@angular/common';
import { I18nService, languages, type Lang } from './i18n.service';

@Component({
  selector: 'app-lang-switcher',
  standalone: true,
  imports: [NgFor],
  template: `
    <div style="display: inline-flex; gap: 0.25rem">
      <button
        *ngFor="let l of langs"
        (click)="setLang(l)"
        [style.padding]="'0.25rem 0.5rem'"
        [style.fontSize]="'0.75rem'"
        [style.border]="'1px solid'"
        [style.borderColor]="l === i18n.lang() ? '#4f46e5' : '#d1d5db'"
        [style.borderRadius]="'0.25rem'"
        [style.background]="l === i18n.lang() ? '#4f46e5' : 'transparent'"
        [style.color]="l === i18n.lang() ? '#fff' : 'inherit'"
        [style.cursor]="'pointer'"
        [style.textTransform]="'uppercase'"
      >{{ l }}</button>
    </div>
  `,
})
export class LangSwitcherComponent {
  langs = [...languages];
  constructor(public i18n: I18nService) {}
  setLang(l: string) { this.i18n.setLang(l as Lang); }
}

// templates/i18n/vue/src/i18n/LangSwitcher.vue
<script setup lang="ts">
import { useI18n, type Lang } from './index';

const { lang, switchLang, languages } = useI18n();
</script>

<template>
  <div style="display: inline-flex; gap: 0.25rem">
    <button
      v-for="l in languages"
      :key="l"
      @click="switchLang(l as Lang)"
      :style="{
        padding: '0.25rem 0.5rem',
        fontSize: '0.75rem',
        border: '1px solid',
        borderColor: l === lang ? '#4f46e5' : '#d1d5db',
        borderRadius: '0.25rem',
        background: l === lang ? '#4f46e5' : 'transparent',
        color: l === lang ? '#fff' : 'inherit',
        cursor: 'pointer',
        textTransform: 'uppercase',
      }"
    >
      {{ l }}
    </button>
  </div>
</template>
