// templates/i18n/react/src/i18n/LangSwitcher.tsx
import { languages, type Lang } from './index';

interface Props {
  current: Lang;
  onChange: (lang: Lang) => void;
}

export function LangSwitcher({ current, onChange }: Props) {
  return (
    <div style={{ display: 'inline-flex', gap: '0.25rem' }}>
      {languages.map((l) => (
        <button
          key={l}
          onClick={() => onChange(l)}
          style={{
            padding: '0.25rem 0.5rem',
            fontSize: '0.75rem',
            border: '1px solid',
            borderColor: l === current ? '#4f46e5' : '#d1d5db',
            borderRadius: '0.25rem',
            background: l === current ? '#4f46e5' : 'transparent',
            color: l === current ? '#fff' : 'inherit',
            cursor: 'pointer',
            textTransform: 'uppercase',
          }}
        >
          {l}
        </button>
      ))}
    </div>
  );
}

// templates/i18n/vue/src/i18n/LangSwitcher.vue
<script setup lang="ts">
import { useI18n, type Lang } from './index';

const { lang, switchLang, languages } = useI18n();
</script>

<template>
  <div style="display: inline-flex; gap: 0.25rem">
    <button
      v-for="l in languages"
      :key="l"
      @click="switchLang(l as Lang)"
      :style="{
        padding: '0.25rem 0.5rem',
        fontSize: '0.75rem',
        border: '1px solid',
        borderColor: l === lang ? '#4f46e5' : '#d1d5db',
        borderRadius: '0.25rem',
        background: l === lang ? '#4f46e5' : 'transparent',
        color: l === lang ? '#fff' : 'inherit',
        cursor: 'pointer',
        textTransform: 'uppercase',
      }"
    >
      {{ l }}
    </button>
  </div>
</template>
