// templates/styling/css-modules/overlays/portfolio/vue/src/pages/Contact.vue
<script setup lang="ts">
import { ref } from 'vue'

const name = ref('')
const email = ref('')
const subject = ref('')
const message = ref('')
const sent = ref(false)

const submit = () => {
  if (name.value && email.value && message.value) {
    sent.value = true
    name.value = ''
    email.value = ''
    subject.value = ''
    message.value = ''
    setTimeout(() => (sent.value = false), 3000)
  }
}
</script>

<template>
  <div :class="$style.contactSection">
    <h1>Get In Touch</h1>
    <p :class="$style.contactSubtitle">Have a project in mind? Let's work together.</p>
    <div :class="$style.contactForm">
      <div :class="$style.formGroup">
        <label>Name</label>
        <input v-model="name" type="text" placeholder="Your name" />
      </div>
      <div :class="$style.formGroup">
        <label>Email</label>
        <input v-model="email" type="email" placeholder="your@email.com" />
      </div>
      <div :class="$style.formGroup">
        <label>Subject</label>
        <input v-model="subject" type="text" placeholder="Project inquiry" />
      </div>
      <div :class="$style.formGroup">
        <label>Message</label>
        <textarea v-model="message" placeholder="Tell me about your project..."></textarea>
      </div>
      <button :class="$style.btnPrimary" @click="submit">Send Message</button>
      <p v-if="sent" style="color: #059669; text-align: center; margin-top: 0.75rem; font-size: 0.9rem;">Message sent! I'll get back to you soon.</p>
    </div>
  </div>
</template>

<style module>
.contactSection {
  max-width: 560px;
  margin: 0 auto;
  padding: 3rem 1.5rem;
}

.contactSection h1 {
  font-size: 1.75rem;
  color: #111827;
  text-align: center;
  margin-bottom: 0.5rem;
}

.contactSubtitle {
  text-align: center;
  color: #6b7280;
  margin-bottom: 2rem;
}

.contactForm {
  background: #fff;
  padding: 1.5rem;
  border-radius: 8px;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.08);
}

.formGroup {
  margin-bottom: 1.25rem;
}

.formGroup label {
  display: block;
  font-size: 0.85rem;
  font-weight: 600;
  color: #374151;
  margin-bottom: 0.4rem;
}

.formGroup input,
.formGroup textarea {
  width: 100%;
  padding: 0.6rem 0.75rem;
  border: 1px solid #d1d5db;
  border-radius: 6px;
  font-size: 0.9rem;
  font-family: inherit;
  outline: none;
  transition: border-color 0.2s;
}

.formGroup input:focus,
.formGroup textarea:focus {
  border-color: #4f46e5;
}

.formGroup textarea {
  resize: vertical;
  min-height: 120px;
}

.btnPrimary {
  width: 100%;
  background: #4f46e5;
  color: #fff;
  border: none;
  padding: 0.7rem;
  border-radius: 6px;
  font-size: 0.95rem;
  font-weight: 600;
  cursor: pointer;
  transition: background 0.2s;
}

.btnPrimary:hover {
  background: #4338ca;
}
</style>

// templates/overlays/portfolio/angular/src/app/pages/contact.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-contact',
  standalone: true,
  imports: [FormsModule],
  template: `
    <div class="contact-container">
      <div class="contact-form-card">
        <h1 class="contact-title">Get in Touch</h1>
        <p class="contact-description">Have a project in mind? Let's work together.</p>
        <div class="contact-field">
          <label>Name</label>
          <input [(ngModel)]="name" placeholder="Your name" />
        </div>
        <div class="contact-field">
          <label>Email</label>
          <input [(ngModel)]="email" type="email" placeholder="Your email" />
        </div>
        <div class="contact-field">
          <label>Subject</label>
          <input [(ngModel)]="subject" placeholder="Subject" />
        </div>
        <div class="contact-field">
          <label>Message</label>
          <textarea
            [(ngModel)]="message"
            placeholder="Your message"
            rows="5"
          ></textarea>
        </div>
        <button class="contact-submit-btn" (click)="sent = true">
          Send Message
        </button>
        @if (sent) {
          <p class="contact-success-message">Thanks! Your message has been sent.</p>
        }
      </div>
    </div>
  `,
  styles: [`
    .contact-container {
      max-width: 560px;
      margin: 0 auto;
      padding: 48px 24px;
    }

    .contact-form-card {
      background: #fff;
      border-radius: 16px;
      padding: 36px;
      box-shadow: 0 1px 3px rgba(0, 0, 0, 0.08);
    }

    .contact-title {
      font-size: 28px;
      font-weight: 800;
      color: #111827;
      margin-bottom: 8px;
    }

    .contact-description {
      font-size: 15px;
      color: #6b7280;
      margin-bottom: 28px;
    }

    .contact-field {
      margin-bottom: 16px;
      display: flex;
      flex-direction: column;
      gap: 6px;
    }

    .contact-field label {
      font-size: 13px;
      font-weight: 500;
      color: #374151;
    }

    .contact-field input,
    .contact-field textarea {
      padding: 10px 14px;
      border: 1px solid #d1d5db;
      border-radius: 8px;
      font-size: 14px;
      outline: none;
      font-family: inherit;
      resize: vertical;
    }

    .contact-field input:focus,
    .contact-field textarea:focus {
      border-color: #4f46e5;
      box-shadow: 0 0 0 3px rgba(79, 70, 229, 0.1);
    }

    .contact-submit-btn {
      width: 100%;
      padding: 12px;
      background: #4f46e5;
      color: #fff;
      border: none;
      border-radius: 8px;
      font-size: 15px;
      font-weight: 600;
      cursor: pointer;
      margin-top: 8px;
    }

    .contact-submit-btn:hover {
      background: #4338ca;
    }

    .contact-success-message {
      margin-top: 16px;
      color: #059669;
      font-size: 14px;
      font-weight: 500;
      text-align: center;
    }
  `]
})
export class ContactComponent {
  name = '';
  email = '';
  subject = '';
  message = '';
  sent = false;
}
