// templates/styling/styled-components/overlays/landing/react/src/components/CTA.tsx
import styled from 'styled-components';

const CTASection = styled.section`
  background: #f9fafb;
  padding: 5rem 2rem;
  text-align: center;
`;

const CTAContent = styled.div`
  max-width: 600px;
  margin: 0 auto;

  h2 {
    font-size: 2.5rem;
    font-weight: 700;
    margin-bottom: 1rem;
    color: #111827;
  }

  p {
    color: #6b7280;
    font-size: 1.1rem;
    margin-bottom: 2rem;
  }
`;

const CTAButton = styled.button`
  padding: 1rem 2.5rem;
  border-radius: 8px;
  font-size: 1.1rem;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.2s;
  border: 2px solid #4f46e5;
  background: #4f46e5;
  color: white;

  &:hover {
    background: #4338ca;
    border-color: #4338ca;
  }
`;

const CTANote = styled.p`
  margin-top: 0.75rem;
  font-size: 0.875rem;
  color: #9ca3af;
`;

export function CTA() {
  return (
    <CTASection id="cta">
      <CTAContent>
        <h2>Ready to Get Started?</h2>
        <p>Join thousands of developers who are building amazing products.</p>
        <div>
          <CTAButton>Start Free Trial</CTAButton>
          <CTANote>No credit card required</CTANote>
        </div>
      </CTAContent>
    </CTASection>
  );
}

// templates/styling/css-modules/overlays/landing/vue/src/components/CTA.vue
<template>
  <section id="cta" :class="$style.cta">
    <div :class="$style.ctaContent">
      <h2>Ready to Get Started?</h2>
      <p>Join thousands of developers building amazing products.</p>
      <button :class="[$style.btn, $style.btnPrimary, $style.btnLarge]">Start Free Trial</button>
      <p :class="$style.note">No credit card required</p>
    </div>
  </section>
</template>

<style module>
.cta { background: #f9fafb; padding: 5rem 2rem; text-align: center; }
.ctaContent { max-width: 600px; margin: 0 auto; }
.cta h2 { font-size: 2.5rem; font-weight: 700; margin-bottom: 1rem; }
.cta p { color: #6b7280; font-size: 1.1rem; margin-bottom: 2rem; }
.note { font-size: 0.875rem; color: #9ca3af; margin-top: 0.75rem; }
.btn { padding: 0.75rem 1.5rem; border-radius: 8px; font-size: 1rem; font-weight: 600; cursor: pointer; border: 2px solid transparent; }
.btnPrimary { background: #4f46e5; color: white; }
.btnLarge { padding: 1rem 2.5rem; font-size: 1.1rem; }
</style>
