// templates/styling/styled-components/overlays/ecommerce/nextjs/src/app/cart/page.tsx
'use client';

import Link from 'next/link';
import styled from 'styled-components';
import { useCart } from '../components/CartProvider';

const CartEmpty = styled.div`
  text-align: center;
  padding: 4rem 1.5rem;

  h2 {
    color: #111827;
    margin-bottom: 0.5rem;
  }

  p {
    color: #6b7280;
    margin-bottom: 1.5rem;
  }
`;

const CartEmptyIcon = styled.div`
  font-size: 4rem;
  margin-bottom: 1rem;
`;

const CartPageWrapper = styled.div`
  max-width: 1000px;
  margin: 0 auto;
  padding: 2rem 1.5rem;
`;

const CartHeader = styled.div`
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 2rem;

  h1 {
    font-size: 1.75rem;
    color: #111827;
  }
`;

const CartLayout = styled.div`
  display: grid;
  grid-template-columns: 1fr 360px;
  gap: 2rem;
  align-items: start;

  @media (max-width: 768px) {
    grid-template-columns: 1fr;
  }
`;

const CartItems = styled.div`
  display: flex;
  flex-direction: column;
  gap: 1rem;
`;

const CartItemCard = styled.div`
  display: flex;
  align-items: center;
  gap: 1rem;
  background: white;
  padding: 1rem;
  border-radius: 12px;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);

  @media (max-width: 768px) {
    flex-wrap: wrap;
  }
`;

const CartItemImage = styled.div`
  font-size: 2.5rem;
  width: 70px;
  height: 70px;
  display: flex;
  align-items: center;
  justify-content: center;
  background: #f3f4f6;
  border-radius: 8px;
`;

const CartItemInfo = styled.div`
  flex: 1;

  h3 {
    font-size: 1rem;
    color: #111827;
  }
`;

const CartItemCategory = styled.p`
  font-size: 0.8rem;
  color: #6b7280;
`;

const CartItemPrice = styled.p`
  font-weight: 600;
  color: #4f46e5;
`;

const CartItemActions = styled.div`
  display: flex;
  align-items: center;
  gap: 1rem;

  @media (max-width: 768px) {
    width: 100%;
    justify-content: space-between;
  }
`;

const QuantityControl = styled.div`
  display: flex;
  align-items: center;
  border: 1px solid #e5e7eb;
  border-radius: 8px;
  overflow: hidden;

  button {
    width: 32px;
    height: 32px;
    border: none;
    background: #f9fafb;
    cursor: pointer;
    font-size: 1rem;
  }

  span {
    width: 36px;
    text-align: center;
    font-weight: 600;
  }
`;

const CartItemTotal = styled.p`
  font-weight: 700;
  color: #111827;
  min-width: 70px;
  text-align: right;
`;

const RemoveButton = styled.button`
  background: none;
  border: none;
  cursor: pointer;
  font-size: 1.2rem;
`;

const CartSummary = styled.div`
  background: white;
  padding: 1.5rem;
  border-radius: 12px;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
  position: sticky;
  top: 80px;

  h2 {
    font-size: 1.25rem;
    color: #111827;
    margin-bottom: 1rem;
  }
`;

const SummaryRow = styled.div<{ $isTotal?: boolean }>`
  display: flex;
  justify-content: space-between;
  padding: 0.5rem 0;
  color: #374151;
  border-top: ${props => props.$isTotal ? '2px solid #e5e7eb' : 'none'};
  margin-top: ${props => props.$isTotal ? '0.5rem' : '0'};
  padding-top: ${props => props.$isTotal ? '1rem' : '0.5rem'};
  font-size: ${props => props.$isTotal ? '1.15rem' : '1rem'};
  font-weight: ${props => props.$isTotal ? '700' : '400'};
  color: ${props => props.$isTotal ? '#111827' : '#374151'};
`;

const CheckoutButton = styled.button`
  width: 100%;
  text-align: center;
  display: inline-block;
  padding: 0.875rem 2rem;
  border-radius: 8px;
  font-weight: 600;
  cursor: pointer;
  border: none;
  transition: all 0.2s;
  font-size: 1.05rem;
  background: #4f46e5;
  color: white;
  margin-top: 1rem;

  &:hover {
    background: #4338ca;
  }
`;

const ContinueLink = styled(Link)`
  display: block;
  text-align: center;
  margin-top: 1rem;
  color: #4f46e5;
  font-weight: 500;
  text-decoration: none;
`;

const ClearButton = styled.button`
  background: transparent;
  color: #374151;
  border: 2px solid #e5e7eb;
  padding: 0.625rem 1.5rem;
  border-radius: 8px;
  font-weight: 600;
  cursor: pointer;
  font-size: 0.95rem;

  &:hover {
    border-color: #4f46e5;
    color: #4f46e5;
  }
`;

const ShopButton = styled(Link)`
  display: inline-block;
  padding: 0.625rem 1.5rem;
  border-radius: 8px;
  font-weight: 600;
  background: #4f46e5;
  color: white;
  text-decoration: none;

  &:hover {
    background: #4338ca;
  }
`;

export default function CartPage() {
  const { items, removeFromCart, updateQuantity, clearCart, totalPrice } = useCart();

  if (items.length === 0) {
    return (
      <CartEmpty>
        <CartEmptyIcon>🛒</CartEmptyIcon>
        <h2>Your cart is empty</h2>
        <p>Looks like you have not added any items to your cart yet.</p>
        <ShopButton href="/">Continue Shopping</ShopButton>
      </CartEmpty>
    );
  }

  return (
    <CartPageWrapper>
      <CartHeader>
        <h1>Shopping Cart</h1>
        <ClearButton onClick={clearCart}>Clear Cart</ClearButton>
      </CartHeader>

      <CartLayout>
        <CartItems>
          {items.map((item) => (
            <CartItemCard key={item.id}>
              <CartItemImage>{item.image}</CartItemImage>
              <CartItemInfo>
                <h3>{item.name}</h3>
                <CartItemCategory>{item.category}</CartItemCategory>
                <CartItemPrice>${item.price.toFixed(2)}</CartItemPrice>
              </CartItemInfo>
              <CartItemActions>
                <QuantityControl>
                  <button onClick={() => updateQuantity(item.id, item.quantity - 1)}>−</button>
                  <span>{item.quantity}</span>
                  <button onClick={() => updateQuantity(item.id, item.quantity + 1)}>+</button>
                </QuantityControl>
                <CartItemTotal>${(item.price * item.quantity).toFixed(2)}</CartItemTotal>
                <RemoveButton onClick={() => removeFromCart(item.id)}>🗑️</RemoveButton>
              </CartItemActions>
            </CartItemCard>
          ))}
        </CartItems>

        <CartSummary>
          <h2>Order Summary</h2>
          <SummaryRow><span>Subtotal</span><span>${totalPrice.toFixed(2)}</span></SummaryRow>
          <SummaryRow><span>Shipping</span><span>{totalPrice > 50 ? 'Free' : '$9.99'}</span></SummaryRow>
          <SummaryRow><span>Tax</span><span>${(totalPrice * 0.08).toFixed(2)}</span></SummaryRow>
          <SummaryRow $isTotal><span>Total</span><span>${(totalPrice + (totalPrice > 50 ? 0 : 9.99) + totalPrice * 0.08).toFixed(2)}</span></SummaryRow>
          <CheckoutButton>Proceed to Checkout</CheckoutButton>
          <ContinueLink href="/">← Continue Shopping</ContinueLink>
        </CartSummary>
      </CartLayout>
    </CartPageWrapper>
  );
}

// templates/overlays/ecommerce/nuxt/pages/cart.vue
<script setup lang="ts">
interface Product {
  id: number;
  name: string;
  price: number;
  image: string;
  category: string;
  description: string;
}

interface CartItem extends Product {
  quantity: number;
}

const cart = useState<CartItem[]>('cart');

const total = computed(() =>
  cart.value.reduce((sum, item) => sum + item.price * item.quantity, 0)
);

function removeItem(id: number) {
  cart.value = cart.value.filter(item => item.id !== id);
}

function updateQuantity(id: number, delta: number) {
  const item = cart.value.find(i => i.id === id);
  if (item) {
    item.quantity += delta;
    if (item.quantity <= 0) {
      removeItem(id);
    }
  }
}
</script>

<template>
  <div class="cart-page">
    <h1 class="cart-title">Shopping Cart</h1>

    <div v-if="cart.length > 0" class="cart-content">
      <div class="cart-items">
        <div v-for="item in cart" :key="item.id" class="cart-item">
          <span class="item-image">{{ item.image }}</span>
          <div class="item-details">
            <h3>{{ item.name }}</h3>
            <p class="item-price">${{ item.price.toFixed(2) }}</p>
          </div>
          <div class="item-quantity">
            <button @click="updateQuantity(item.id, -1)">-</button>
            <span>{{ item.quantity }}</span>
            <button @click="updateQuantity(item.id, 1)">+</button>
          </div>
          <p class="item-subtotal">${{ (item.price * item.quantity).toFixed(2) }}</p>
          <button class="remove-btn" @click="removeItem(item.id)">✕</button>
        </div>
      </div>

      <div class="cart-summary">
        <h2>Order Summary</h2>
        <div class="summary-row">
          <span>Subtotal</span>
          <span>${{ total.toFixed(2) }}</span>
        </div>
        <div class="summary-row">
          <span>Shipping</span>
          <span>Free</span>
        </div>
        <div class="summary-row total">
          <span>Total</span>
          <span>${{ total.toFixed(2) }}</span>
        </div>
        <button class="checkout-btn">Proceed to Checkout</button>
      </div>
    </div>

    <div v-else class="empty-cart">
      <p class="empty-icon">🛒</p>
      <h2>Your cart is empty</h2>
      <p>Start adding some products!</p>
      <NuxtLink to="/" class="continue-btn">Continue Shopping</NuxtLink>
    </div>
  </div>
</template>

<style scoped>
.cart-title {
  font-size: 2rem;
  color: #111827;
  margin-bottom: 2rem;
}

.cart-content {
  display: grid;
  grid-template-columns: 1fr 350px;
  gap: 2rem;
  align-items: start;
}

.cart-items {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.cart-item {
  display: flex;
  align-items: center;
  gap: 1rem;
  background: white;
  padding: 1.25rem;
  border-radius: 10px;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
}

.item-image {
  font-size: 2.5rem;
}

.item-details {
  flex: 1;
}

.item-details h3 {
  color: #111827;
  font-size: 1rem;
  margin-bottom: 0.25rem;
}

.item-price {
  color: #6b7280;
  font-size: 0.9rem;
}

.item-quantity {
  display: flex;
  align-items: center;
  border: 1px solid #d1d5db;
  border-radius: 6px;
  overflow: hidden;
}

.item-quantity button {
  background: #f3f4f6;
  border: none;
  padding: 0.35rem 0.75rem;
  cursor: pointer;
  font-size: 0.9rem;
}

.item-quantity button:hover {
  background: #e5e7eb;
}

.item-quantity span {
  padding: 0.35rem 0.75rem;
  font-weight: 600;
  font-size: 0.9rem;
}

.item-subtotal {
  font-weight: 700;
  color: #111827;
  min-width: 70px;
  text-align: right;
}

.remove-btn {
  background: none;
  border: none;
  color: #9ca3af;
  cursor: pointer;
  font-size: 1.1rem;
  padding: 0.25rem;
}

.remove-btn:hover {
  color: #ef4444;
}

.cart-summary {
  background: white;
  padding: 1.5rem;
  border-radius: 10px;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
}

.cart-summary h2 {
  font-size: 1.25rem;
  color: #111827;
  margin-bottom: 1.25rem;
  padding-bottom: 0.75rem;
  border-bottom: 1px solid #e5e7eb;
}

.summary-row {
  display: flex;
  justify-content: space-between;
  padding: 0.5rem 0;
  color: #6b7280;
}

.summary-row.total {
  font-weight: 700;
  font-size: 1.2rem;
  color: #111827;
  border-top: 1px solid #e5e7eb;
  margin-top: 0.75rem;
  padding-top: 1rem;
}

.checkout-btn {
  width: 100%;
  background: #4f46e5;
  color: white;
  border: none;
  padding: 0.875rem;
  border-radius: 8px;
  font-size: 1rem;
  font-weight: 600;
  cursor: pointer;
  margin-top: 1.25rem;
  transition: background 0.2s;
}

.checkout-btn:hover {
  background: #4338ca;
}

.empty-cart {
  text-align: center;
  padding: 4rem 0;
}

.empty-icon {
  font-size: 4rem;
  margin-bottom: 1rem;
}

.empty-cart h2 {
  color: #111827;
  margin-bottom: 0.5rem;
}

.empty-cart p {
  color: #6b7280;
  margin-bottom: 1.5rem;
}

.continue-btn {
  display: inline-block;
  background: #4f46e5;
  color: white;
  padding: 0.75rem 1.5rem;
  border-radius: 8px;
  font-weight: 600;
  transition: background 0.2s;
}

.continue-btn:hover {
  background: #4338ca;
}

@media (max-width: 768px) {
  .cart-content {
    grid-template-columns: 1fr;
  }
}
</style>
