// templates/overlays/portfolio/angular/src/app/pages/projects.component.ts
import { Component } from '@angular/core';
import { ProjectCardComponent, Project } from '../components/project-card.component';

@Component({
  selector: 'app-projects',
  standalone: true,
  imports: [ProjectCardComponent],
  template: `
    <div class="projects-container">
      <h1 class="projects-page-title">Projects</h1>
      <div class="projects-filter-bar">
        @for (cat of categories; track cat) {
          <button
            class="projects-filter-btn"
            [class.active]="active === cat"
            (click)="active = cat"
          >{{ cat }}</button>
        }
      </div>
      <div class="projects-grid">
        @for (p of filtered; track p.id) {
          <app-project-card [project]="p" />
        }
      </div>
    </div>
  `,
  styles: [`
    .projects-container {
      max-width: 1100px;
      margin: 0 auto;
      padding: 48px 24px;
    }

    .projects-page-title {
      font-size: 32px;
      font-weight: 800;
      color: #111827;
      margin-bottom: 24px;
      text-align: center;
    }

    .projects-filter-bar {
      display: flex;
      gap: 10px;
      justify-content: center;
      margin-bottom: 32px;
    }

    .projects-filter-btn {
      padding: 8px 18px;
      border: 1px solid #d1d5db;
      border-radius: 8px;
      background: #fff;
      font-size: 14px;
      color: #374151;
      cursor: pointer;
      transition: all 0.2s;
    }

    .projects-filter-btn:hover {
      border-color: #4f46e5;
      color: #4f46e5;
    }

    .projects-filter-btn.active {
      background: #4f46e5;
      color: #fff;
      border-color: #4f46e5;
    }

    .projects-grid {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 24px;
    }

    @media (max-width: 768px) {
      .projects-filter-bar {
        flex-wrap: wrap;
      }

      .projects-grid {
        grid-template-columns: 1fr;
        gap: 16px;
      }
    }
  `]
})
export class ProjectsComponent {
  active = 'All';

  categories: string[] = ['All', 'Web App', 'Dashboard', 'Tool'];

  projects: Project[] = [
    {
      id: 1,
      title: 'E-Commerce Platform',
      description: 'Full-stack online store with payments',
      image: '🛒',
      tags: ['Angular', 'Node.js', 'MongoDB'],
      category: 'Web App',
    },
    {
      id: 2,
      title: 'Task Manager',
      description: 'Collaborative project management tool',
      image: '📋',
      tags: ['React', 'Firebase', 'TypeScript'],
      category: 'Web App',
    },
    {
      id: 3,
      title: 'Weather Dashboard',
      description: 'Real-time weather visualization',
      image: '🌤️',
      tags: ['Vue', 'D3.js', 'API'],
      category: 'Dashboard',
    },
    {
      id: 4,
      title: 'Chat Application',
      description: 'Real-time messaging with WebSockets',
      image: '💬',
      tags: ['React', 'Socket.io', 'Express'],
      category: 'Web App',
    },
    {
      id: 5,
      title: 'Portfolio Generator',
      description: 'CLI tool for generating portfolios',
      image: '🛠️',
      tags: ['Node.js', 'TypeScript', 'CLI'],
      category: 'Tool',
    },
    {
      id: 6,
      title: 'Analytics Dashboard',
      description: 'Business intelligence dashboard',
      image: '📊',
      tags: ['Angular', 'D3.js', 'PostgreSQL'],
      category: 'Dashboard',
    },
  ];

  get filtered(): Project[] {
    return this.active === 'All'
      ? this.projects
      : this.projects.filter((p) => p.category === this.active);
  }
}

// templates/overlays/portfolio/nuxt/pages/projects.vue
<script setup lang="ts">
const projects = [
  { id: 1, title: 'E-Commerce Platform', description: 'A full-featured online store with cart, checkout, and payment integration.', image: '🛒', tags: ['Vue.js', 'Node.js', 'PostgreSQL'], link: '#' },
  { id: 2, title: 'Task Management App', description: 'Collaborative project management tool with real-time updates and team features.', image: '📋', tags: ['React', 'TypeScript', 'Firebase'], link: '#' },
  { id: 3, title: 'Analytics Dashboard', description: 'Data visualization platform with interactive charts and real-time metrics.', image: '📊', tags: ['Vue.js', 'D3.js', 'Python'], link: '#' },
  { id: 4, title: 'Social Media App', description: 'Mobile-first social platform with real-time messaging and content sharing.', image: '💬', tags: ['React Native', 'GraphQL', 'MongoDB'], link: '#' },
  { id: 5, title: 'Weather Dashboard', description: 'Real-time weather tracking with location-based forecasts and alerts.', image: '🌤️', tags: ['Vue.js', 'API', 'Chart.js'], link: '#' },
  { id: 6, title: 'Portfolio Generator', description: 'CLI tool that generates beautiful portfolio websites from configuration files.', image: '🎯', tags: ['Node.js', 'TypeScript', 'CLI'], link: '#' },
];

const selectedTag = ref('All');

const allTags = computed(() => {
  const tags = new Set<string>();
  projects.forEach(p => p.tags.forEach(t => tags.add(t)));
  return ['All', ...Array.from(tags)];
});

const filteredProjects = computed(() => {
  if (selectedTag.value === 'All') return projects;
  return projects.filter(p => p.tags.includes(selectedTag.value));
});
</script>

<template>
  <div class="projects-page">
    <div class="page-inner">
      <div class="page-header">
        <h1>Projects</h1>
        <p class="subtitle">A collection of my recent work and side projects.</p>
      </div>

      <div class="filter-bar">
        <button
          v-for="tag in allTags"
          :key="tag"
          :class="['filter-btn', { active: selectedTag === tag }]"
          @click="selectedTag = tag"
        >
          {{ tag }}
        </button>
      </div>

      <div class="projects-grid">
        <ProjectCard
          v-for="project in filteredProjects"
          :key="project.id"
          :project="project"
        />
      </div>
    </div>
  </div>
</template>

<style scoped>
.projects-page {
  padding: 2rem 1.5rem;
}

.page-inner {
  max-width: 1200px;
  margin: 0 auto;
}

.page-header {
  text-align: center;
  margin-bottom: 2rem;
}

.page-header h1 {
  font-size: 2rem;
  color: #111827;
  margin-bottom: 0.5rem;
}

.subtitle {
  color: #6b7280;
  font-size: 1.1rem;
}

.filter-bar {
  display: flex;
  justify-content: center;
  flex-wrap: wrap;
  gap: 0.5rem;
  margin-bottom: 2rem;
}

.filter-btn {
  padding: 0.5rem 1rem;
  border: 1px solid #d1d5db;
  border-radius: 20px;
  background: white;
  cursor: pointer;
  font-size: 0.85rem;
  font-weight: 500;
  transition: all 0.2s;
}

.filter-btn:hover {
  border-color: #4f46e5;
  color: #4f46e5;
}

.filter-btn.active {
  background: #4f46e5;
  color: white;
  border-color: #4f46e5;
}

.projects-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(320px, 1fr));
  gap: 1.5rem;
}
</style>
