// templates/overlays/portfolio/vue/src/components/ProjectCard.vue
<script setup lang="ts">
import type { Project } from '../data'

defineProps<{ project: Project }>()
</script>

<template>
  <div class="project-card">
    <div class="card-image">{{ project.image }}</div>
    <div class="card-body">
      <div class="card-title">{{ project.title }}</div>
      <div class="card-desc">{{ project.description }}</div>
      <div class="card-tags">
        <span v-for="tag in project.tags" :key="tag">{{ tag }}</span>
      </div>
    </div>
  </div>
</template>

// templates/styling/ant-design/overlays/portfolio/react/src/components/ProjectCard.tsx
import { Card, Tag, Typography, Space } from 'antd';
import type { Project } from '../data/projects';

const { Title, Paragraph } = Typography;

interface ProjectCardProps {
  project: Project;
}

function ProjectCard({ project }: ProjectCardProps) {
  return (
    <Card hoverable>
      <div style={{ fontSize: 48, textAlign: 'center', marginBottom: 16 }}>{project.image}</div>
      <Title level={4} style={{ marginBottom: 8 }}>{project.title}</Title>
      <Paragraph type="secondary">{project.description}</Paragraph>
      <Space wrap>
        {project.tags.map((tag, j) => (
          <Tag key={j} color="blue">{tag}</Tag>
        ))}
      </Space>
    </Card>
  );
}

export default ProjectCard;
