// templates/styling/chakra-ui/overlays/landing/react/src/components/Footer.tsx
import { Box, Flex, Heading, Text, Link, VStack, HStack } from '@chakra-ui/react';

export function Footer() {
  return (
    <Box as="footer" bg="gray.900" color="gray.400" pt={16} pb={8} px={8}>
      <Flex maxW="1200px" mx="auto" justify="space-between" gap={16} flexWrap="wrap">
        <Box>
          <Heading as="h3" size="lg" color="white" mb={2}>
            {'{{projectName}}'}
          </Heading>
          <Text maxW="300px" lineHeight={1.6}>
            Building the future of the web, one project at a time.
          </Text>
        </Box>
        <HStack gap={16} align="flex-start" flexWrap="wrap">
          <VStack align="flex-start" gap={2}>
            <Heading as="h4" size="xs" color="white" textTransform="uppercase" letterSpacing="0.05em" mb={2}>
              Product
            </Heading>
            <Link href="#features" color="gray.400" _hover={{ color: 'white' }} textDecoration="none" fontSize="0.9rem">Features</Link>
            <Link href="#cta" color="gray.400" _hover={{ color: 'white' }} textDecoration="none" fontSize="0.9rem">Pricing</Link>
            <Link href="#" color="gray.400" _hover={{ color: 'white' }} textDecoration="none" fontSize="0.9rem">Documentation</Link>
          </VStack>
          <VStack align="flex-start" gap={2}>
            <Heading as="h4" size="xs" color="white" textTransform="uppercase" letterSpacing="0.05em" mb={2}>
              Company
            </Heading>
            <Link href="#" color="gray.400" _hover={{ color: 'white' }} textDecoration="none" fontSize="0.9rem">About</Link>
            <Link href="#" color="gray.400" _hover={{ color: 'white' }} textDecoration="none" fontSize="0.9rem">Blog</Link>
            <Link href="#contact" color="gray.400" _hover={{ color: 'white' }} textDecoration="none" fontSize="0.9rem">Contact</Link>
          </VStack>
          <VStack align="flex-start" gap={2}>
            <Heading as="h4" size="xs" color="white" textTransform="uppercase" letterSpacing="0.05em" mb={2}>
              Legal
            </Heading>
            <Link href="#" color="gray.400" _hover={{ color: 'white' }} textDecoration="none" fontSize="0.9rem">Privacy Policy</Link>
            <Link href="#" color="gray.400" _hover={{ color: 'white' }} textDecoration="none" fontSize="0.9rem">Terms of Service</Link>
          </VStack>
        </HStack>
      </Flex>
      <Box borderTop="1px solid" borderColor="gray.700" mt={12} pt={6} textAlign="center" maxW="1200px" mx="auto">
        <Text fontSize="sm" color="gray.500">
          &copy; 2025 {'{{projectName}}'}. All rights reserved.
        </Text>
      </Box>
    </Box>
  );
}

// templates/overlays/landing/angular/src/app/components/footer.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-footer',
  standalone: true,
  template: `
    <footer class="footer">
      <div class="footer-content">
        <div class="brand">
          <h3>{{projectName}}</h3>
          <p>Building the future of the web.</p>
        </div>
        <div class="links">
          <div class="col">
            <h4>Product</h4>
            <a href="#features">Features</a>
            <a href="#cta">Pricing</a>
          </div>
          <div class="col">
            <h4>Company</h4>
            <a href="#">About</a>
            <a href="#">Blog</a>
          </div>
        </div>
      </div>
      <div class="bottom">
        <p>&copy; 2025 {{projectName}}. All rights reserved.</p>
      </div>
    </footer>
  `,
  styles: [`
    .footer { background: #111827; color: #d1d5db; padding: 4rem 2rem 2rem; }
    .footer-content { display: flex; justify-content: space-between; max-width: 1200px; margin: 0 auto; gap: 4rem; flex-wrap: wrap; }
    .brand h3 { color: white; font-size: 1.5rem; margin-bottom: 0.5rem; }
    .brand p { max-width: 300px; }
    .links { display: flex; gap: 4rem; }
    .col { display: flex; flex-direction: column; gap: 0.5rem; }
    .col h4 { color: white; font-size: 0.875rem; text-transform: uppercase; margin-bottom: 0.5rem; }
    .col a { color: #9ca3af; text-decoration: none; }
    .col a:hover { color: white; }
    .bottom { border-top: 1px solid #374151; margin-top: 3rem; padding-top: 1.5rem; text-align: center; }
    .bottom p { font-size: 0.875rem; color: #6b7280; }
  `]
})
export class FooterComponent {}
