// templates/styling/styled-components/overlays/landing/nextjs/src/app/components/Footer.tsx
'use client';

import styled from 'styled-components';

const StyledFooter = styled.footer`
  background: #111827;
  color: #d1d5db;
  padding: 4rem 2rem 2rem;
`;

const FooterContent = styled.div`
  display: flex;
  justify-content: space-between;
  max-width: 1200px;
  margin: 0 auto;
  gap: 4rem;
  flex-wrap: wrap;
`;

const FooterBrand = styled.div`
  h3 {
    color: white;
    font-size: 1.5rem;
    margin-bottom: 0.5rem;
  }
`;

const FooterLinks = styled.div`
  display: flex;
  gap: 4rem;
`;

const FooterCol = styled.div`
  display: flex;
  flex-direction: column;
  gap: 0.5rem;

  h4 {
    color: white;
    font-size: 0.875rem;
    text-transform: uppercase;
    margin-bottom: 0.5rem;
  }

  a {
    color: #9ca3af;
    text-decoration: none;

    &:hover {
      color: white;
    }
  }
`;

const FooterBottom = styled.div`
  border-top: 1px solid #374151;
  margin-top: 3rem;
  padding-top: 1.5rem;
  text-align: center;

  p {
    font-size: 0.875rem;
    color: #6b7280;
  }
`;

export function Footer() {
  return (
    <StyledFooter>
      <FooterContent>
        <FooterBrand>
          <h3>{'{{projectName}}'}</h3>
          <p>Building the future of the web.</p>
        </FooterBrand>
        <FooterLinks>
          <FooterCol>
            <h4>Product</h4>
            <a href="#features">Features</a>
            <a href="#cta">Pricing</a>
          </FooterCol>
          <FooterCol>
            <h4>Company</h4>
            <a href="#">About</a>
            <a href="#">Blog</a>
          </FooterCol>
        </FooterLinks>
      </FooterContent>
      <FooterBottom>
        <p>&copy; 2025 {'{{projectName}}'}. All rights reserved.</p>
      </FooterBottom>
    </StyledFooter>
  );
}

// templates/overlays/landing/angular/src/app/components/footer.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-footer',
  standalone: true,
  template: `
    <footer class="footer">
      <div class="footer-content">
        <div class="brand">
          <h3>{{projectName}}</h3>
          <p>Building the future of the web.</p>
        </div>
        <div class="links">
          <div class="col">
            <h4>Product</h4>
            <a href="#features">Features</a>
            <a href="#cta">Pricing</a>
          </div>
          <div class="col">
            <h4>Company</h4>
            <a href="#">About</a>
            <a href="#">Blog</a>
          </div>
        </div>
      </div>
      <div class="bottom">
        <p>&copy; 2025 {{projectName}}. All rights reserved.</p>
      </div>
    </footer>
  `,
  styles: [`
    .footer { background: #111827; color: #d1d5db; padding: 4rem 2rem 2rem; }
    .footer-content { display: flex; justify-content: space-between; max-width: 1200px; margin: 0 auto; gap: 4rem; flex-wrap: wrap; }
    .brand h3 { color: white; font-size: 1.5rem; margin-bottom: 0.5rem; }
    .brand p { max-width: 300px; }
    .links { display: flex; gap: 4rem; }
    .col { display: flex; flex-direction: column; gap: 0.5rem; }
    .col h4 { color: white; font-size: 0.875rem; text-transform: uppercase; margin-bottom: 0.5rem; }
    .col a { color: #9ca3af; text-decoration: none; }
    .col a:hover { color: white; }
    .bottom { border-top: 1px solid #374151; margin-top: 3rem; padding-top: 1.5rem; text-align: center; }
    .bottom p { font-size: 0.875rem; color: #6b7280; }
  `]
})
export class FooterComponent {}
