// templates/styling/css-modules/overlays/blog/vue/src/components/BlogHeader.vue
<script setup lang="ts">
import { useRoute } from 'vue-router';
import { useCssModule } from 'vue';

const route = useRoute();
const style = useCssModule();

function navLinkClass(path: string) {
  return route.path === path
    ? [style.navLink, style.navLinkActive]
    : [style.navLink];
}
</script>

<template>
  <div :class="$style.blogHeaderWrap">
    <header :class="$style.blogHeader">
      <RouterLink to="/" :class="$style.logo" style="text-decoration: none;">{{projectName}}</RouterLink>
      <nav :class="$style.nav">
        <RouterLink to="/" :class="navLinkClass('/')">Home</RouterLink>
        <RouterLink to="/about" :class="navLinkClass('/about')">About</RouterLink>
      </nav>
    </header>
  </div>
</template>

<style module>
.blogHeaderWrap {
  background: #fff;
  border-bottom: 1px solid #e5e7eb;
}

.blogHeader {
  background: #fff;
  padding: 1rem 2rem;
  display: flex;
  align-items: center;
  justify-content: space-between;
  max-width: 1100px;
  width: 100%;
  margin: 0 auto;
}

.logo {
  font-size: 1.35rem;
  font-weight: 700;
  color: #111827;
}

.nav {
  display: flex;
  gap: 1.5rem;
}

.navLink {
  color: #6b7280;
  font-weight: 500;
  font-size: 0.95rem;
  text-decoration: none;
}

.navLink:hover {
  color: #4f46e5;
  text-decoration: none;
}

.navLinkActive {
  color: #4f46e5;
}
</style>

// templates/styling/chakra-ui/overlays/blog/react/src/components/BlogHeader.tsx
import { NavLink } from 'react-router-dom';
import { Box, Flex, Heading, HStack } from '@chakra-ui/react';

function BlogHeader() {
  return (
    <Box as="header" borderBottom="1px solid" borderColor="gray.200">
      <Flex maxW="1100px" mx="auto" px={8} py={5} justify="space-between" align="center">
        <Heading as={NavLink} to="/" size="lg" color="gray.900" textDecoration="none">
          {'{{projectName}}'}
        </Heading>
        <HStack as="nav" gap={6}>
          <Box
            as={NavLink}
            to="/"
            end
            color="gray.500"
            fontWeight={500}
            textDecoration="none"
            _hover={{ color: '#4f46e5' }}
            css={{ '&.active': { color: '#4f46e5' } }}
          >
            Home
          </Box>
          <Box
            as={NavLink}
            to="/about"
            color="gray.500"
            fontWeight={500}
            textDecoration="none"
            _hover={{ color: '#4f46e5' }}
            css={{ '&.active': { color: '#4f46e5' } }}
          >
            About
          </Box>
        </HStack>
      </Flex>
    </Box>
  );
}

export default BlogHeader;
