// templates/overlays/dashboard/nextjs/src/app/components/KPICards.tsx
interface KPI {
  title: string;
  value: string;
  change: string;
  trend: 'up' | 'down';
  icon: string;
}

const kpis: KPI[] = [
  { title: 'Total Revenue', value: '$48,250', change: '+12.5%', trend: 'up', icon: '💰' },
  { title: 'Active Users', value: '2,340', change: '+8.1%', trend: 'up', icon: '👥' },
  { title: 'Orders', value: '1,120', change: '+23.4%', trend: 'up', icon: '📦' },
  { title: 'Conversion Rate', value: '3.2%', change: '-1.8%', trend: 'down', icon: '📈' },
];

export function KPICards() {
  return (
    <div className="kpi-grid">
      {kpis.map((kpi) => (
        <div key={kpi.title} className="kpi-card">
          <div className="kpi-header">
            <span className="kpi-icon">{kpi.icon}</span>
            <span className={`kpi-change ${kpi.trend}`}>{kpi.change}</span>
          </div>
          <p className="kpi-value">{kpi.value}</p>
          <p className="kpi-title">{kpi.title}</p>
        </div>
      ))}
    </div>
  );
}

// templates/overlays/dashboard/vue/src/components/KPICards.vue
<script setup lang="ts">
const kpis = [
  { label: 'Total Revenue', value: '$48,250', change: '+12%', positive: true },
  { label: 'Active Users', value: '2,420', change: '+8%', positive: true },
  { label: 'Orders', value: '1,210', change: '-3%', positive: false },
  { label: 'Conversion', value: '3.2%', change: '+0.5%', positive: true },
];
</script>

<template>
  <div class="kpi-grid">
    <div v-for="kpi in kpis" :key="kpi.label" class="kpi-card">
      <p class="kpi-label">{{ kpi.label }}</p>
      <p class="kpi-value">{{ kpi.value }}</p>
      <p :class="['kpi-change', kpi.positive ? 'positive' : 'negative']">{{ kpi.change }}</p>
    </div>
  </div>
</template>
