// templates/styling/tailwind/overlays/blog/react/src/components/PostCard.tsx
import { Link } from 'react-router-dom';
import type { Post } from '../data/posts';

interface PostCardProps {
  post: Post;
}

function PostCard({ post }: PostCardProps) {
  return (
    <article className="flex flex-col sm:flex-row gap-6 py-6 border-b border-gray-100">
      <div className="text-5xl w-20 text-center shrink-0">{post.image}</div>
      <div className="flex-1">
        <Link
          to={`/category/${post.category.toLowerCase()}`}
          className="text-xs text-indigo-600 font-semibold uppercase tracking-wide no-underline hover:text-indigo-700"
        >
          {post.category}
        </Link>
        <Link to={`/post/${post.id}`} className="no-underline group">
          <h2 className="text-xl font-bold text-gray-900 mt-1 mb-2 group-hover:text-indigo-600">
            {post.title}
          </h2>
        </Link>
        <p className="text-gray-500 leading-relaxed mb-3">{post.excerpt}</p>
        <div className="flex gap-4 text-sm text-gray-400">
          <span>By {post.author}</span>
          <span>{post.date}</span>
          <span>{post.readTime} read</span>
        </div>
      </div>
    </article>
  );
}

export default PostCard;

// templates/styling/tailwind/overlays/blog/vue/src/components/PostCard.vue
<script setup lang="ts">
import type { Post } from '../data'

defineProps<{ post: Post }>()
</script>

<template>
  <RouterLink :to="`/post/${post.id}`" class="bg-white rounded-lg overflow-hidden shadow-sm flex transition-shadow hover:shadow-md no-underline text-inherit">
    <div class="w-44 min-h-[140px] bg-indigo-50 flex items-center justify-center text-5xl shrink-0">{{ post.image }}</div>
    <div class="p-5 flex-1">
      <div class="text-xs font-semibold text-indigo-600 uppercase tracking-wider">{{ post.category }}</div>
      <div class="text-lg font-bold text-gray-900 mt-1 mb-1.5">{{ post.title }}</div>
      <div class="text-sm text-gray-500 leading-relaxed">{{ post.excerpt }}</div>
      <div class="mt-3 text-xs text-gray-400">{{ post.author }} &middot; {{ post.date }} &middot; {{ post.readTime }}</div>
    </div>
  </RouterLink>
</template>
