// templates/overlays/portfolio/vue/src/pages/Projects.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import ProjectCard from '../components/ProjectCard.vue'
import { projects } from '../data'

const activeFilter = ref('All')

const categories = ['All', ...new Set(projects.map(p => p.category))]

const filtered = computed(() =>
  activeFilter.value === 'All'
    ? projects
    : projects.filter(p => p.category === activeFilter.value)
)
</script>

<template>
  <section class="section">
    <h2 class="section-title">All Projects</h2>
    <div class="filter-buttons">
      <button
        v-for="cat in categories"
        :key="cat"
        class="filter-btn"
        :class="{ active: activeFilter === cat }"
        @click="activeFilter = cat"
      >{{ cat }}</button>
    </div>
    <div class="projects-grid">
      <ProjectCard v-for="project in filtered" :key="project.id" :project="project" />
    </div>
  </section>
</template>

// templates/styling/css-modules/overlays/portfolio/react/src/pages/Projects.tsx
import { useState } from 'react';
import ProjectCard from '../components/ProjectCard';
import { projects } from '../data/projects';
import styles from './Projects.module.css';

const allCategories = ['All', ...Array.from(new Set(projects.map((p) => p.category)))];

function Projects() {
  const [active, setActive] = useState('All');

  const filtered = active === 'All' ? projects : projects.filter((p) => p.category === active);

  return (
    <section className={styles.projectsSection}>
      <h2>All Projects</h2>
      <p className={styles.sectionSubtitle}>Browse my complete portfolio</p>
      <div className={styles.filterBar}>
        {allCategories.map((cat) => (
          <button
            key={cat}
            className={active === cat ? styles.filterBtnActive : styles.filterBtn}
            onClick={() => setActive(cat)}
          >
            {cat}
          </button>
        ))}
      </div>
      <div className={styles.projectsGrid}>
        {filtered.map((project) => (
          <ProjectCard key={project.id} project={project} />
        ))}
      </div>
    </section>
  );
}

export default Projects;
