// templates/styling/tailwind/overlays/blog/vue/src/components/BlogHeader.vue
<script setup lang="ts">
</script>

<template>
  <div class="bg-white border-b border-gray-200">
    <header class="max-w-5xl w-full mx-auto px-8 py-4 flex items-center justify-between">
      <RouterLink to="/" class="text-xl font-bold text-gray-900 no-underline">{{projectName}}</RouterLink>
      <nav class="flex gap-6">
        <RouterLink to="/" class="text-gray-500 font-medium text-sm no-underline transition-colors hover:text-indigo-600 [&.router-link-exact-active]:text-indigo-600">Home</RouterLink>
        <RouterLink to="/about" class="text-gray-500 font-medium text-sm no-underline transition-colors hover:text-indigo-600 [&.router-link-exact-active]:text-indigo-600">About</RouterLink>
      </nav>
    </header>
  </div>
</template>

// templates/styling/tailwind/overlays/blog/react/src/components/BlogHeader.tsx
import { NavLink } from 'react-router-dom';

function BlogHeader() {
  return (
    <header className="border-b border-gray-200">
      <div className="max-w-5xl mx-auto px-4 sm:px-8 py-5 flex flex-col sm:flex-row justify-between items-center gap-3 sm:gap-0">
        <NavLink to="/" className="text-2xl font-bold text-gray-900 no-underline">
          {'{{projectName}}'}
        </NavLink>
        <nav className="flex gap-6">
          <NavLink
            to="/"
            end
            className={({ isActive }) =>
              `no-underline font-medium transition-colors duration-150 ${
                isActive ? 'text-indigo-600' : 'text-gray-500 hover:text-indigo-600'
              }`
            }
          >
            Home
          </NavLink>
          <NavLink
            to="/about"
            className={({ isActive }) =>
              `no-underline font-medium transition-colors duration-150 ${
                isActive ? 'text-indigo-600' : 'text-gray-500 hover:text-indigo-600'
              }`
            }
          >
            About
          </NavLink>
        </nav>
      </div>
    </header>
  );
}

export default BlogHeader;
