// templates/styling/tailwind/overlays/dashboard/react/src/components/KPICards.tsx
const kpis = [
  { label: 'Total Revenue', value: '$48,250', change: '+12%', positive: true },
  { label: 'Active Users', value: '2,420', change: '+8%', positive: true },
  { label: 'Orders', value: '1,210', change: '-3%', positive: false },
  { label: 'Conversion', value: '3.2%', change: '+0.5%', positive: true },
];

export function KPICards() {
  return (
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 lg:gap-6 mb-6 lg:mb-8">
      {kpis.map((kpi, i) => (
        <div key={i} className="bg-white rounded-xl p-4 lg:p-6 border border-gray-200">
          <span className="text-sm text-gray-500 font-medium">{kpi.label}</span>
          <div className="text-2xl lg:text-3xl font-bold mt-1 text-gray-900">{kpi.value}</div>
          <span className={`text-xs ${kpi.positive ? 'text-emerald-500' : 'text-red-500'}`}>
            {kpi.change} from last month
          </span>
        </div>
      ))}
    </div>
  );
}

// templates/styling/tailwind/overlays/dashboard/nuxt/components/KPICards.vue
<script setup lang="ts">
const kpis = [
  { label: 'Total Revenue', value: '$54,230', change: '+12.5%', icon: '💰', positive: true },
  { label: 'Active Users', value: '2,345', change: '+8.1%', icon: '👥', positive: true },
  { label: 'Orders', value: '1,247', change: '+23.4%', icon: '📦', positive: true },
  { label: 'Conversion', value: '3.24%', change: '-0.8%', icon: '📈', positive: false },
];
</script>

<template>
  <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5 mb-8">
    <div v-for="kpi in kpis" :key="kpi.label" class="bg-white rounded-lg p-6 shadow-sm">
      <div class="flex justify-between items-center mb-3">
        <span class="text-sm text-gray-500 font-medium">{{ kpi.label }}</span>
        <span class="text-2xl">{{ kpi.icon }}</span>
      </div>
      <p class="text-2xl font-bold text-gray-900 mb-1">{{ kpi.value }}</p>
      <p :class="['text-xs font-medium', kpi.positive ? 'text-emerald-500' : 'text-red-500']">
        {{ kpi.change }} from last month
      </p>
    </div>
  </div>
</template>
