// templates/styling/chakra-ui/overlays/crm/react/src/components/StatsCards.tsx
import { SimpleGrid, Box, Text } from '@chakra-ui/react';
import { contacts } from '../data/contacts';

const stats = [
  { label: 'Total Contacts', value: contacts.length, color: '#4f46e5' },
  { label: 'Leads', value: contacts.filter((c) => c.status === 'Lead').length, color: '#f59e0b' },
  { label: 'Customers', value: contacts.filter((c) => c.status === 'Customer').length, color: '#10b981' },
  { label: 'Churned', value: contacts.filter((c) => c.status === 'Churned').length, color: '#ef4444' },
];

function StatsCards() {
  return (
    <SimpleGrid columns={{ base: 2, md: 4 }} gap={4} mb={6}>
      {stats.map((stat, i) => (
        <Box key={i} bg="white" borderRadius="xl" p={5} border="1px solid" borderColor="gray.200" position="relative" overflow="hidden">
          <Box position="absolute" top={0} left={0} w="4px" h="100%" bg={stat.color} />
          <Text fontSize="0.8rem" color="gray.500">{stat.label}</Text>
          <Text fontSize="1.75rem" fontWeight={700} color="gray.900">{stat.value}</Text>
        </Box>
      ))}
    </SimpleGrid>
  );
}

export default StatsCards;

// templates/styling/tailwind/overlays/crm/vue/src/components/StatsCards.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { Contact } from '../data'

const props = defineProps<{ contacts: Contact[] }>()

const stats = computed(() => [
  { icon: '\u{1F465}', label: 'Total', value: props.contacts.length },
  { icon: '\u{1F535}', label: 'Leads', value: props.contacts.filter(c => c.status === 'Lead').length },
  { icon: '\u{1F7E2}', label: 'Customers', value: props.contacts.filter(c => c.status === 'Customer').length },
  { icon: '\u{1F534}', label: 'Churned', value: props.contacts.filter(c => c.status === 'Churned').length },
])
</script>

<template>
  <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
    <div v-for="stat in stats" :key="stat.label" class="bg-white rounded-lg p-5 shadow-sm">
      <div class="text-2xl mb-2">{{ stat.icon }}</div>
      <div class="text-xs text-gray-500 uppercase tracking-wider">{{ stat.label }}</div>
      <div class="text-3xl font-bold text-gray-900 mt-1">{{ stat.value }}</div>
    </div>
  </div>
</template>
