// templates/styling/tailwind/overlays/crm/angular/src/app/components/stats-cards.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-stats-cards',
  standalone: true,
  template: `
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
      @for (stat of stats; track stat.label) {
        <div class="bg-white rounded-xl p-5 flex items-center gap-4 shadow-sm">
          <span class="text-3xl">{{ stat.icon }}</span>
          <div class="flex flex-col">
            <span class="text-2xl font-bold text-gray-900">{{ stat.value }}</span>
            <span class="text-sm text-gray-500">{{ stat.label }}</span>
          </div>
        </div>
      }
    </div>
  `,
  styles: []
})
export class StatsCardsComponent {
  stats = [
    { icon: '👥', value: '2,847', label: 'Total Contacts' },
    { icon: '🎯', value: '643', label: 'Leads' },
    { icon: '✅', value: '1,924', label: 'Customers' },
    { icon: '📉', value: '280', label: 'Churned' },
  ];
}

// templates/styling/tailwind/overlays/crm/nuxt/components/StatsCards.vue
<script setup lang="ts">
const stats = [
  { label: 'Total Contacts', value: '1,284', icon: '👥', color: '#4f46e5' },
  { label: 'Active Deals', value: '42', icon: '💼', color: '#10b981' },
  { label: 'Revenue', value: '$128,400', icon: '💰', color: '#f59e0b' },
  { label: 'Conversion Rate', value: '24.8%', icon: '📈', color: '#ef4444' },
];
</script>

<template>
  <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5 mb-8">
    <div v-for="stat in stats" :key="stat.label" class="bg-white rounded-lg p-6 shadow-sm flex items-center gap-4">
      <div
        class="w-12 h-12 rounded-lg flex items-center justify-center text-xl shrink-0"
        :style="{ backgroundColor: stat.color + '15', color: stat.color }"
      >
        {{ stat.icon }}
      </div>
      <div>
        <p class="text-xl font-bold text-gray-900">{{ stat.value }}</p>
        <p class="text-sm text-gray-500">{{ stat.label }}</p>
      </div>
    </div>
  </div>
</template>
