// templates/styling/tailwind/overlays/portfolio/nuxt/components/PortfolioFooter.vue
<template>
  <footer class="bg-gray-900 text-gray-400 py-8 px-6 mt-auto">
    <div class="max-w-7xl mx-auto flex items-center justify-between">
      <p class="text-sm">&copy; 2024 {{projectName}}. All rights reserved.</p>
      <div class="flex gap-5">
        <NuxtLink to="/" class="text-gray-400 text-sm hover:text-white transition-colors">Home</NuxtLink>
        <NuxtLink to="/projects" class="text-gray-400 text-sm hover:text-white transition-colors">Projects</NuxtLink>
        <NuxtLink to="/about" class="text-gray-400 text-sm hover:text-white transition-colors">About</NuxtLink>
        <NuxtLink to="/contact" class="text-gray-400 text-sm hover:text-white transition-colors">Contact</NuxtLink>
      </div>
    </div>
  </footer>
</template>

// templates/styling/tailwind/overlays/portfolio/react/src/components/PortfolioFooter.tsx
function PortfolioFooter() {
  return (
    <footer className="bg-gray-900 text-gray-400 py-8 px-8 text-center mt-auto">
      <div className="max-w-[1100px] mx-auto">
        <div className="flex gap-8 justify-center mb-4">
          <a href="#" target="_blank" rel="noopener noreferrer" className="text-gray-400 no-underline hover:text-white transition-colors duration-150">GitHub</a>
          <a href="#" className="text-gray-400 no-underline hover:text-white transition-colors duration-150">LinkedIn</a>
          <a href="#" className="text-gray-400 no-underline hover:text-white transition-colors duration-150">Twitter</a>
        </div>
        <p className="text-sm">&copy; 2025 {'{{projectName}}'}. All rights reserved.</p>
      </div>
    </footer>
  );
}

export default PortfolioFooter;
