// templates/styling/tailwind/overlays/portfolio/vue/src/components/PortfolioFooter.vue
<script setup lang="ts">
</script>

<template>
  <footer class="bg-gray-900 text-gray-400 text-center py-8 px-6 mt-auto">
    <div class="flex justify-center gap-4 mb-4">
      <a href="#" title="GitHub" class="text-gray-400 text-xl no-underline transition-colors hover:text-white">&#x1F419;</a>
      <a href="#" title="LinkedIn" class="text-gray-400 text-xl no-underline transition-colors hover:text-white">&#x1F4BC;</a>
      <a href="#" title="Twitter" class="text-gray-400 text-xl no-underline transition-colors hover:text-white">&#x1F426;</a>
      <a href="#" title="Email" class="text-gray-400 text-xl no-underline transition-colors hover:text-white">&#x1F4E7;</a>
    </div>
    <p class="text-sm">&copy; 2025 {{projectName}}. Built with passion.</p>
  </footer>
</template>

// templates/styling/tailwind/overlays/portfolio/react/src/components/PortfolioFooter.tsx
function PortfolioFooter() {
  return (
    <footer className="bg-gray-900 text-gray-400 py-8 px-8 text-center mt-auto">
      <div className="max-w-[1100px] mx-auto">
        <div className="flex gap-8 justify-center mb-4">
          <a href="#" target="_blank" rel="noopener noreferrer" className="text-gray-400 no-underline hover:text-white transition-colors duration-150">GitHub</a>
          <a href="#" className="text-gray-400 no-underline hover:text-white transition-colors duration-150">LinkedIn</a>
          <a href="#" className="text-gray-400 no-underline hover:text-white transition-colors duration-150">Twitter</a>
        </div>
        <p className="text-sm">&copy; 2025 {'{{projectName}}'}. All rights reserved.</p>
      </div>
    </footer>
  );
}

export default PortfolioFooter;
