// templates/styling/tailwind/overlays/portfolio/vue/src/components/ProjectCard.vue
<script setup lang="ts">
import type { Project } from '../data'

defineProps<{ project: Project }>()
</script>

<template>
  <div class="bg-white rounded-lg overflow-hidden shadow-sm transition-all hover:shadow-md hover:-translate-y-0.5">
    <div class="bg-indigo-50 h-36 flex items-center justify-center text-5xl">{{ project.image }}</div>
    <div class="p-5">
      <div class="text-lg font-bold text-gray-900 mb-1.5">{{ project.title }}</div>
      <div class="text-sm text-gray-500 mb-3 leading-relaxed">{{ project.description }}</div>
      <div class="flex flex-wrap gap-1.5">
        <span v-for="tag in project.tags" :key="tag" class="bg-indigo-50 text-indigo-600 text-xs font-semibold px-2.5 py-0.5 rounded-full">{{ tag }}</span>
      </div>
    </div>
  </div>
</template>

// templates/styling/tailwind/overlays/portfolio/react/src/components/ProjectCard.tsx
import type { Project } from '../data/projects';

interface ProjectCardProps {
  project: Project;
}

function ProjectCard({ project }: ProjectCardProps) {
  return (
    <div className="border border-gray-200 rounded-xl overflow-hidden transition-all duration-200 hover:shadow-lg hover:-translate-y-0.5">
      <div className="text-5xl text-center py-8 bg-gray-50">{project.image}</div>
      <div className="p-5">
        <h3 className="text-lg font-semibold mb-2 text-gray-900">{project.title}</h3>
        <p className="text-gray-500 text-sm leading-relaxed mb-4">{project.description}</p>
        <div className="flex flex-wrap gap-1.5">
          {project.tags.map((tag, j) => (
            <span key={j} className="bg-indigo-50 text-indigo-600 px-2.5 py-0.5 rounded text-xs font-medium">{tag}</span>
          ))}
        </div>
      </div>
    </div>
  );
}

export default ProjectCard;
