// templates/styling/tailwind/overlays/portfolio/vue/src/components/SkillsGrid.vue
<script setup lang="ts">
import { skills } from '../data'
</script>

<template>
  <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
    <div v-for="group in skills" :key="group.category" class="bg-white rounded-lg p-5 shadow-sm">
      <h3 class="text-xs uppercase tracking-wider text-indigo-600 font-semibold mb-3">{{ group.category }}</h3>
      <div class="flex flex-wrap gap-1.5">
        <span v-for="item in group.items" :key="item" class="bg-gray-100 text-gray-700 text-sm px-3 py-1 rounded-md">{{ item }}</span>
      </div>
    </div>
  </div>
</template>

// templates/styling/tailwind/overlays/portfolio/react/src/components/SkillsGrid.tsx
import { skills } from '../data/projects';

function SkillsGrid() {
  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 max-w-[1100px] mx-auto">
      {skills.map((group, i) => (
        <div key={i} className="bg-white p-6 rounded-xl border border-gray-200">
          <h3 className="text-base font-semibold mb-4 text-indigo-600">{group.category}</h3>
          <div className="flex flex-wrap gap-2">
            {group.items.map((skill, j) => (
              <span key={j} className="bg-gray-100 px-3 py-1 rounded-md text-sm text-gray-700">{skill}</span>
            ))}
          </div>
        </div>
      ))}
    </div>
  );
}

export default SkillsGrid;
