// templates/overlays/dashboard/react/src/pages/Analytics.tsx
import { ChartPlaceholder } from '../components/ChartPlaceholder';

const metrics = [
  { label: 'Page Views', value: '124,892', change: '+14%' },
  { label: 'Bounce Rate', value: '42.3%', change: '-2.1%' },
  { label: 'Avg. Session', value: '4m 32s', change: '+8%' },
  { label: 'Conversions', value: '1,847', change: '+5.3%' },
];

export function Analytics() {
  return (
    <div className="page-analytics">
      <h1>Analytics</h1>
      <div className="metrics-grid">
        {metrics.map((m, i) => (
          <div key={i} className="metric-card">
            <span className="metric-label">{m.label}</span>
            <div className="metric-value">{m.value}</div>
            <span className="metric-change">{m.change}</span>
          </div>
        ))}
      </div>
      <div className="dashboard-grid">
        <ChartPlaceholder title="Traffic Sources" data={[30, 55, 80, 45, 70, 60, 85, 50, 65, 75, 90, 40]} />
        <ChartPlaceholder title="Conversion Funnel" data={[95, 80, 60, 45, 30, 20, 15, 12, 10, 8, 6, 5]} />
      </div>
      <div className="dashboard-grid">
        <ChartPlaceholder title="Revenue by Channel" data={[70, 50, 85, 40, 60, 75, 55, 90, 45, 65, 80, 70]} />
        <ChartPlaceholder title="User Engagement" data={[20, 35, 50, 65, 45, 70, 55, 80, 60, 75, 85, 90]} />
      </div>
    </div>
  );
}

// templates/overlays/dashboard/vue/src/pages/Analytics.vue
<script setup lang="ts">
import ChartPlaceholder from '../components/ChartPlaceholder.vue';

const metrics = [
  { label: 'Avg. Session', value: '4m 32s' },
  { label: 'Bounce Rate', value: '32.1%' },
  { label: 'Page Views', value: '18,420' },
  { label: 'New Visitors', value: '1,105' },
  { label: 'Top Channel', value: 'Organic' },
  { label: 'Goal Completion', value: '68%' },
];
</script>

<template>
  <div>
    <div class="page-header">
      <h1 class="page-title">Analytics</h1>
      <p class="page-subtitle">Detailed traffic and engagement metrics.</p>
    </div>
    <div class="metrics-row">
      <div v-for="m in metrics" :key="m.label" class="metric-card">
        <p class="metric-value">{{ m.value }}</p>
        <p class="metric-label">{{ m.label }}</p>
      </div>
    </div>
    <div class="charts-grid">
      <ChartPlaceholder title="Traffic Sources" />
      <ChartPlaceholder title="User Engagement" />
    </div>
    <ChartPlaceholder title="Weekly Active Users" />
  </div>
</template>
