// templates/overlays/dashboard/react/src/pages/Overview.tsx
import { KPICards } from '../components/KPICards';
import { ChartPlaceholder } from '../components/ChartPlaceholder';
import { DataTable } from '../components/DataTable';

export function Overview() {
  return (
    <div className="page-overview">
      <div className="page-header">
        <h1>Dashboard</h1>
        <div className="header-actions">
          <input type="text" placeholder="Search..." className="search-input" />
          <div className="user-avatar">B</div>
        </div>
      </div>
      <KPICards />
      <div className="dashboard-grid">
        <ChartPlaceholder title="Revenue Overview" />
        <ChartPlaceholder title="User Growth" />
      </div>
      <DataTable />
    </div>
  );
}

// templates/overlays/dashboard/vue/src/pages/Overview.vue
<script setup lang="ts">
import KPICards from '../components/KPICards.vue';
import ChartPlaceholder from '../components/ChartPlaceholder.vue';
import DataTable from '../components/DataTable.vue';
</script>

<template>
  <div>
    <div class="page-header">
      <h1 class="page-title">Overview</h1>
      <p class="page-subtitle">Welcome back. Here is what is happening today.</p>
    </div>
    <KPICards />
    <ChartPlaceholder title="Monthly Revenue" />
    <DataTable />
  </div>
</template>
