// templates/styling/ant-design/overlays/dashboard/react/src/pages/Users.tsx
import { Typography, Table, Card, Tag, Avatar, Button, Badge } from 'antd';
import { PlusOutlined } from '@ant-design/icons';

const { Title } = Typography;

interface User {
  avatar: string;
  name: string;
  email: string;
  role: string;
  status: 'Active' | 'Inactive';
}

const users: User[] = [
  { avatar: '👩', name: 'Sarah Chen', email: 'sarah@email.com', role: 'Admin', status: 'Active' },
  { avatar: '👨', name: 'James Miller', email: 'james@email.com', role: 'Editor', status: 'Active' },
  { avatar: '👩', name: 'Emily Davis', email: 'emily@email.com', role: 'Viewer', status: 'Inactive' },
  { avatar: '👨', name: 'Robert Wilson', email: 'robert@email.com', role: 'Editor', status: 'Active' },
  { avatar: '👩', name: 'Maria Garcia', email: 'maria@email.com', role: 'Admin', status: 'Active' },
  { avatar: '👨', name: 'David Lee', email: 'david@email.com', role: 'Viewer', status: 'Inactive' },
  { avatar: '👩', name: 'Anna Taylor', email: 'anna@email.com', role: 'Editor', status: 'Active' },
];

const columns = [
  {
    title: 'User',
    key: 'user',
    render: (_: unknown, record: User) => (
      <span style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
        <Avatar>{record.avatar}</Avatar>
        {record.name}
      </span>
    ),
  },
  { title: 'Email', dataIndex: 'email', key: 'email' },
  {
    title: 'Role',
    dataIndex: 'role',
    key: 'role',
    render: (role: string) => <Tag color="blue">{role}</Tag>,
  },
  {
    title: 'Status',
    dataIndex: 'status',
    key: 'status',
    render: (status: string) => (
      <Badge status={status === 'Active' ? 'success' : 'default'} text={status} />
    ),
  },
];

export function Users() {
  return (
    <div>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 }}>
        <Title level={3} style={{ margin: 0 }}>Users</Title>
        <Button type="primary" icon={<PlusOutlined />}>Add User</Button>
      </div>
      <Card>
        <Table dataSource={users} columns={columns} rowKey="email" pagination={false} />
      </Card>
    </div>
  );
}

// templates/overlays/dashboard/vue/src/pages/Users.vue
<script setup lang="ts">
const users = [
  { name: 'Sarah Johnson', email: 'sarah@example.com', role: 'Admin', status: 'Active', badge: 'badge-success', initials: 'SJ' },
  { name: 'Mike Peters', email: 'mike@example.com', role: 'Editor', status: 'Active', badge: 'badge-success', initials: 'MP' },
  { name: 'Emily Chen', email: 'emily@example.com', role: 'Viewer', status: 'Inactive', badge: 'badge-danger', initials: 'EC' },
  { name: 'James Wilson', email: 'james@example.com', role: 'Editor', status: 'Active', badge: 'badge-success', initials: 'JW' },
  { name: 'Anna Lee', email: 'anna@example.com', role: 'Admin', status: 'Active', badge: 'badge-success', initials: 'AL' },
  { name: 'Tom Davis', email: 'tom@example.com', role: 'Viewer', status: 'Pending', badge: 'badge-warning', initials: 'TD' },
  { name: 'Lisa Brown', email: 'lisa@example.com', role: 'Editor', status: 'Active', badge: 'badge-success', initials: 'LB' },
];
</script>

<template>
  <div>
    <div class="page-header">
      <h1 class="page-title">Users</h1>
      <p class="page-subtitle">Manage your team members and their permissions.</p>
    </div>
    <div class="data-table-wrapper">
      <div class="table-header">All Users</div>
      <table class="data-table">
        <thead>
          <tr>
            <th>User</th>
            <th>Email</th>
            <th>Role</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="user in users" :key="user.email">
            <td style="display:flex;align-items:center;gap:0.75rem;">
              <span class="user-avatar">{{ user.initials }}</span>
              {{ user.name }}
            </td>
            <td>{{ user.email }}</td>
            <td>{{ user.role }}</td>
            <td><span :class="['badge', user.badge]">{{ user.status }}</span></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>
