// templates/styling/tailwind/overlays/landing/nextjs/src/app/components/Hero.tsx
export function Hero() {
  return (
    <header className="bg-gradient-to-br from-indigo-500 to-purple-700 text-white pb-16">
      <nav className="flex justify-between items-center px-8 py-4 max-w-7xl mx-auto">
        <div className="text-2xl font-bold text-white">{'{{projectName}}'}</div>
        <div className="flex gap-8">
          <a href="#features" className="text-white/90 font-medium hover:text-white transition-colors">Features</a>
          <a href="#cta" className="text-white/90 font-medium hover:text-white transition-colors">Pricing</a>
          <a href="#contact" className="text-white/90 font-medium hover:text-white transition-colors">Contact</a>
        </div>
      </nav>
      <div className="text-center px-8 py-16 max-w-4xl mx-auto">
        <h1 className="text-4xl sm:text-5xl lg:text-6xl font-extrabold mb-6 leading-tight">Build Something Amazing</h1>
        <p className="text-lg sm:text-xl opacity-90 mb-8">A modern landing page template to kickstart your next project.</p>
        <div className="flex gap-4 justify-center">
          <button className="px-6 py-3 rounded-lg text-base font-semibold cursor-pointer border-2 border-indigo-600 bg-indigo-600 text-white hover:bg-indigo-700 hover:border-indigo-700 transition-colors">Get Started</button>
          <button className="px-6 py-3 rounded-lg text-base font-semibold cursor-pointer border-2 border-white/50 bg-transparent text-white hover:bg-white/10 transition-colors">Learn More</button>
        </div>
      </div>
    </header>
  );
}

// templates/styling/tailwind/overlays/landing/angular/src/app/components/hero.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-hero',
  standalone: true,
  template: `
    <header class="bg-gradient-to-br from-indigo-600 to-purple-700 text-white pb-16">
      <nav class="flex justify-between items-center px-6 py-4 max-w-7xl mx-auto">
        <div class="text-2xl font-bold">{{projectName}}</div>
        <div class="flex gap-8">
          <a href="#features" class="text-white/90 hover:text-white font-medium transition-colors">Features</a>
          <a href="#cta" class="text-white/90 hover:text-white font-medium transition-colors">Pricing</a>
          <a href="#contact" class="text-white/90 hover:text-white font-medium transition-colors">Contact</a>
        </div>
      </nav>
      <div class="text-center px-6 pt-16 max-w-3xl mx-auto">
        <h1 class="text-4xl sm:text-5xl lg:text-6xl font-extrabold mb-6">Build Something Amazing</h1>
        <p class="text-lg sm:text-xl text-white/90 mb-8">A modern landing page template to kickstart your next project.</p>
        <div class="flex gap-4 justify-center flex-wrap">
          <button class="px-6 py-3 bg-indigo-500 hover:bg-indigo-400 text-white font-semibold rounded-lg border-2 border-indigo-500 hover:border-indigo-400 transition-colors">Get Started</button>
          <button class="px-6 py-3 bg-transparent text-white font-semibold rounded-lg border-2 border-white/50 hover:border-white transition-colors">Learn More</button>
        </div>
      </div>
    </header>
  `,
  styles: []
})
export class HeroComponent {}
