// templates/styling/angular-material/overlays/ecommerce/angular/src/app/pages/home.component.ts
import { Component, inject, signal } from '@angular/core';
import { ProductCardComponent } from '../components/product-card.component';
import { Product, PRODUCTS } from '../data/products';
import { AppComponent } from '../app.component';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatIconModule } from '@angular/material/icon';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [ProductCardComponent, MatFormFieldModule, MatInputModule, MatIconModule],
  template: `
    <div class="home-page">
      <div class="home-hero">
        <h1>Discover Amazing Products</h1>
        <mat-form-field appearance="outline" class="search-field">
          <mat-label>Search products</mat-label>
          <input matInput [value]="search()" (input)="search.set($any($event.target).value)" />
          <mat-icon matPrefix>search</mat-icon>
        </mat-form-field>
      </div>
      <div class="product-grid">
        @for (product of filtered(); track product.id) {
          <app-product-card
            [product]="product"
            (addToCart)="onAddToCart($event)"
          />
        }
      </div>
    </div>
  `,
  styles: [`
    .home-hero { text-align: center; margin-bottom: 32px; }
    .home-hero h1 { font-size: 2rem; color: #212121; margin-bottom: 16px; }
    .search-field { width: 100%; max-width: 400px; }
    .product-grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(260px, 1fr));
      gap: 24px;
    }
  `]
})
export class HomeComponent {
  private app = inject(AppComponent);
  search = signal<string>('');

  filtered = (): Product[] => {
    const query = this.search().toLowerCase();
    return PRODUCTS.filter(
      (product: Product) =>
        product.name.toLowerCase().includes(query) ||
        product.category.toLowerCase().includes(query)
    );
  };

  onAddToCart(product: Product): void {
    this.app.addToCart(product);
  }
}

// templates/styling/css-modules/overlays/ecommerce/vue/src/pages/Home.vue
<script setup lang="ts">
import { ref, computed, inject } from 'vue';
import type { Product } from '../data';
import { products } from '../data';
import ProductCard from '../components/ProductCard.vue';

const addToCart = inject<(p: Product) => void>('addToCart')!;
const search = ref('');
const filtered = computed(() =>
  products.filter(p => p.name.toLowerCase().includes(search.value.toLowerCase()))
);
</script>

<template>
  <main :class="$style.pageContainer">
    <h2 :class="$style.pageTitle">All Products</h2>
    <input v-model="search" type="text" :class="$style.searchBar" placeholder="Search products..." />
    <div :class="$style.productGrid">
      <ProductCard
        v-for="p in filtered"
        :key="p.id"
        :product="p"
        @add-to-cart="addToCart"
      />
    </div>
  </main>
</template>

<style module>
.pageContainer { flex: 1; max-width: 1200px; margin: 0 auto; padding: 2rem; width: 100%; }
.pageTitle { font-size: 1.75rem; font-weight: 700; color: #111827; margin-bottom: 1.5rem; }
.searchBar { padding: 0.75rem 1rem; border: 1px solid #d1d5db; border-radius: 8px; width: 100%; max-width: 400px; margin-bottom: 1.5rem; font-size: 0.95rem; }
.searchBar:focus { outline: none; border-color: #4f46e5; box-shadow: 0 0 0 3px rgba(79, 70, 229, 0.1); }
.productGrid { display: grid; grid-template-columns: repeat(auto-fill, minmax(260px, 1fr)); gap: 1.5rem; }
</style>
