// templates/styling/styled-components/overlays/ecommerce/react/src/pages/ProductDetail.tsx
import { useParams, Link } from 'react-router-dom';
import styled from 'styled-components';
import { products, Product } from '../data/products';

const ProductDetailWrapper = styled.div`
  max-width: 900px;
  margin: 0 auto;
`;

const BackLink = styled(Link)`
  color: #4f46e5;
  text-decoration: none;
  font-weight: 500;
  display: inline-block;
  margin-bottom: 1.5rem;

  &:hover {
    text-decoration: underline;
  }
`;

const DetailContent = styled.div`
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 3rem;
  align-items: start;

  @media (max-width: 768px) {
    grid-template-columns: 1fr;
    gap: 1.5rem;
  }
`;

const DetailImage = styled.div`
  font-size: 8rem;
  text-align: center;
  padding: 3rem;
  background: #f9fafb;
  border-radius: 12px;

  @media (max-width: 768px) {
    font-size: 5rem;
    padding: 2rem;
  }
`;

const DetailInfo = styled.div`
  h1 {
    font-size: 1.75rem;
    font-weight: 700;
    color: #111827;
    margin: 0.25rem 0 1rem;
  }
`;

const ProductCategory = styled.span`
  font-size: 0.75rem;
  color: #4f46e5;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.05em;
`;

const DetailDescription = styled.p`
  color: #374151;
  font-size: 1rem;
  line-height: 1.6;
  margin-bottom: 1.5rem;
`;

const DetailPrice = styled.span`
  font-size: 2rem;
  font-weight: 700;
  color: #111827;
  display: block;
  margin-bottom: 1.5rem;
`;

const AddToCartButton = styled.button`
  background: #4f46e5;
  color: white;
  border: none;
  padding: 0.75rem 2rem;
  border-radius: 8px;
  cursor: pointer;
  font-weight: 500;
  font-size: 1rem;

  &:hover {
    background: #4338ca;
  }
`;

const NotFound = styled.div`
  text-align: center;
  padding: 4rem 0;

  h2 {
    color: #374151;
    margin-bottom: 1rem;
  }
`;

interface ProductDetailProps {
  addToCart: (product: Product) => void;
}

export function ProductDetail({ addToCart }: ProductDetailProps) {
  const { id } = useParams<{ id: string }>();
  const product = products.find((p) => p.id === Number(id));

  if (!product) {
    return (
      <NotFound>
        <h2>Product Not Found</h2>
        <BackLink to="/">Back to Shop</BackLink>
      </NotFound>
    );
  }

  return (
    <ProductDetailWrapper>
      <BackLink to="/">← Back to Shop</BackLink>
      <DetailContent>
        <DetailImage>{product.image}</DetailImage>
        <DetailInfo>
          <ProductCategory>{product.category}</ProductCategory>
          <h1>{product.name}</h1>
          <DetailDescription>{product.description}</DetailDescription>
          <DetailPrice>${product.price.toFixed(2)}</DetailPrice>
          <AddToCartButton onClick={() => addToCart(product)}>
            Add to Cart
          </AddToCartButton>
        </DetailInfo>
      </DetailContent>
    </ProductDetailWrapper>
  );
}

// templates/styling/css-modules/overlays/ecommerce/vue/src/pages/ProductDetail.vue
<script setup lang="ts">
import { computed, inject } from 'vue';
import { useRoute } from 'vue-router';
import type { Product } from '../data';
import { products } from '../data';

const route = useRoute();
const addToCart = inject<(p: Product) => void>('addToCart')!;
const product = computed(() => products.find(p => p.id === Number(route.params.id)));
</script>

<template>
  <main :class="$style.pageContainer">
    <RouterLink to="/" :class="$style.backLink">&#8592; Back to Products</RouterLink>
    <div v-if="product" :class="$style.detailLayout">
      <div :class="$style.detailEmoji">{{ product.emoji }}</div>
      <div>
        <span :class="$style.detailCategory">{{ product.category }}</span>
        <h1 :class="$style.detailName">{{ product.name }}</h1>
        <p :class="$style.detailPrice">${{ product.price.toFixed(2) }}</p>
        <p :class="$style.detailDesc">{{ product.description }}</p>
        <button :class="$style.btnPrimary" @click="addToCart(product)">Add to Cart</button>
      </div>
    </div>
    <p v-else :class="$style.cartEmpty">Product not found.</p>
  </main>
</template>

<style module>
.pageContainer { flex: 1; max-width: 1200px; margin: 0 auto; padding: 2rem; width: 100%; }
.backLink { display: inline-block; color: #4f46e5; font-weight: 500; margin-bottom: 1.5rem; }
.detailLayout { display: grid; grid-template-columns: 1fr 1fr; gap: 3rem; align-items: start; }
.detailEmoji { font-size: 8rem; text-align: center; padding: 4rem; background: #f9fafb; border-radius: 12px; }
.detailCategory { font-size: 0.8rem; color: #4f46e5; font-weight: 600; text-transform: uppercase; }
.detailName { font-size: 2rem; font-weight: 700; color: #111827; margin: 0.5rem 0; }
.detailPrice { font-size: 1.75rem; font-weight: 700; color: #4f46e5; margin-bottom: 1rem; }
.detailDesc { color: #6b7280; line-height: 1.8; margin-bottom: 2rem; }
.btnPrimary { background: #4f46e5; color: #ffffff; border: none; padding: 0.5rem 1rem; border-radius: 8px; font-weight: 600; transition: background 0.2s; }
.btnPrimary:hover { background: #4338ca; }
.cartEmpty { text-align: center; padding: 4rem 2rem; color: #9ca3af; font-size: 1.1rem; }
@media (max-width: 768px) { .detailLayout { grid-template-columns: 1fr; } }
</style>
