// templates/styling/chakra-ui/overlays/landing/nextjs/src/app/page.tsx
'use client';

import { Hero } from './components/Hero';
import { Features } from './components/Features';
import { CTA } from './components/CTA';
import { Footer } from './components/Footer';
import { Box } from '@chakra-ui/react';

export default function Home() {
  return (
    <Box minH="100vh">
      <Hero />
      <Features />
      <CTA />
      <Footer />
    </Box>
  );
}

// templates/styling/css-modules/overlays/landing/vue/src/App.vue
<script setup lang="ts">
import Hero from './components/Hero.vue';
import Features from './components/Features.vue';
import CTA from './components/CTA.vue';
import AppFooter from './components/AppFooter.vue';
</script>

<template>
  <div :class="$style.landing">
    <Hero />
    <Features />
    <CTA />
    <AppFooter />
  </div>
</template>

<style module>
.landing { min-height: 100vh; }
</style>
