// templates/styling/tailwind/overlays/crm/vue/src/components/ContactsTable.vue
<script setup lang="ts">
import type { Contact } from '../data'

defineProps<{ contacts: Contact[] }>()

const badgeClass = (status: string) => {
  switch (status) {
    case 'Lead': return 'bg-blue-100 text-blue-800'
    case 'Prospect': return 'bg-amber-100 text-amber-800'
    case 'Customer': return 'bg-emerald-100 text-emerald-800'
    case 'Churned': return 'bg-red-100 text-red-800'
    default: return 'bg-gray-100 text-gray-800'
  }
}
</script>

<template>
  <div class="bg-white rounded-lg shadow-sm overflow-hidden">
    <table class="w-full border-collapse">
      <thead>
        <tr>
          <th class="text-left px-4 py-3 text-xs uppercase tracking-wider text-gray-500 bg-gray-50 border-b border-gray-200">Name</th>
          <th class="text-left px-4 py-3 text-xs uppercase tracking-wider text-gray-500 bg-gray-50 border-b border-gray-200">Email</th>
          <th class="text-left px-4 py-3 text-xs uppercase tracking-wider text-gray-500 bg-gray-50 border-b border-gray-200">Company</th>
          <th class="text-left px-4 py-3 text-xs uppercase tracking-wider text-gray-500 bg-gray-50 border-b border-gray-200">Phone</th>
          <th class="text-left px-4 py-3 text-xs uppercase tracking-wider text-gray-500 bg-gray-50 border-b border-gray-200">Status</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="contact in contacts" :key="contact.id" class="hover:bg-gray-50">
          <td class="px-4 py-3 border-b border-gray-100 text-sm">{{ contact.name }}</td>
          <td class="px-4 py-3 border-b border-gray-100 text-sm">{{ contact.email }}</td>
          <td class="px-4 py-3 border-b border-gray-100 text-sm">{{ contact.company }}</td>
          <td class="px-4 py-3 border-b border-gray-100 text-sm">{{ contact.phone }}</td>
          <td class="px-4 py-3 border-b border-gray-100 text-sm"><span :class="['inline-block px-2.5 py-0.5 rounded-full text-xs font-semibold', badgeClass(contact.status)]">{{ contact.status }}</span></td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

// templates/styling/tailwind/overlays/crm/angular/src/app/components/contacts-table.component.ts
import { Component, Input } from '@angular/core';

interface Contact {
  id: number;
  name: string;
  email: string;
  company: string;
  status: string;
  phone: string;
}

@Component({
  selector: 'app-contacts-table',
  standalone: true,
  template: `
    <div class="overflow-x-auto">
      <table class="w-full border-collapse bg-white rounded-xl overflow-hidden shadow-sm">
        <thead>
          <tr>
            <th class="text-left px-4 py-3 bg-gray-50 text-gray-500 text-xs uppercase tracking-wider font-semibold">Name</th>
            <th class="text-left px-4 py-3 bg-gray-50 text-gray-500 text-xs uppercase tracking-wider font-semibold">Email</th>
            <th class="text-left px-4 py-3 bg-gray-50 text-gray-500 text-xs uppercase tracking-wider font-semibold">Company</th>
            <th class="text-left px-4 py-3 bg-gray-50 text-gray-500 text-xs uppercase tracking-wider font-semibold">Phone</th>
            <th class="text-left px-4 py-3 bg-gray-50 text-gray-500 text-xs uppercase tracking-wider font-semibold">Status</th>
          </tr>
        </thead>
        <tbody>
          @for (contact of contacts; track contact.id) {
            <tr>
              <td class="px-4 py-3 border-t border-gray-100 text-sm font-semibold text-gray-900">{{ contact.name }}</td>
              <td class="px-4 py-3 border-t border-gray-100 text-sm text-gray-700">{{ contact.email }}</td>
              <td class="px-4 py-3 border-t border-gray-100 text-sm text-gray-700">{{ contact.company }}</td>
              <td class="px-4 py-3 border-t border-gray-100 text-sm text-gray-700">{{ contact.phone }}</td>
              <td class="px-4 py-3 border-t border-gray-100 text-sm">
                <span
                  class="inline-block px-2.5 py-1 rounded-xl text-xs font-medium"
                  [class.bg-emerald-100]="contact.status === 'Customer'"
                  [class.text-emerald-800]="contact.status === 'Customer'"
                  [class.bg-blue-100]="contact.status === 'Lead'"
                  [class.text-blue-800]="contact.status === 'Lead'"
                  [class.bg-amber-100]="contact.status === 'Prospect'"
                  [class.text-amber-800]="contact.status === 'Prospect'"
                  [class.bg-red-100]="contact.status === 'Churned'"
                  [class.text-red-800]="contact.status === 'Churned'"
                >
                  {{ contact.status }}
                </span>
              </td>
            </tr>
          }
        </tbody>
      </table>
    </div>
  `,
  styles: []
})
export class ContactsTableComponent {
  @Input() contacts: Contact[] = [];
}
