// templates/styling/tailwind/overlays/crm/react/src/pages/Contacts.tsx
import { useState } from 'react';
import ContactsTable from '../components/ContactsTable';
import { contacts } from '../data/contacts';

function Contacts() {
  const [search, setSearch] = useState('');

  const filtered = contacts.filter(
    (c) =>
      c.name.toLowerCase().includes(search.toLowerCase()) ||
      c.email.toLowerCase().includes(search.toLowerCase()) ||
      c.company.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div>
      <header className="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-8 gap-4">
        <h1 className="text-2xl font-bold text-gray-900">Contacts</h1>
        <input
          type="text"
          className="w-full sm:w-64 px-4 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:border-indigo-600 focus:ring-2 focus:ring-indigo-600/15"
          placeholder="Search contacts..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />
      </header>
      <ContactsTable contacts={filtered} />
    </div>
  );
}

export default Contacts;

// templates/styling/tailwind/overlays/crm/nuxt/pages/contacts.vue
<script setup lang="ts">
const search = ref('');
</script>

<template>
  <div>
    <div class="flex justify-between items-start mb-6">
      <div>
        <h1 class="text-2xl font-bold text-gray-900 mb-1">Contacts</h1>
        <p class="text-gray-500">Manage your customer relationships.</p>
      </div>
      <button class="bg-indigo-600 text-white border-none px-5 py-2.5 rounded-lg font-semibold cursor-pointer hover:bg-indigo-700 transition-colors">+ Add Contact</button>
    </div>

    <div class="mb-5">
      <input
        v-model="search"
        type="text"
        placeholder="Search contacts..."
        class="w-full max-w-md px-4 py-2.5 border border-gray-300 rounded-lg text-sm outline-none focus:border-indigo-600 focus:ring-2 focus:ring-indigo-600/10"
      />
    </div>

    <ContactsTable :search-query="search" />
  </div>
</template>
