// templates/overlays/dashboard/nuxt/components/DataTable.vue
<script setup lang="ts">
const orders = [
  { id: '#ORD-001', customer: 'Alice Johnson', product: 'Wireless Headphones', amount: '$79.99', status: 'Completed', date: '2024-01-15' },
  { id: '#ORD-002', customer: 'Bob Smith', product: 'Running Shoes', amount: '$129.99', status: 'Processing', date: '2024-01-14' },
  { id: '#ORD-003', customer: 'Carol Williams', product: 'Coffee Maker', amount: '$49.99', status: 'Completed', date: '2024-01-14' },
  { id: '#ORD-004', customer: 'David Brown', product: 'Backpack', amount: '$59.99', status: 'Shipped', date: '2024-01-13' },
  { id: '#ORD-005', customer: 'Eva Martinez', product: 'Smartwatch', amount: '$199.99', status: 'Pending', date: '2024-01-13' },
];
</script>

<template>
  <div class="table-card">
    <h3 class="table-title">Recent Orders</h3>
    <div class="table-wrapper">
      <table class="data-table">
        <thead>
          <tr>
            <th>Order ID</th>
            <th>Customer</th>
            <th>Product</th>
            <th>Amount</th>
            <th>Status</th>
            <th>Date</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="order in orders" :key="order.id">
            <td class="order-id">{{ order.id }}</td>
            <td>{{ order.customer }}</td>
            <td>{{ order.product }}</td>
            <td class="amount">{{ order.amount }}</td>
            <td>
              <span :class="['status-badge', order.status.toLowerCase()]">
                {{ order.status }}
              </span>
            </td>
            <td class="date">{{ order.date }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<style scoped>
.table-card {
  background: white;
  border-radius: 10px;
  padding: 1.5rem;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.08);
}

.table-title {
  font-size: 1.1rem;
  color: #111827;
  margin-bottom: 1rem;
}

.table-wrapper {
  overflow-x: auto;
}

.data-table {
  width: 100%;
  border-collapse: collapse;
}

.data-table th {
  text-align: left;
  padding: 0.75rem 1rem;
  font-size: 0.8rem;
  font-weight: 600;
  color: #6b7280;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  border-bottom: 2px solid #e5e7eb;
}

.data-table td {
  padding: 0.875rem 1rem;
  font-size: 0.9rem;
  border-bottom: 1px solid #f3f4f6;
}

.order-id {
  font-weight: 600;
  color: #4f46e5;
}

.amount {
  font-weight: 600;
  color: #111827;
}

.date {
  color: #6b7280;
}

.status-badge {
  display: inline-block;
  padding: 0.2rem 0.65rem;
  border-radius: 20px;
  font-size: 0.75rem;
  font-weight: 600;
}

.status-badge.completed {
  background: #d1fae5;
  color: #065f46;
}

.status-badge.processing {
  background: #dbeafe;
  color: #1e40af;
}

.status-badge.shipped {
  background: #fef3c7;
  color: #92400e;
}

.status-badge.pending {
  background: #f3f4f6;
  color: #374151;
}
</style>

// templates/overlays/dashboard/angular/src/app/components/data-table.component.ts
import { Component } from '@angular/core';

interface OrderItem {
  id: number;
  customer: string;
  amount: string;
  status: 'Completed' | 'Shipped' | 'Pending' | 'Cancelled';
}

@Component({
  selector: 'app-data-table',
  standalone: true,
  template: `
    <div class="orders-table-card">
      <h3 class="orders-table-title">Recent Orders</h3>
      <table class="orders-table">
        <thead>
          <tr>
            <th>Order</th>
            <th>Customer</th>
            <th>Amount</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          @for (order of orders; track order.id) {
            <tr>
              <td>#{{ order.id }}</td>
              <td>{{ order.customer }}</td>
              <td>{{ order.amount }}</td>
              <td>
                <span
                  class="orders-table-badge"
                  [class]="order.status.toLowerCase()"
                >
                  {{ order.status }}
                </span>
              </td>
            </tr>
          }
        </tbody>
      </table>
    </div>
  `,
  styles: [`
    .orders-table-card {
      background: #fff;
      border-radius: 12px;
      padding: 1.25rem;
      border: 1px solid #e5e7eb;
    }

    .orders-table-title {
      font-size: 1rem;
      color: #111827;
      margin-bottom: 1rem;
    }

    .orders-table {
      width: 100%;
      border-collapse: collapse;
    }

    .orders-table th {
      text-align: left;
      padding: 0.6rem;
      font-size: 0.75rem;
      color: #6b7280;
      text-transform: uppercase;
      border-bottom: 2px solid #e5e7eb;
    }

    .orders-table td {
      padding: 0.75rem 0.6rem;
      border-bottom: 1px solid #f3f4f6;
      font-size: 0.875rem;
    }

    .orders-table-badge {
      padding: 0.2rem 0.6rem;
      border-radius: 9999px;
      font-size: 0.75rem;
      font-weight: 600;
    }

    .completed {
      background: #d1fae5;
      color: #059669;
    }

    .pending {
      background: #fef3c7;
      color: #d97706;
    }

    .shipped {
      background: #dbeafe;
      color: #2563eb;
    }

    .cancelled {
      background: #fee2e2;
      color: #dc2626;
    }
  `]
})
export class DataTableComponent {
  orders: OrderItem[] = [
    {
      id: 1041,
      customer: 'Alice Johnson',
      amount: '$125.00',
      status: 'Completed',
    },
    {
      id: 1040,
      customer: 'Bob Smith',
      amount: '$89.50',
      status: 'Shipped',
    },
    {
      id: 1039,
      customer: 'Carol Davis',
      amount: '$245.00',
      status: 'Pending',
    },
    {
      id: 1038,
      customer: 'Dan Wilson',
      amount: '$67.25',
      status: 'Completed',
    },
    {
      id: 1037,
      customer: 'Eve Martinez',
      amount: '$312.00',
      status: 'Cancelled',
    },
  ];
}
