// templates/overlays/portfolio/vue/src/components/PortfolioFooter.vue
<script setup lang="ts">
</script>

<template>
  <footer class="portfolio-footer">
    <div class="social-links">
      <a href="#" title="GitHub">🐙</a>
      <a href="#" title="LinkedIn">💼</a>
      <a href="#" title="Twitter">🐦</a>
      <a href="#" title="Email">📧</a>
    </div>
    <p class="copyright">&copy; 2025 {{projectName}}. Built with passion.</p>
  </footer>
</template>

// templates/overlays/portfolio/react/src/components/PortfolioFooter.tsx
function PortfolioFooter() {
  return (
    <footer className="portfolio-footer">
      <div className="footer-content">
        <div className="footer-links">
          <a href="#" target="_blank" rel="noopener noreferrer">GitHub</a>
          <a href="#">LinkedIn</a>
          <a href="#">Twitter</a>
        </div>
        <p>&copy; 2025 {'{{projectName}}'}. All rights reserved.</p>
      </div>
    </footer>
  );
}

export default PortfolioFooter;
