// templates/styling/tailwind/overlays/dashboard/nuxt/components/ChartPlaceholder.vue
<script setup lang="ts">
defineProps<{
  title: string;
}>();

const bars = [
  { label: 'Mon', height: 65 },
  { label: 'Tue', height: 80 },
  { label: 'Wed', height: 45 },
  { label: 'Thu', height: 90 },
  { label: 'Fri', height: 70 },
  { label: 'Sat', height: 55 },
  { label: 'Sun', height: 75 },
];
</script>

<template>
  <div class="bg-white rounded-lg p-6 shadow-sm">
    <h3 class="text-lg font-semibold text-gray-900 mb-6">{{ title }}</h3>
    <div class="flex items-end gap-4 h-[200px] pt-4">
      <div v-for="bar in bars" :key="bar.label" class="flex-1 flex flex-col items-center h-full justify-end">
        <div
          class="w-full max-w-[40px] bg-gradient-to-t from-indigo-600 to-indigo-400 rounded-t transition-all duration-300"
          :style="{ height: bar.height + '%' }"
        ></div>
        <span class="text-xs text-gray-500 mt-2">{{ bar.label }}</span>
      </div>
    </div>
  </div>
</template>

// templates/styling/tailwind/overlays/dashboard/react/src/components/ChartPlaceholder.tsx
interface ChartPlaceholderProps {
  title: string;
  data?: number[];
}

export function ChartPlaceholder({ title, data }: ChartPlaceholderProps) {
  const bars = data || [40, 65, 45, 80, 55, 70, 90, 60, 75, 50, 85, 95];

  return (
    <div className="bg-white rounded-xl p-4 lg:p-6 border border-gray-200">
      <h3 className="text-lg font-semibold mb-4 text-gray-900">{title}</h3>
      <div className="h-48 lg:h-52 flex items-end">
        <div className="flex gap-2 items-end h-full w-full">
          {bars.map((h, i) => (
            <div
              key={i}
              className="flex-1 bg-gradient-to-t from-indigo-600 to-indigo-400 rounded-t min-w-3 transition-all duration-300"
              style={{ height: `${h}%` }}
            />
          ))}
        </div>
      </div>
    </div>
  );
}
