// templates/styling/css-modules/overlays/portfolio/nuxt/components/PortfolioFooter.vue
<template>
  <footer :class="$style.portfolioFooter">
    <div :class="$style.footerInner">
      <p>&copy; 2024 {{projectName}}. All rights reserved.</p>
      <div :class="$style.footerLinks">
        <NuxtLink to="/">Home</NuxtLink>
        <NuxtLink to="/projects">Projects</NuxtLink>
        <NuxtLink to="/about">About</NuxtLink>
        <NuxtLink to="/contact">Contact</NuxtLink>
      </div>
    </div>
  </footer>
</template>

<style module>
.portfolioFooter {
  background: #111827;
  color: #9ca3af;
  padding: 2rem 1.5rem;
  margin-top: auto;
}

.footerInner {
  max-width: 1200px;
  margin: 0 auto;
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.footerInner p {
  font-size: 0.875rem;
}

.footerLinks {
  display: flex;
  gap: 1.25rem;
}

.footerLinks a {
  color: #9ca3af;
  font-size: 0.875rem;
  transition: color 0.2s;
}

.footerLinks a:hover {
  color: white;
}
</style>

// templates/styling/styled-components/overlays/portfolio/react/src/components/PortfolioFooter.tsx
import styled from 'styled-components';

const StyledFooter = styled.footer`
  background: #111827;
  color: #9ca3af;
  padding: 2rem;
  text-align: center;
  margin-top: auto;
`;

const FooterContent = styled.div`
  max-width: 1100px;
  margin: 0 auto;

  p {
    font-size: 0.85rem;
  }
`;

const FooterLinks = styled.div`
  display: flex;
  gap: 2rem;
  justify-content: center;
  margin-bottom: 1rem;

  a {
    color: #9ca3af;
    text-decoration: none;

    &:hover {
      color: white;
    }
  }
`;

function PortfolioFooter() {
  return (
    <StyledFooter>
      <FooterContent>
        <FooterLinks>
          <a href="#" target="_blank" rel="noopener noreferrer">GitHub</a>
          <a href="#">LinkedIn</a>
          <a href="#">Twitter</a>
        </FooterLinks>
        <p>&copy; 2025 {'{{projectName}}'}. All rights reserved.</p>
      </FooterContent>
    </StyledFooter>
  );
}

export default PortfolioFooter;
