// templates/overlays/ecommerce/vue/src/pages/Cart.vue
<script setup lang="ts">
import { computed, inject, type Ref } from 'vue';
import type { CartItem } from '../data';

const cart = inject<Ref<CartItem[]>>('cart')!;
const removeFromCart = inject<(id: number) => void>('removeFromCart')!;
const total = computed(() => cart.value.reduce((sum, item) => sum + item.price * item.quantity, 0));
</script>

<template>
  <main class="page-container">
    <h2 class="page-title">Shopping Cart</h2>
    <div v-if="cart.length === 0" class="cart-empty">
      <p>Your cart is empty.</p>
      <RouterLink to="/" class="btn-primary" style="display:inline-block;margin-top:1rem;">Browse Products</RouterLink>
    </div>
    <template v-else>
      <div class="cart-list">
        <div v-for="item in cart" :key="item.id" class="cart-item">
          <span class="cart-item-emoji">{{ item.emoji }}</span>
          <div class="cart-item-info">
            <p class="cart-item-name">{{ item.name }}</p>
            <p class="cart-item-meta">Qty: {{ item.quantity }} &times; ${{ item.price.toFixed(2) }}</p>
          </div>
          <button class="btn-remove" @click="removeFromCart(item.id)">Remove</button>
        </div>
      </div>
      <div class="cart-summary">
        <span class="cart-total">Total: ${{ total.toFixed(2) }}</span>
        <button class="btn-primary">Checkout</button>
      </div>
    </template>
  </main>
</template>

// templates/styling/css-modules/overlays/ecommerce/react/src/pages/Cart.tsx
import { Link } from 'react-router-dom';
import { CartItem } from '../data/products';
import styles from './Cart.module.css';

interface CartProps {
  cart: CartItem[];
  removeFromCart: (id: number) => void;
}

export function Cart({ cart, removeFromCart }: CartProps) {
  const total = cart.reduce((sum, item) => sum + item.price * item.quantity, 0);

  if (cart.length === 0) {
    return (
      <div className={styles.cartPage}>
        <h2>Shopping Cart</h2>
        <div className={styles.cartEmpty}>
          <p>Your cart is empty</p>
          <Link to="/" className={styles.continueLink}>Continue Shopping</Link>
        </div>
      </div>
    );
  }

  return (
    <div className={styles.cartPage}>
      <h2>Shopping Cart ({cart.length} items)</h2>
      <div className={styles.cartLayout}>
        <div className={styles.cartItemsList}>
          {cart.map((item) => (
            <div key={item.id} className={styles.cartRow}>
              <span className={styles.cartRowImage}>{item.image}</span>
              <div className={styles.cartRowInfo}>
                <Link to={`/product/${item.id}`}><h4>{item.name}</h4></Link>
                <p>Qty: {item.quantity}</p>
              </div>
              <span className={styles.cartRowPrice}>${(item.price * item.quantity).toFixed(2)}</span>
              <button className={styles.cartRowRemove} onClick={() => removeFromCart(item.id)}>Remove</button>
            </div>
          ))}
        </div>
        <div className={styles.cartSummary}>
          <h3>Order Summary</h3>
          <div className={styles.summaryRow}><span>Subtotal</span><span>${total.toFixed(2)}</span></div>
          <div className={styles.summaryRow}><span>Shipping</span><span>Free</span></div>
          <div className={styles.summaryRowTotal}><span>Total</span><strong>${total.toFixed(2)}</strong></div>
          <button className={styles.checkoutBtn}>Checkout</button>
        </div>
      </div>
    </div>
  );
}
